### ISSUE TITLE
html content assist for STS

### ISSUE THREAD

**Issue by Yang09701194** [spring-projects/sts4#1034]
eclipse preferences has html content assist, I set `prompt when these characters are inserted`, in .html file it works and assist a lot, would it be added to STS... ?

![eclipse preferences](https://i.imgur.com/e16pDtE.png)

**Comment by BoykoAlex** [comment]
I do not think this is possible to implement at the moment... You mean you'd like to customize trigger characters for application YAML/Properties files? Or are you thinking of having the settings in the screenshot for HTML, CSS, JSP, XML files?

STS currently takes advantage of [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/). The protocol only allows setting trigger chars at the initialization step. There is no protocol support to change trigger chars on the fly as far I understand.
Majority of editors in STS4 are LSP-based with [LSP4E](https://github.com/eclipse/lsp4e) project as a common layer. Therefore, don't think that XML/HTML/CSS would have trigger chars support at the moment... likely they won't have for some foreseeable future. The only option is have a preference just like above but it would take effect only after the IDE is restarted. You'd have to request this feature from here: https://github.com/eclipse/wildwebdeveloper.

If it is the Spring Boot properties files you are inquiring about, perhaps we could look into this with a limitation that IDE re-start is required for the new trigger chars to take effect.

**Comment by martinlippert** [comment]
As Alex mentioned, the HTML and XML support that we currently ship with the Spring Tools for Eclipse distribution is based on the Wild Web Developer project. If you would like to use the traditional HTML and XML support instead of the Wild Web Developer one, you could uninstall the Wild Web Developer related features and install the traditional Web Tools components instead. It requires some manual tweaking of your installation (uninstall, install, etc.), but it should be possible.

We don't ship the traditional HTML and XML tooling anymore because we opted into using the Wild Web Developer one - and having both installed (which is also possible) results in some quite confusing experience where you multiple editors and preferences for e.g. HTML files. But if you would like to give it a try, feel free to install the traditional Web Tools via `Install New Software`, then select the main Eclipse update site, and go from there.

**Comment by martinlippert** [comment]
So the two options are:
- ask the Wild Web Developer tooling projects to add those preferences
- install the traditional Web Tools to get the old HTML and XML tooling back (and maybe uninstall Wild Web Developer features along the way)

Since we will stick to including the Wild Web Developer tools in the foreseeable future, I will close this issue here, but please feel free to continue to command and ask. Happy to provide further help here, of course.
