### ISSUE TITLE
Spring Tool Suite 4 for eclipse install codeMix, can not open vue file

### ISSUE THREAD

**Issue by moyuan0522** [spring-projects/sts4#1104]
**Describe the bug**
Spring Tool Suite 4 for eclipse(Version: 4.19.0.RELEASE),after install codeMix, can not open vue file, throw the exception "class org.eclipse.ui.part.FileEditorInput cannot be cast to class com.genuitec.eclipse.code.ui.welcome.editors.CodeMixWelcomeEditorInput (org.eclipse.ui.part.FileEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1c811c9; com.genuitec.eclipse.code.ui.welcome.editors.CodeMixWelcomeEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2abb32b)"

**To Reproduce**
1.open Spring Tool Suite 4 -> help -> eclipse marketplace->find "vue.js::CodeMix 3 CI 2020.7.22"->install
2.restart Spring Tool Suite 4->window->preferences->general->editors->file associations
file types -> add "*.vue"->associated editors->add CodeMix Welcome
3.project explorer->open a  vue file -> throw the exception "class org.eclipse.ui.part.FileEditorInput cannot be cast to class com.genuitec.eclipse.code.ui.welcome.editors.CodeMixWelcomeEditorInput (org.eclipse.ui.part.FileEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1c811c9; com.genuitec.eclipse.code.ui.welcome.editors.CodeMixWelcomeEditorInput is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2abb32b)"

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by martinlippert** [comment]
I tried installing the mentioned Codemix extension into a plain Spring Tools for Eclipse 4.19.0.RELEASE installation as well as into a plain Eclipse 2023-06 JEE package installation, and both failed due to some javax.servlet bundle dependencies missing during the installation. This - and the build date of the extension - sounds very much like the version of Codemix that is on the marketplace is not (yet) compatible with the latest Eclipse versions.

The error in your description also points towards an incompatibility between the Codemix version and the underlying Eclipse version. I would recommend to report this to the Codemix project.
