### ISSUE TITLE
Unable to get Intellisense and formatting for JSP files

### ISSUE THREAD

**Issue by Debakripa** [spring-projects/sts4#1171]
**Expected Behavior**

It should work on Intranet PC, and JSP files should have alll edit features, like Intellisense, hughlighting, special edition support for JSP pages. 

**Current Behavior**
Currently it behaves like  a common notepad on saving a file as JSP, not like an IDE. 

**Context**

As PC is forever Intranet-connected and not Internet, can't install plugins or anything. Raised this issue on Twitter, was told to download directory for the 3.32.0 release (which corresponds to the Eclipse 2023-12 release): https://download.eclipse.org/webtools/downloads/drops/R3.32.0/R-3.32.0-20231114230950/ However l can't locate the exact resource required. 

I intend to get it downloaded from an Internet-connected PC and transfer it to the Intranet PC where l need to work with STS. 

Can someone please help with this? I use STS version 4.20.0, and the version can never be upgraded as PC is Intranet-connected

**Comment by martinlippert** [comment]
It turns out this is going to be difficult if your machine is not connected to the wider internet and can't access the necessary software update sites. I double checked the offline installation of the tools you are asking for from the ZIP archive of the WTP project, but that alone also doesn't work. You would need to have access to the main Eclipse update repository as well, so unfortunately this isn't really working as expected for you.

I also tried it another way, which also doesn't work out of the box, so the best option here is probably do grab a fresh installation of the Spring Tools 4 for Eclipse on an internet-connected machine, run the installation vial the Eclipse Marketplace entry or the main Eclipse update site, and then transfer the fully installed IDE over to your intranet-connected machine.
