### ISSUE TITLE
Filter types ineligible for access in code completion for Spring Modulith projects

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects/sts4#1173]
STS currently verifies type references of Spring Modulith projects for whether they are valid ones regarding the Spring Modulith module model. It would be nice if the code completion for types would consider those validity rules, too. Currently, you can, for example, declare a field of a forbidden type and get that type code completed but then immediately marked invalid afterward.

**Comment by martinlippert** [comment]
Hey @odrotbohm, thanks for raising this. Sounds indeed completely reasonable (one could argue about not showing the proposal at all or continue to show it but marked somehow), but unfortunately this is difficult to implement at the moment due to the fact that the regular Java proposals are coming from the Java language tooling (in VSCode from the Java language server, in Eclipse from JDT) whereas the Spring Modulith validation (and information) is part of the Spring language tooling, sitting in its own language server.

In this architecture, the client (the editor, the IDE) asks all language servers for proposals and merges them, so each language server does not have any influence on the proposals generated from other language servers (or other language extensions), so there is no way for the spring language server to remove certain proposals that are coming from the java language server.

There is probably a way to make this work somehow by extending the java language server itself and injecting logic into it to filter out certain proposals (I think something like this has been done before in Eclipse itself), but I would like to keep us out of these custom and client-specific extensions as much as possible.

Probably worth to discuss this with the VSCode team to get their opinion on this "filter out proposals from another extension/server" question though.

**Comment by martinlippert** [comment]
I double checked this. The way you can modify completion proposals is highly specific to the client side, so we would have to implement this specifically for Eclipse, for VSCode, and potentially for other Java tooling implementations (e.g. the new Oracle Java language support in VSCode).

In addition to that it is somewhat limited what you can do with those proposals. The things that would serve the needs the best seem to be to influence the ranking of proposals and/or to decorate proposals (with some icon or with a strikethrough style, for example). It would not easily be possible to entirely remove those proposals.

In addition to that I don't really think that support for modifying proposals will make it into the language server protocol anytime soon (if at all). It would be the ideal way to implement this, but as said, nothing that is possible right now nor in the near future

Given these options, I don't think going down the path of implementing multiple custom client- and java-tooling-specific extensions is what we should do here - even though I totally see the value of the raised idea.

**Comment by odrotbohm** [comment]
Understood, thanks for the analysis, though! 👍

**Comment by martinlippert** [comment]
So closing this for now. If things change or new insights appear, we can re-open.
