### ISSUE TITLE
Spring for Eclipse - Mac App Naming

### ISSUE THREAD

**Issue by rderewianko** [spring-projects/sts4#118]
Hello All,

Thanks for releasing a new version.. 

Could I ask that in the future a few things stay the same between builds/releases
The file name
It's moved from STS.app -> Spring Tool Suite.app

The Certificate Identifier
 org.springsource.sts.ide -> org.springframework.boot.ide.branding.sts4

But the worst offender is the file name listed on the spring site.
In the last few years we've had a few changes
one from tar.gz.
another dropping some -'s for some .'s

These changes affect automation macadmins have in place to facilitate updating that software on their endpoints through their own internal tools managing macs, be it munki, casper etc.

https://github.com/autopkg/rderewianko-recipes/tree/master/SpringToolSuite

While it's not a show stopper its a bit of an annoyance to update it when there's new releases.

Thank you
- RD

**Comment by martinlippert** [comment]
I understand your suggestion and I can tell you we are not making changes to names and identifiers without good reasons... :-)

Since the release of Spring Tools 4 was not a regular update for the Spring Tool Suite, but instead a major re-write and complete new product, keeping the same names and identifiers for it would have caused quite some confusion and would have been misleading. Therefore it made a lot of sense for us to adjust the names and identifiers.

We will release updates for the STS 3.9.x stream, too, so keeping them separate is important.

And changing the packaging of the macOS version from tar.gz to a dmg file was also an important step to avoid app translation issues in macOS (btw).

Nevertheless, looking ahead, I think the names and identifies will stay the same for the foreseeable future for both, STS 3.9.x releases as well as Spring Tools 4 releases.
