### ISSUE TITLE
Every time I run VSCode, an error message appears: [the trustAnchors parameter must be non-empty].

### ISSUE THREAD

**Issue by jackcomtw** [spring-projects/sts4#1195]
**Describe the bug**
Every time I run VSCode, an error message appears: 
[Failed to fetch Generation from Spring IO: I/O error on GET request for "https://api.spring.io/projects": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty].
from Spring Boot Tools

System Info
```
Version : 1.86.2
認可: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date : 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```

Extensions
```
.vscjava.vscode-lombok-1.0.1
chrmarti.network-proxy-test-0.0.11
dhruv.maven-dependency-explorer-1.0.17
donjayamanne.githistory-0.6.20
github.copilot-1.164.0
github.copilot-chat-0.12.2
ms-ceintl.vscode-language-pack-zh-hant-1.85.2024021409
redhat.fabric8-analytics-0.9.2
redhat.java-1.28.1-win32-x64
redhat.vscode-xml-0.26.1-win32-x64
vmware.vscode-boot-dev-pack-0.2.1
vmware.vscode-spring-boot-1.52.0
vscjava.vscode-java-debug-0.56.1
vscjava.vscode-java-dependency-0.23.4
vscjava.vscode-java-pack-0.25.15
vscjava.vscode-java-test-0.40.1
vscjava.vscode-spring-boot-dashboard-0.13.1
vscjava.vscode-spring-initializr-0.11.2
```
Settings.json
``` 
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "git.autofetch": true,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.renderControlCharacters": true,
    "timeline.excludeSources": [],
    "redhat.telemetry.enabled": true,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "http.proxy": "http://......",
    "https.proxy": "http://......",
    "http.proxyStrictSSL": false,
    "http.proxyAuthorization": null,
    "maven.settingsFile": "C:/Users/...../.m2/settings.xml",
    "java.configuration.maven.globalSettings": "C:/Users/...../.m2/settings.xml",
    "maven.terminal.useJavaHome": true,
    "java.configuration.runtimes": [
        {"name": "JavaSE-11", "path": "C:/tools/openjdk-11+28_windows-x64_bin", "default": true},
        {"name": "JavaSE-21", "path": "C:/tools/openjdk-21.0.1_windows-x64_bin"}
    ],
    "editor.minimap.enabled": false,
    "editor.codeActionsOnSave": {
        "source.organizeImports": "always"
    },
    "javascript.validate.enable": false,
    "github.copilot.chat.welcomeMessage": "always",
    "github.copilot.advanced": {
        
    },
    "github.copilot.chat.localeOverride": "zh-TW",
    "spring-boot.ls.java.home": "C:/tools/openjdk-21.0.1_windows-x64_bin",
    "spring-boot.ls.java.vmargs": [
        "-Djavax.net.ssl.trustStore=c:/tools/openjdk-21.0.1_windows-x64_bin/lib/security/cacerts"
    ],
    "diffEditor.ignoreTrimWhitespace": false,
    "java.compile.nullAnalysis.mode": "automatic",
    "settingsSync.ignoredSettings": [],
    "editor.multiCursorModifier": "ctrlCmd",
}
```

**Comment by BoykoAlex** [comment]
Never seen this error yet... Looks like it has to do more with the JVM running the the Boot Language Server rather than with the Boot tooling. What's the JVM running the Boot LS? If you launch `jconsole`, connect to a java process with label `org.springframework.ide.vscode.boot.app.BootLanguageServerBootApp`, switch to **VM Summary** tab then in the table you should find the VM details, vendor version, somewhere below you should find the VM path...
I'd suggest try a different JVM for the Boot Language Server... Go to settings Extensions -> Spring Boot Tools -> Language Server, enter java home setting: the path to JVM to use to launch Boot LS. Hopefully better luck with a different JVM...

**Comment by Elyasin** [comment]
I got a similar error recently. The error suggests that the SSL handshake fails, which may be a problem with the usage of certificates.

Java has its own certiciate store, which you can manage with the keytool.

I work in an environment where the customer has restrictions on their systems such that we have to deal with certificates.

I had installed and set up a JDK and imported the necessary certificates. That works fine.

The Spring Boot Tools did not use the JDK that I set up. Instead it used the JRE that comes with the Red Hat Languages Server; this one does not have the certificates and fails for some connections.

My solution was, as BoykoAlex suggested, to use the `"spring-boot.ls.java.home"` setting to tell the Spring Boot Tools extension to use the JDK I had set up.

Alternatively, I could have imported the certificates into the JRE of the language server. But I did not want that because it is not a JRE under my control really, and I would have to maintain two Java keystores.

**Comment by martinlippert** [comment]
Thanks @Elyasin for the detailed analysis and description here, much appreciated.
@jackcomtw Does that help and allows you to fix the issue on your side as well?

**Comment by jackcomtw** [comment]
> 
> Alternatively, I could have imported the certificates into the JRE of the language server. But I did not want that because it is not a JRE under my control really, and I would have to maintain two Java keystores.

In my problem description related to 'Settings.json', there are two parameters: **spring-boot.ls.java.home** and **spring-boot.ls.java.vmargs**. Both of them explicitly point to my JVM, so I have configured them correctly. However, I am still encountering the error message **[the trustAnchors parameter must be non-empty]** .

Additionally, your response contains a string of messages that I don’t understand. Could you please explain what a language server is? 🤔

How to correctly set the language server in VSCode

**Comment by jackcomtw** [comment]
> Never seen this error yet... Looks like it has to do more with the JVM running the the Boot Language Server rather than with the ...

I apologize, but I am not familiar with what jconsole is. However, in the vscode-spring-boot-debuglog for VSCode, the following message appears, indicating that openjdk-21 has been correctly loaded. Additionally, here are the commands I used to demonstrate that I have indeed imported the certificate into openjdk-21.

[img1](https://meee.com.tw/BuVrYzj)

```
keytool -delete -keystore "c:\tools\openjdk-21.0.1_windows-x64_bin\lib\security\cacerts" -alias repo_spring -storepass changeit
keytool -trustcacerts keystore "c:\tools\openjdk-21.0.1_windows-x64_bin\lib\security\cacerts" -storepass changeit -importcert  -file "C:\tools\_.spring.io.crt" -alias repo_spring
```
[img2](https://meee.com.tw/KVmn7Yq)

**Comment by jackcomtw** [comment]
> Thanks @Elyasin for the detailed analysis and description here, much appreciated. @jackcomtw Does that help and allows you to fix the issue on your side as well?

I apologize for the late response, but unfortunately, this issue has not been resolved yet. 🙇‍♂️

**Comment by martinlippert** [comment]
> > Thanks @Elyasin for the detailed analysis and description here, much appreciated. @jackcomtw Does that help and allows you to fix the issue on your side as well?
> 
> I apologize for the late response, but unfortunately, this issue has not been resolved yet. 🙇‍♂️

No worries about the late response, but I am quite puzzled by this. The steps you described sound all correct, the settings in your settings.json file look good as well. You probably don't need the jvmargs pointing to the keystone, since the JDK should lookup that location automatically, but that is more cosmetics here than an attempt at solving the underlying issue.

`jconsole` comes with the JDK, you in case you have your JDK on the path, you can execute `jconsole`, which brings up a simple application that lets you connect to a running JVM and see what is going on inside (in a very simple way). You could do this to see if the process behind the scenes that seems to throw this problem is indeed using the right JVM. You could run `jconsole`, then select the process that is called `org.springframework.ide.....BootLanguageServerBootApp`, press `connect`, use the insecure connection, etc. But given the output that you pasted here, it looks like the Spring Boot tooling is using the JDK that you configured.

Maybe it is worth to create a simple Spring Boot application that accesses the URL in question here (as a small reproducer) and run that using your JDK - at least to see where the problem could be. WDYT?

**Comment by martinlippert** [comment]
@jackcomtw Glad to hear that you found the solution to this and shared this with the broader community here. Much appreciated.
