### ISSUE TITLE
sun.security.ssl.SSLContextImpl$DefaultSSLContext

### ISSUE THREAD

**Issue by Nikthakur09** [spring-projects/sts4#1203]
![Screenshot 2024-03-11 211149](https://github.com/spring-projects/sts4/assets/114174800/f4dde8e6-f15f-40a5-8442-4edbee2131f4)
**Describe the bug**
Not able to create a spring starter project cause this window always pops up and I have installed many time but not able to resolve this one

**Comment by martinlippert** [comment]
Can you take a look at the `Error Log` view to see if there is something related with a more comprehensible stack trace and if so, paste those details here?

**Comment by Nikthakur09** [comment]
I have resolved the issue by myself.

**Comment by Nikthakur09** [comment]
So If you are using sts version 4.22.0 You have to extract contents folder to the location C:\Windows\System32 then it will work fine

**Comment by martinlippert** [comment]
The `system32` folder on Windows is meant for operating system files and I definitely don't recommend to move the Spring Tools for Eclipse distribution into that folder.

I wonder why this solves the issue for you...

**Comment by martinlippert** [comment]
Without further details, it is hard to recommend a specific solution here. My best guess here is that this is related to https://github.com/spring-projects/sts4/issues/1195 - while that issue is more specific to the VSCode environment, the underlying issue might be the same. So you might want to take a look at those comments to see if having the right certs on the JDK that is used to run the IDE.

In addition to that it would be interesting to see if the `Error Log` view in your IDE reveals any details. Did you look into that already? And if you find anything related, please paste the stack trace here.
