### ISSUE TITLE
New projects are missing spring nature

### ISSUE THREAD

**Issue by yossikolel** [spring-projects/sts4#122]
New projects are missing spring nature, missing all Spring Tools features.

**Comment by martinlippert** [comment]
The Spring Tools 4 do not have the Spring nature anymore, but all the features of the all-new Spring Tools 4 should be available for Spring Boot projects nevertheless. What exactly are you missing?

**Comment by yossikolel** [comment]
Thanks for the quick answer.

I see I can edit starters, but I missing the "Show RequestMappings".

**Comment by martinlippert** [comment]
You should have a look at all the features of the new tools in the user guide here: https://github.com/spring-projects/sts4/wiki/

Since we re-implemented and re-designed a lot of the functionality, things are new and different. Spring Tools 4 is not just a minor update of STS3, it is a complete new set of tools.

You can learn more about the differences here:
https://github.com/spring-projects/sts4/wiki/STS3-Features

And let us know what else you are missing when using Spring Tools 4, always happy to get feedback from the community.

**Comment by martinlippert** [comment]
For the `Show Request Mappings` action, there is a much better alternative available now, using the super quick symbol navigation. Open a Java editor, type `Cmd+6` and put in `@/` as a search prefix. It will show you all the defined request mappings with lots of details. And you can easily filter them, too.

**Comment by martinlippert** [comment]
Here is a quick feature video showing a demo of that: https://www.youtube.com/watch?v=2-Afy8AeC6A&index=2&list=PL7B74449D5224CC99

It is using VSCode, but the same is available in Eclipse, too.
