### ISSUE TITLE
Variable assignment/reference syntax highlighting lost between v1.53.0 and v1.54.0

### ISSUE THREAD

**Issue by dbmckie** [spring-projects/sts4#1249]
I use the Spring Boot Tools Extension for VS Code.  Between versions 1.53.0 and 1.54.0 local variable lose syntax highlighting when they are referenced.

Highlighting is fine when variable is initially defined but when later referenced or assigned, highlighting is lost.  All things the same, v1.53.0 works fine.

This is on a clean install of VS Code with only the Java Extension Pack and Spring Boot Extension Pack installed.

![image](https://github.com/spring-projects/sts4/assets/51343001/3eba2082-d36c-46c1-8a8f-aed5c50c8ebf)
V1.53.0

![image](https://github.com/spring-projects/sts4/assets/51343001/4fb719d2-2727-491f-a9b7-b09b31a711f8)
V1.54.0

**Comment by martinlippert** [comment]
The only thing that comes to my mind is the new semantic token support that we have in place. I wonder why and how that could cause this, but we need to investigate this. Thanks a lot for reporting this.

**Comment by BoykoAlex** [comment]
Looks like there is some kind of conflict between java semantic highlighting and ours for embedded HQL/JPQL. Needs to be investigated. One thing i could fix quickly is if one disables the JPQL support then java semantic token highlight works the same as before. However, seems that for both working well together language client in vscode might need to be involved

**Comment by BoykoAlex** [comment]
I pushed something that allows the setting "JPA Query Support" (`boot-java.jpql`) to properly disable JPQL/HQL syntax highlighting: 8f691f357548334d26f8c6dd882e1c3a8d24c9a5
If you grab a snapshot build of the extension from the bottom of this page: https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html it should highlight Java code properly (accounting for JDT LS semantic tokens highlighting) if JPQL support is off in the settings.

I noticed that VSCode semantic tokens support would honour the first semantic token provider that provides non-null tokens and ignore the tokens coming from the rest of them. This isn't promising at all :-\ Seems like this is a design decision... I may try tokens for a range rather than for a whole doc as it may work differently.

**Comment by BoykoAlex** [comment]
We've pushed a fix for the issue which is kind of a workaround until VSCode properly supports multiple semantic tokens providers for the same language: 6243feefffbd4e5ee375e5f8a33a1f1d55525ec7
We'll track the VSCode side of things via #1251 separately
