### ISSUE TITLE
Debug stack reference lost/reset when another thread is executed in versions 4.22.0 and 4.22.1

### ISSUE THREAD

**Issue by duduabreu** [spring-projects/sts4#1250]
**Describe the bug**
In versions 4.22.0 and 4.22.1 of sts4 eclipse distribution for linux, while debugging the code, if I'm paused at a breakpoint and another thread is executed, displaying a message in the console tab, the debug stack reference is lost/reset.

As a result, the step into, step over, and step return buttons become disabled, and I lose the values of my variables in the variables tab.

To return to normal, I need to expand the System Thread again and click on the first item in the stack. However, every time another thread is executed, I lose this reference again.

**To Reproduce**
1 - Run the program in debug mode.
2 - Set a breakpoint in the program.
3- While paused at the breakpoint, have another thread display a message in the console tab.

I tried to take a screenshot of the first moment and the second moment. I hope it helps, and I apologize for deleting a lot of information from the images, but it's for confidentiality reasons.

First Moment (The debug reference has not been lost yet.)
![first](https://github.com/spring-projects/sts4/assets/13894242/0aff0fdd-9e76-4f87-8ed6-e5ecede64b68)

Second Moment (The debug reference has already been lost.)
![second](https://github.com/spring-projects/sts4/assets/13894242/db0f5f50-96b6-4a19-a420-a22a474991a5)

**Comment by BoykoAlex** [comment]
@duduabreu I think the problem is with Eclipse Debug UI rather than STS's plugins... Looks like the problem has been introduced in Eclipse 4.31. Try STS distribution on Eclipse 4.32 snapshot via our snapshot build site: https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html
If the issue is still there I'd report it to Eclipse via https://bugs.eclipse.org/bugs/

**Comment by duduabreu** [comment]
I downloaded [spring-tool-suite-4-4.23.0.202405141928-SNAPSHOT-e4.32.0-linux.gtk.x86_64.tar.gz](https://cdn.spring.io/spring-tools/snapshot/STS4/nightly/dist/e4.32/spring-tool-suite-4-4.23.0.202405141928-SNAPSHOT-e4.32.0-linux.gtk.x86_64.tar.gz), but the problem persisted. I will report it on the suggested site. Thank you in advance.

**Comment by mauricio-rodrigues-vega** [comment]
I also have this problem, has anyone managed to solve it?

**Comment by martinlippert** [comment]
@duduabreu Did you report it to Eclipse? If so, do you have a URL to the report?

Aside from that, the issue should probably be reported to https://github.com/eclipse-jdt/eclipse.jdt.debug, if that hasn't happened yet. Before doing that, it would be good to verify that the issue is still around via trying the latest Eclipse SDK builds from https://download.eclipse.org/eclipse/downloads/

The latest Eclipse milestone or RC builds would be a good candidate - or even the latest integration builds to double check even the absolutely latest code.

**Comment by duduabreu** [comment]
@martinlippert i didn't.

I tried on version 4.23 of STS and the bug still remaining.

**Comment by martinlippert** [comment]
> @martinlippert i didn't.
> 
> I tried on version 4.23 of STS and the bug still remaining.

Please try with the latest Eclipse 2024-09 builds and report the issue against https://github.com/eclipse-jdt/eclipse.jdt.debug.

**Comment by martinlippert** [comment]
And would be awesome if you could paste a link to the reported issue once you filed it, so that we can keep track of it here.

**Comment by christian-elsen** [comment]
This one here more or less describes this case: https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/345

**Comment by martinlippert** [comment]
> This one here more or less describes this case: [eclipse-jdt/eclipse.jdt.debug#345](https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/345)

Thanks @christian-elsen for the reference to the JDT debug issue.
