### ISSUE TITLE
spring tool suite 3 -JDK21

### ISSUE THREAD

**Issue by mandala5741** [spring-projects/sts4#1252]
I hope to compile a version of Spring Tool suite 3 that supports JDK21，Thank you very much, loyal fan. I only like Spring Tool suite 3

**Comment by martinlippert** [comment]
Spring Tool Suite 3 is no longer supported and no longer maintained, so we will not push out an update for that which supports JDK 21.

You could try to assemble those pieces yourself, but I am sure that this will be somewhat difficult and cumbersome. JDK 21 support landed in Eclipse in the 2023-12 release (4.30), whereas the maintenance for the Spring IDE components ended with Eclipse 4.21. A lot of things changed in Eclipse since then.

I would strongly recommend to upgrade your dev environment to the latest Spring Tools 4 distributions for Eclipse to continue to stay on the latest versions. It gives you all the JDK 21. If you are missing anything specific from the Spring Tools 4 that you had in Spring Tool Suite 3 (there must be a reason why you only like Spring Tool Suite 3), then please tell us what you are missing. Since we introduced Spring Tools 4, we love to hear that kind of feedback to improve Spring Tools 4.

**Comment by martinlippert** [comment]
Closing this issue. If there is anything you are missing from the latest Spring Tools 4 releases, please let us know.
