### ISSUE TITLE
weird vscode JPQL/HQL syntax error for @Query text block in Spring Boot

### ISSUE THREAD

**Issue by jackytank** [spring-projects/sts4#1279]
**Describe the bug**
I had installed Spring Boot Extension Pack in VSCode and I detect weird JPQL/HQL syntax error present in my repository

![image](https://github.com/spring-projects/sts4/assets/52403567/883c2cb5-fe08-4a60-9d54-6ddf0956aa20)

although the code work fine without any runtime error, but VSCode still showing that weird syntax error makes me want to become a dictator and destroy the world

**To Reproduce**

**Sample**

![image](https://github.com/spring-projects/sts4/assets/52403567/883c2cb5-fe08-4a60-9d54-6ddf0956aa20)

**Comment by martinlippert** [comment]
In order to avoid you "become a dictator and destroy the world", you can switch off those validations in the `Preferences -> Settings -> Extensions -> Spring Boot Tools -> Data Query` as a quick workaround to get rid of those errors.

In the meantime, we will work on improving this for the next release.

**Comment by jackytank** [comment]
thanks for your time sir, you had prevented possible WW3
