### ISSUE TITLE
[performance] annotation processing needs overhaul

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1288]
The `AnnotationHierarchies` helper class is widely used during indexing, symbol generation, and validation to check for annotation hierarchies and whether a specific annotation found in the source code relates to a specific annotation that is know to the indexing or validation.

The implementation in this space is quite complex and contains a lot of duplication, so this needs a lot of cleanup work. In addition to that results of the AST analysis are not cached, which results in the same checks being performed over and over again with every validation, every indexing, every source files, etc.

`AnnotationHierarchies` is currently a set of static helper methods. We need to turn this into a project-specific helper that caches results and wipes out the cache as soon as files change. Even though most of the cached data might not be affected by changed code or a changed classpath of the project, the cache might not be able to decide that very precisely. Therefore, wiping the cache with every classpath change and every source file change will be the safest strategy here.

**Comment by BoykoAlex** [comment]
The plan is:
1. Cleanup and trim down number of methods in `AnnotationHierarchies` to the absolutely required bare minimum
2. Transform `AnnotationHierarchies` into a class with instance methods rather than static. Pass it around via CU property. Create in CU cache and spring indexer.
3. Introduce `CachingAnnotationHierarchies` subclass of `AnnotationHierarchies`. This class will attempt to cache most of the results produced by the non-caching base class. Likely caching will be for binary types rather than source types which may change often.

Draft PR for 1. is #1421
