### ISSUE TITLE
Plugin matches any file named *Tasks*.yml

### ISSUE THREAD

**Issue by chrisrpatterson** [spring-projects/sts4#13]
The Concourse CI Pipeline Editor plugin seems to try and take over validation of any file that happens to be named in the format of *Tasks*.yml.  For example I had a file named NetCore-Tasks.yml and red squiggly lines were displayed in the editor.  The documentation for the plugin states it should only match */tasks/*.yml which seems reasonable given the concourse pipeline structure.

**Comment by kdvolder** [comment]
Looks like the readme and the actual patterns configured in package.json do not match.

See: https://github.com/spring-projects/sts4/blob/master/vscode-extensions/vscode-concourse/package.json#L54

```
        "filenamePatterns": [
          "*task*.yml",
          "**/tasks/*.yml"
        ],
```

Published version on marketplace is slightly different:

```
				"filenamePatterns": [
					"*task*.yml",
					"**/tasks/*.yml"
				],
```

I guess we can fix this issue by updating the readme, or by updating the default patterns themselves.

Unfortunately there seem to be a number of different ways folks name and organize their task files so likely any default set of patterns we come up with will be wrong for some folks out there.

Luckily vscode allows you to easily override these patterns in your own user or workspace settings. (There's some explanation about this in the readme too).

Also I think the patterns currently in master are slightly more selective than the ones in 0.0.8 and, I don't think they would have caused you grief as your file ending in 'Tasks.yml' no longer matches the pattern (only file ending in "task.yml" would match now.

So I think I'll opt with updating the readme to align with the patterns in master. Feel free to disagree and try and convince me otherwise.

**Comment by chrisrpatterson** [comment]
If you go with the even more selective *task.yml I think that will be ok.

**Comment by kdvolder** [comment]
So yeah, I made the pattern a bit more selective "*task.yml" and updated the readme. Thanks for the feedback :-)
