### ISSUE TITLE
Missing views in STS 4 

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/sts4#132]
In Window > Show View > Other ... there is just one entry from STS and the Spring Tools. Is this intended?

![image](https://user-images.githubusercontent.com/5071169/47775208-579cfa00-dcef-11e8-96e2-446d28e2bf4b.png)

I am using OpenJDK-11.

**Comment by kdvolder** [comment]
Yes. A lot of old STS 3 functionality was removed. You can still get it back for the time being but it has to be installed explitly, its no longer bundled. Eventually the old functionality will be no longer maintained.

If there's some specific functionality that you are missing you should let us know. We are counting on this feedback to determine how to prioritize work on new STS 4 features and/or porting over some of the old features. But please be specific, what are you missing exactly? And it also helps to give a little bit of details of how/why you use a specific view or feature (we don't intend to just blindly copy over the old views, so knowing a bit about how you used it in the past could help in filling your use-cases in a different way).

BTW: There's a FAQ that explains a bit about why features were not included in STS 4, what is meant to replace them, how to get the old features installed back in the short run, and our plans going forward. You can find it here: 

https://github.com/spring-projects/sts4/wiki/FAQ

Closing this ticket now because I think your question 'Is this intended' has been answered. But do raise more tickets to describe if/what you are missing in STS 4.

**Comment by ullenboom** [comment]
Thanks for the clarification. Also https://github.com/spring-projects/sts4/wiki/STS3-Features has useful information about alternatives.
