### ISSUE TITLE
SPEL: no viable alternative at input '#{' [JAVA_SPEL_EXPRESSION_SYNTAX]

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/sts4#1353]
Started seeing the below error alert for the annotation mentioned since **v4.24.0**, application builds and works perfectly fine otherwise.

`SPEL: no viable alternative at input '#{' [JAVA_SPEL_EXPRESSION_SYNTAX]`

`@ConditionalOnExpression("#{${some.property.delay-seconds:0} > 0}")`

**Comment by BoykoAlex** [comment]
You can disable SPEL validations via settings:
![Screenshot 2024-09-13 at 00 04 11](https://github.com/user-attachments/assets/a0f09731-f672-45ae-b29d-1efeb00cf6a2)

You are seeing an error because we added syntax validation for SPEL expressions. This error doesn't affect the compilation so this error is just for information purposes. STS shows error because it expects the SPEL expression not to have `#{` prefix and `}` suffix. It expects SPEL without prefix and suffix: `@ConditionalOnExpression("${some.property.delay-seconds:0} > 0")`

**Comment by martinlippert** [comment]
Probably something we need to support as well for the validation

**Comment by BoykoAlex** [comment]
The question is whether SPEL wrapped in `#{}` in `@ConditionalOnExpression` is a valid syntax. I'm not sure it is...

**Comment by syedyusufh** [comment]
@BoykoAlex I can confirm it is a valid expression as application with the mentioned `SPEL` works dynamically as expected

**Comment by BoykoAlex** [comment]
I think the reason for this might be the ability to nest SPEL expressions inside SPEL expressions

**Comment by BoykoAlex** [comment]
Looks like Spring allows it either wrapped in `#{}` or without and then it just automatically wraps it in `#{}` at runtime.

Fixed with 80de7872247a7455717df18ef4bae9cd638d0bc7
