### ISSUE TITLE
Spring legacy project type is missing in STS4 default installation 

### ISSUE THREAD

**Issue by muhammadallee** [spring-projects/sts4#151]
Unzipping the freshly downloaded Windows distribution, is missing Spring Legacy project options while creating a new project (shown below). Are these being removed from STS4? I couldn't find information around it.

Spring Tool Suite 4 
Version: 4.0.1.RELEASE
Build Id: 201810300749 
Win 10 x64
<img width="429" alt="newprojectwindow" src="https://user-images.githubusercontent.com/13325618/49036528-5fa66780-f1d1-11e8-9730-d6f4841441fd.png">

**Comment by kdvolder** [comment]
Yes, eventually they will be discontinued. For the time being you can still install the legacy tooling manually. Read more about the plans here: https://github.com/spring-projects/sts4/wiki/FAQ

Let us know if you have more questions, or specific concerns around discontinued functionality. 

We can't promise that we will keep all the legacy tooling around forever, but we are interested to learn if/what features people will be missing the most. This will help us moving forwards in deciding the kinds of things to implement or port for STS 4.

I'm closing this ticket now, as I think the question has been answered. But feel free to add more comments/questions here, or create a new ticket.

**Comment by martinlippert** [comment]
As an additional comment I would like to add that you can install the STS3 pieces that contain the support for the old-style non-Spring-Boot legacy projects as an extension pack into Spring Tools4 (via the Eclipse marketplace).

**Comment by muhammadallee** [comment]
I did try installing STS3 for non-Spring-Boot legacy projects, however, the generated projects use older versions of Spring and their related compatible frameworks which does not completely deliver the advantage of having a project wizard.

**Comment by kdvolder** [comment]
>  the generated projects use older versions of Spring and their related compatible frameworks

That is true. This is because the legacy wizard is an old wizard and it is no longer being maintained. We mererely provide it to support people who are not yet ready to adopt newer version of Spring and Spring Boot.

If you want to use modern spring it probably also makes sense to switch to using Spring Boot, and then you can use the Spring boot wizard in STS 4 instead.

**Comment by martinlippert** [comment]
@muhammadallee So what exactly are you trying to create? A regular Maven project that is using Spring core framework in the recent version, but not Spring Boot?

**Comment by muhammadallee** [comment]
@martinlippert Yes, a regular Maven project that uses Spring framework (core, web, security, data etc) targeting traditional deployment. It would really be great of have such tooling available for Spring framework as well.

**Comment by kdvolder** [comment]
Not a wizard, but it isn't too hard to convert a spring boot project to be packaged into a war file. It just isn't what most people do nowadays. But in fact spring-boot does still support war packaging. See here on a quick "how to": https://spring.io/guides/gs/convert-jar-to-war/

**Comment by LightCC** [comment]
Let me add another perspective - I'm just learning Spring (and Java, for that matter), and working my way through Pluralsight courses for Spring, and just figured I should work through some plan Spring courses before tackling Spring boot, after watching an "overview" video.  Now, these might be outdated these days, but when I looked at the STS3 and STS4 plug-ins in the Eclipse marketplace, there is nothing at all saying that STS4 is just supporting Spring Boot.  "Spring Tools 4 is the next generation of Spring tooling..." not even a mention of Spring Boot.

So I installed STS4 because, well, newer is always better, right?  But then there was a lot of missing things.

All that to say that I'm not saying STS4 should necessarily support the legacy items, but perhaps the plug-in description and the install/getting started pages should have a brief section or note describing what you have said in this thread?  I spent a few hours cruising the web trying to figure out why File/New didn't have any Spring options, except for 2 Spring Boot items... And only found this thread when I came here to file an issue report.  :)

**Comment by kdvolder** [comment]
@LightCC 

> I'm just learning Spring (and Java, for that matter)

This may seem unintuitive, but you probably will have a much better / fun / easy time if you started with Spring Boot rather than 'plain' Spring. You are right, you will still have to learn the concepts of 'plain' Spring (beans, dependency injection etc), because Spring Boot is still Spring. The only real differences:

- it comes with some machinery to autoconfigure a lot of things. So getting started with a simple spring app that actually runs is a lot easier and requires very little if any 'boilerplate' configuration. This makes life a lot easier if you are learning spring. I think its when you are learning that this actually helps the most. Once you are getting deeper into the thick of things, you'll probably configure more and more things exactly the way you want (overriding the autoconfig) and so you will loose some of those benefits. But especialy when you are learning, autoconfiguration 'magic' is actually very helpful to ease you into building your first spring apps.

- it provides 'jar' packaging with an embedded servlet container. This is a fancy way of saying that it contains its own 'server' (which is autoconfigured for you). So your java app is just a 'self-contained' jar and is very easy to run. I'ts just a regular java app with a main method. So you don't have to worry about installing a server like tomcat or jetty and deploy your apps as wars. Beleave me, the server deployment adds a lot of (arguably unessary) complexity to your development process.

Anyhoo, I just wanted to mention that. Your points are still taken though and we'll add your voice as a vote for more / better support for non spring boot apps. And we'll make sure the marketplace entries are more clear about the current limitations. 

Thanks for the feedback and merry x-mas :-)

**Comment by martinlippert** [comment]
@LightCC I updated the marketplace entry to make it more obvious that the Spring Tools 4 are focused on Spring Boot projects at the moment.

**Comment by panguohua** [comment]
thanks
