### ISSUE TITLE
What is the right way to deploy maven web app to tomcat 8.5?

### ISSUE THREAD

**Issue by user20161119** [spring-projects/sts4#154]
Maven web app did not show when want deploy the project to tomcat 8.5 server

![image](https://user-images.githubusercontent.com/123967/49325006-4a389100-f575-11e8-9255-0a9ee1c276b5.png)

**Comment by user20161119** [comment]
Why the STS provide tomcat config option for users?

**Comment by BoykoAlex** [comment]
If you really want to run Spring Boot app on non embedded Tomcat you'd have to switch its packaging to WAR instead of JAR. You can follow this: https://spring.io/guides/gs/convert-jar-to-war/ perhaps.

**Comment by user20161119** [comment]
It's base on spring mvc legacy project,not boot-based project.so i need tomcat to run app

**Comment by martinlippert** [comment]
Hey @user20161119, please note that the Spring Tools 4 do not provide any specific tooling yet for legacy Spring projects that are not based on Spring Boot. We are working on opening up specific parts of the Spring Tools 4 tooling to non-Spring-Boot projects, but that is not yet done and released (and will probably take a little while for us to complete).

If you want to help us with that, feel free to comment on https://github.com/spring-projects/sts4/issues/96 and let us know what specific features you would like to see for non-boot projects and feel free to attach a specific project as an example, if you like.

In addition to that I will re-open this issue, so that we can double check what is missing in your case for deploying your legacy app to Tomcat. That should at least work somehow and could be especially interesting if people also install the STS3 add-on package into their STS4 distribution.

**Comment by user20161119** [comment]
@martinlippert thanks,i have based on spring 4.0 mvc maven project and some new boot based projects to maintain and develop.so i need to deploy project to tomcat within STS.I am using sts 3.x for a long time.really excited about the STS4.X,but i can not use it to maintain my all projects now.

**Comment by martinlippert** [comment]
I worked on this and added the necessary integration bits and pieces to the STS4 product definition, so that the next release will include the necessary m2e extensions to directly run/deploy those apps to a local Tomcat installation.

Additional details how to fix an existing install can be found here:
https://stackoverflow.com/questions/54183982/cannot-drop-project-into-the-development-server

**Comment by user20161119** [comment]
> I worked on this and added the necessary integration bits and pieces to the STS4 product definition, so that the next release will include the necessary m2e extensions to directly run/deploy those apps to a local Tomcat installation.
> 
> Additional details how to fix an existing install can be found here:
> https://stackoverflow.com/questions/54183982/cannot-drop-project-into-the-development-server

thanks,i do not want to try the workaround.i am waiting for the new version release.
