### ISSUE TITLE
【yml editor】Shortcut key comment not following cursor

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#159]
**version**
Spring Tool Suite 4 

Version: 4.0.2.RELEASE
Build Id: 201811300843

**Problem description**

ctrl + shift + c Not following cursor comments.

![image](https://user-images.githubusercontent.com/39790401/49502549-3f049e80-f8b0-11e8-99a1-26c7f56ac7dc.png)

As shown in the figure above, select the cursor`    druid.sql.Statement: DEBUG`This line, press the shortcut key combination, the effect is as follows:

![image](https://user-images.githubusercontent.com/39790401/49502578-50e64180-f8b0-11e8-95b3-d35b069acd94.png)

The annotated content is the first line

**Comment by kdvolder** [comment]
At first I couldn't reproduce it. The key seems to be that problems ensue if the text selection is of length zero. In other words it is just a 'cursor' rather than a selection highlighting a range of characters. Even selecting just a single character makes it work correctly. But if we select change selection, for example, by moving the cursor around the document using the arrow keys, then, the next time we call on 'Toggle Comment' it triggers at the last location where a non-empty text selection was made.

Seems like this is some sort of a quirk caused by the Eclipse 'selection service'. I think it is skipping over 'empty' selections and so to the 'Toggle comment' handler it is as if those cursor movements never happened. I'll have to debug it a bit more to be sure of this explanation, and to find a suitable fix.

In the mean time a simple workaround is to make sure you select at least one character before triggering 'toggle comment'.
