### ISSUE TITLE
Cloud Foundry Manifest buildpack deprecated in vs code extension

### ISSUE THREAD

**Issue by stephaneplante** [spring-projects/sts4#161]
The keyword `buildpack` is deprecated.  

The replacement keyword `buildbacks ` is not recognized in de vscode extension.

Ref : [doc cloudfoundry.org](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#buildpack-deprecated)

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

Note that although this might appear simple, and in fact, making changes to the schema to deprecate `buildpack` and add `buildpacks` is 1-point feature, since we share the cf client with boot dash, we have to also update the underlying CF Java client to support pushing with this new `buildpacks` property.

Consequently, there would be a lot more related work involved, since our current CF client is very far behind the latest one in terms of changes.

I've raised a separate chore for the CF Java client:

https://www.pivotaltracker.com/story/show/162520788

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

Changes pushed to support `buildpacks`, as well as mark `buildpack` as deprecated.

Delivering this for acceptance just on the editor side. Please verify that:

1. `buildpacks` has no reconcile error
2. `buildpacks` is a sequence
3.  Hovering over `buildpacks` shows correct documentation 
4. `buildpack` is marked as deprecated in the editor. Hovering over this property will also indicate that it is deprecated.
5. Dynamic content assist is available in each sequence for `buildpacks`

As for push support for `buildpacks`, since this involves a CF Java client update and is different type of work, it will be tracked separately:

https://www.pivotaltracker.com/story/show/162520788
