### ISSUE TITLE
Dropins

### ISSUE THREAD

**Issue by aldhor** [spring-projects/sts4#165]
Are dropins feature enabled in STS4?

I tried to create the folder dropins in%STS4_INSTALL_FOLDER%\dropins but when starting the IDE it does not recognize them.

**Comment by martinlippert** [comment]
As far as I remember support for the `dropins` folder has been removed from the Eclipse runtime a while ago.

**Comment by aldhor** [comment]
> 
> 
> As far as I remember support for the `dropins` folder has been removed from the Eclipse runtime a while ago.

STS3 has support and Eclipse 4.8.0 (Photon) has support too

**Comment by martinlippert** [comment]
Yes, and the dropins reconciler is also part of the STS4 distribution (including its config), but we don't create the dropins folder by default anymore because Eclipse deprecated the mechanism.

But since the p2 reconciler for dropins is still in the distribution, it should still work, you are right. Not sure why it doesn't. Did you try with the latest Eclipse 2018-12 milestones? Do they come with support for it that still works?

**Comment by aldhor** [comment]
Yeah, I can see that eclipse-jee-2018-09-win32-x86_64 and eclipse-java-2018-12-RC1-win32-x86_64 has dropins folder

**Comment by martinlippert** [comment]
And the dropins folder still work for 2018-12-RC1 ?!?

**Comment by aldhor** [comment]
Sorry for the delay, I was trying different versions.
Effectively, in 2018-12-RC1 has stopped working. In 2018-09 it works correctly.
Hopefully it will be enabled in the following RC.

Thanks for your time!
