### ISSUE TITLE
[navigation] Allow filtering by project in Find Spring Elements list 

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#173]
The default implementation is to show spring elements in workspace or on current file. It would be really usefull if the elements can be filtered on the current project as well. One could easily filter the elements by their path using the current active editor's project name. This can be programmed to another cycle of CTRL+6 like workspace, project and current file.  Or else one could program it to be able filter using a different keyword in the filter field. I personally prefer the option 1 since it make the user experience more straight forward.

**Comment by gayanper** [comment]
This should be a eclipse only feature since other tools doesn't have a notion of multiple projects in a workspace.

**Comment by gayanper** [comment]
@martinlippert here is a PR which adds support for in project symbols for eclipse.

**Comment by gayanper** [comment]
@martinlippert any feedback on this ?

**Comment by kdvolder** [comment]
> This should be a eclipse only feature since other tools doesn't have a notion of multiple projects in a workspace.

That's not true. It isn't as obvious perhaps but vscode also has projects since vscode java support is basically a wrapper on Eclipse JDT (pakcaged as a language server).

**Comment by kdvolder** [comment]
FWIW: I like the idea of being able to filter symbol by current project.

**Comment by gayanper** [comment]
> That's not true. It isn't as obvious perhaps but vscode also has projects since vscode java support is basically a wrapper on Eclipse JDT (pakcaged as a language server).

Hmmm thats good to know. But since the language server api doesn't have support for project notion vscode implementation might look similar to this. May be someone who is really fluent in js development can take it up.

**Comment by gayanper** [comment]
@kdevolder the PR is already there. You can give it a try 😊

**Comment by kdvolder** [comment]
@gayanper I see what you are saying now. Yes language server protocol doesn't have the concept of a 'project'. The closest thing would be a workspaceFolders but its really not the same as the 'projects' that jdt identifies. 

So yeah, it seems hard to implement this functionality in vscode (more so because the UI isn't implemented by us, but is part of the vscode 'generic' language server client).

Anyhoo.... I still support having the project-based filter in our Eclipse 'goto symbol' ui, independent of whether or not we have something similar in vscode (or other clients).
