### ISSUE TITLE
[question, need-help] How to debug the spring boot language server

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#179]
I'm currently working on some improvements for the spring boot language server. I would like to know how i can run the language server from the IDE so that i can debug it while the language server client is making requests to the server.

**Comment by martinlippert** [comment]
Here is what I do:

Being in Eclipse/STS4 and having the language server projects checked out, I can start the spring-boot-language-server from my workspace using a launch config with:

- project: `spring-boot-language-server`
- main class: `org.springframework.ide.vscode.boot.app.BootLanguagServerBootApp`
- vmargs: `-Dlanguageserver.standalone=true -Dstandalone-startup=true -Dsts.lsp.client=eclipse -Dlsp.lazy.completions.disable=true -Dlsp.completions.indentation.enable=true`

This starts up the spring-boot-language-server in something like a reverse mode, it is sitting there and waiting for a connection from the IDE (instead of connecting right away after it started). That way you can run and debug this process in the same way than any other java project.

In the other side, when starting up the IDE (using a runtime workbench), you have to configure that with these VMargs:

`-Dorg.eclipse.swt.internal.carbon.smallFonts -Dboot-java-ls-host=localhost -Dboot-java-ls-port=5007`

(the first one is just a macOS specific setting for Eclipse in general, you can skip that on a other platforms)

That way the IDE tries to connect to the `spring-boot-language-server` using a socket connection at port localhost:5007, which is the port that the above started language server listens on for connections.

Attention: this works only and exactly once. The IDE tries to start the language server (in this case tries to connect to the running one) as soon as it is needed in the IDE (you open a Java file, for example). As soon as it is no longer needed in the IDE (all Java and property files have been closed), the IDE shuts down the language server again. This is what happens from the IDE side, independent of the way you started the language server. In this local dev mode setup the language server process keeps running, but the IDE is not able to re-connect to that process, so it will fail to re-connect to a spring-boot-language-server the second time the IDE would start the language server. Keep that in mind when running in this setting.

Hope this helps!

(lets keep this open until you can successfully run this dev mode for further questions)

**Comment by martinlippert** [comment]
Alex also added details about how to connect to that locally running language server if you run the VSCode extension, another interesting setting.

**Comment by gayanper** [comment]
Thanks All :+1:
