### ISSUE TITLE
How to install latest 4.1.1 version ?

### ISSUE THREAD

**Issue by goxr3plus** [spring-projects/sts4#188]
Eclipse Marketplace has 4.1.0

I added on Eclipse Update sites the below link : 

http://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.10

But it doesn't work ... after 10 minutes i take an error ?

What should we do :( ?

**Comment by martinlippert** [comment]
Once 4.1.1 has been released, it will be available on the Eclipse Marketplace via the regular Spring Tools 4 update site for Eclipse 4.10:

http://download.springsource.com/release/TOOLS/sts4/update/e4.10/

If you want to install a nightly CI build (which is not the release and might contain problems and not-ready features), you can install that CI build from the update site that you mentioned above. But since that update site is being updated quite frequently, it can easily happen that you hit it at a moment where it gets updated.

I would recommend to reload the update site using the "reload" button in the preferences and try again.
