### ISSUE TITLE
STS 4.1.2 breaks Eclipse 4.10 Mylyn

### ISSUE THREAD

**Issue by protobufel2** [spring-projects/sts4#207]
STS 4.1.2 breaks Eclipse 4.10 Mylyn local task creation! 

Either 
1. install full STS 4.1.2 and then add Mylyn via Eclipse Marketplace or the p2, or
2. install Eclipse 4.10 JEE (Mylyn included) and add STS 4.1.2 via Eclipse Marketplace

Observe:
1. New Local Mylyn Task doesn't save any info, e.g. a new task name, etc.

Workaround (also problematic):
1. Install Eclipse 4.10 JEE (Mylyn included) and add STS 4.1.2 via  
https://download.springsource.com/release/TOOLS/sts4/update/e4.10/

Observe:
1. Mylyn Local Task creation is ok
2. Eclipse Check for Updates gives the following error:
```
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/e4.10/compositeContent.xml.
peer not authenticated
```

This is a huge blocker! Please fix! Thank you!

**Comment by martinlippert** [comment]
OK, let's dive into the details here and try to find out what the problem is:

- I installed STS4 into a vanilla Eclipse JEE 2018-12
- Switched to the `Task List` view
- Selected `New Task -> Local`
- The editor for a new task opened

There is Immediately an error showing up in the Error Log view, which is this one:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544794

Nevertheless, I can continue edit and save the task and it shows up in the Task List view. Is that what you are seeing/observing, too?

The bug in LSP4E is already fixed, so you could grab either a new nightly STS4 build for Eclipse 2018-12 from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html or update your installation using 
https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.10 (which would also give you the latest nightly builds of STS 4.2.0).

Regarding the "peer not authenticated" exception, it might be the same as:
https://stackoverflow.com/questions/23754081/peer-not-authenticated-ssl-certificate-error-usng-defaulthttpclient

You could also switch to a http URL instead in the preferences, if you would prefer that.

**Comment by protobufel2** [comment]
My bad, I forgot to mention it’s happening on MacOS Mojave. This could be less severe on other OSes, though.

On my Mac, Oracle and OpenJDK, 8 and 11, the behavior is the same - the blank “New Task” task is created w/o any info.

It’s great that the fix is coming, however, I’d either released the emergency fix, or at the very least put this is a known problem in the Release Log.

All the Best,
David

**Comment by protobufel2** [comment]
Also, I don’t remember the auth problem occurring before with the same setup in previous version; could easily be wrong here...

**Comment by martinlippert** [comment]
> On my Mac, Oracle and OpenJDK, 8 and 11, the behavior is the same - the blank “New Task” task is created w/o any info.

What do you mean exactly? So you hit the `New Task -> Local` action from the `Task View`, then the editor for the new task is opened, but is completely empty? No widgets? No error message? Is there maybe anything related that shows up in the Error Log view?

> It’s great that the fix is coming, however, I’d either released the emergency fix, or at the very least put this is a known problem in the Release Log.

From your description above I am not sure if we are seeing the same issues. Can you maybe attach a screenshot that shows the error?

**Comment by protobufel2** [comment]
In the New Task form, all GUI is fine, name the task to  anything, e.g. “task 1”,  fill the text box, anything else (optional); now try to save it. Observe the New Task appearing in the Tasks List, however, the task name and the rest of your entered info gone; again, UI is fine.

**Comment by martinlippert** [comment]
Ok, you are completely right, I can reproduce that behavior. My bad, tested not enough and not looked at the right things before. The easiest and fastest way to fix this right within your environment is to install a fixed version of the LSP4E component (the one that got the fix). You can do that via `Install New Software` and use this p2 repo URL:

https://download.eclipse.org/lsp4e/snapshots/

Then select the component `Language Server Protocol client for Eclipse IDE (Incubation)` (it should show up as version 0.9.0.something). Select that component and press install. The dialog will tell you that instead of an install it will perform an update since you have that component already installed - which is absolutely correct. Continue, install, and restart. After that, the Mylyn integration should work again just fine.

Hope this helps!

**Comment by martinlippert** [comment]
And many thanks for reporting this. Extremely valuable that you found it, so that we have a solution now to share with other users.

**Comment by protobufel2** [comment]
My pleasure!
And thank you for your hard work!

I think for those who want to stay with the release version, the initially provided workaround should be fine, given the STS url is disabled till the next STS release.

Sincerely,
David
