### ISSUE TITLE
How to change fonts size of Project Explorer

### ISSUE THREAD

**Issue by swdhsn** [spring-projects/sts4#219]
Hello STS-Team,
not sure whether this is the right channel to ask.
Under
Preferences -> General -> Appearance -> Colors and Fonts
there are lots of places where you can change the fonts size. However I couldn't find out how to change the size of what is displayed in views like "Project Explorer" or "Package Explorer".
Is there a way to change this?

**Comment by martinlippert** [comment]
The font size in the explorer views is large controlled by the operating system. If you change the settings over there, the font size should change in Eclipse/STS, too.

On macOS there is a specific flag that gets set in the ini file to set the explorers to a somewhat small font size. If you remove that flag, the fonts are bigger.

**Comment by reya004** [comment]
ESSENTIALLY THIS IS SAYING THAT THERE'S NO SOLUTION FOR THIS.

**Comment by kdvolder** [comment]
@reya004 Maybe this is more helpful? It has more suggestions for different OS.

https://stackoverflow.com/questions/3124629/how-can-i-configure-the-font-size-for-the-tree-item-in-the-package-explorer-in-e

Unfortunately there is not much that we here can do about this situation. This is how Eclipse works. Personally, I agree that its not logical and confuses many people. But the only way to really 'fix' this issue inside of Eclipse. 

So you should raise a Eclipse bug or comment on a existing bug instead of here. 

Actually I found there is a bug ticket for this exact problem (actually, I wouldn't be surprised if there are several tickets, but this is the one that I found):

https://bugs.eclipse.org/bugs/show_bug.cgi?id=540299

So I suggest you go over there and make a comment.

**Comment by Ikhan** [comment]
if anyone still searching for this solutions here it is(mac osx)

<img width="912" alt="Screen Shot 2022-07-12 at 8 52 26 AM" src="https://user-images.githubusercontent.com/475993/178494391-741bb5da-8fe1-4d92-9bb6-694792eaca14.png">

**Comment by torbenmueller** [comment]
Thank you so much Ikhan, this is exactly the solution.
