### ISSUE TITLE
No more Spring Perspective neither Spring Explorer?

### ISSUE THREAD

**Issue by LorenzoBettini** [spring-projects/sts4#23]
In the current version of STS4 in Eclipse there's no Spring Perspective nor Spring Explorer... will they be added back in the future?

**Comment by martinlippert** [comment]
The STS4 distribution takes a fresh start with many things and therefore doesn't include the Spring perspective and the Spring explorer anymore.

The Spring Explorer will be replaced with the new "go to symbol" infrastructure that provides a much faster and more lightweight way to get an overview of your Spring elements in your project. And since the Spring Explorer was the main difference between the Java and the Spring perspective, we decided to not configure a specialized Spring perspective anymore. In addition to that the "go to symbol" infrastructure is available independent of the chosen perspective.

What exactly are you missing from the Spring Explorer? I would certainly be interested to hear from you what use case you have in mind that the new "go to symbol" infrastructure doesn't serve.

**Comment by LorenzoBettini** [comment]
Hi Martin
what I'm missing from the Spring explorer is the overall view of the application, like beans and mappings... is this still viewable in another way? Does the new "go to symbol" provide the same functionality?

**Comment by kdvolder** [comment]
@LorenzoBettini We think it does. But we'd be interested to hear your opinion on this specifically. Just give it a try. Press CTRL-6 for 'symbols' in current file. Press CTRL-6 again to broaden the scope to the whole workspace. You can search for beans with `@+` and for requestmappings with `@/`.

Note: On Mac, I think it is CMD-6 instead of CTRL-6.

**Comment by davidmichaelkarr** [comment]
I can't find any information about this "goto symbol" thing, or how it could possibly replace the graphical view.  When I press Ctrl+6 in a source file, it does nothing, and I've verified that this key is bound to that "goto-symbol" command.

**Comment by martinlippert** [comment]
@davidmichaelkarr hard to say what is going wrong from this short description, but I am sure we will be able to find that out somehow. First of all, you can find more information on the wiki: https://github.com/spring-projects/sts4/wiki/Navigation

In case this doesn't work for you, we would need to take a look at the details. You could open the preferences and go to the `Language Server` section to see if the `Spring Boot Language Server` is active for all those content-types (which should be by default). Next step would be to select the `Spring Language Server` node in the preferences and enable the console logging for the `Spring Boot` language server. This will open a console view as soon as the language server process starts up behind the scenes. That way you could see if something goes wring inside that language server.

The `Go To Symbol` infrastructure doesn't require anything special, like running the Spring apps or something like that. It should work as soon as it detects a Spring project in your workspace.

Please keep in mind that the symbols in that list are being generated from Spring-specific annotations, so if you still use Spring XML config files, there is nothing showing up by default. We are working on that and you could enable the XML scanning early-access version in the preferences (`Spring Boot Language Server`preferences).

Hope that helps. If there is still nothing showing up for you, we would need ti dig deeper. In that case, it would be useful to share a sample project that reproduces the issue.

**Comment by moueza** [comment]
So is it normal to have no Spring nature any more too ?

**Comment by martinlippert** [comment]
@moueza Yes, the special Spring nature is no longer needed in Spring Tools 4.

**Comment by martinlippert** [comment]
@davidmichaelkarr I forgot to mention that the graphical views are indeed no longer available and the aim of the symbol infrastructure is not to replace the graphical views. There are two things we are working on in this area:

- we work on a new graphical representation for Spring Integration definitions, there are a few more details about this discussed in https://github.com/spring-projects/sts4/issues/167. In case you are looking for additional graphical views, please let us know (in a new enhancement request), so that we can discuss and learn more about the details you are looking for.

- we work on a view that displays symbol information to allow you to, for example, get a view with all your request mappings or a view wit all your bean definitions

**Comment by martinlippert** [comment]
@moueza In case you are migrating an existing project/workspace from STS3 to Spring Tools 4, here is a wiki section on this with more help and details: https://github.com/spring-projects/sts4/wiki/STS3-Migration
