### ISSUE TITLE
Support for Java 11 on Spring Boot Tools Extension for VS Code

### ISSUE THREAD

**Issue by brunoborges** [spring-projects/sts4#254]
Currently, it only works with Java 8 code.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

It seems to be working fine for me after a little bit of trying. There was a little hitch initially. But let me start with explaining what does work before delving into that:

I installed these from vscode marketplace:

- 'Java Extension Pack'
- 'Spring Boot Extension Pack'

I opened a simple/empty and brand new "Spring Boot" project that is setup to use maven and Java 11.

I added these to my 'settings.json' in order to tell both the Redhat Java Language Server and our 'Spring Boot' lanuage server where to find the JDK 11:

```
{
    "java.home": "/home/kdvolder/Applications/jdk-11.0.2",
    "spring-boot.ls.java.home": "/home/kdvolder/Applications/jdk-11.0.2"
}
```

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

About the initial glitches referred earlier...

I first tried to just setup JDK 11 on via env variables

- made sure PATH has the jdk 11 bin folder on it.
- made sure JAVA_HOME points to the jdk 11.

Started vscode with these env variables in effect.

My Java 11 project was then full of errors. The reason seemed to be that it couldn't find JDK or JRE 11. One of the errors was around JavaSE-11 classpath container not being 'bound'. The rest of the errors seemed to be caused by the fact that standard JRE libs are not on the classpath (Object is an unknown class and stuff like that).

Strangely though. I tried to reproduce this problem a second time but was not able to. I am guessing the Java language server may be remembering where to find a compatible JRE 11 even after I was trying to 'confuse' it by not giving it any more hint via env vars or vscode settings.json.

**Comment by kdvolder** [comment]
@brunoborges Do you have any more details that you could add? E.g. how did you set things up exactly? In particular how did you make sure vscode / language servers knew where to find a JDK or JRE 11? How did you setup the project? 

Also curious to know whether the problems I experienced on my first try where similar to yours?

**Comment by brunoborges** [comment]
I can no longer reproduce the issue after a clean install. Closing for now.

**Comment by martinlippert** [comment]
@brunoborges OK, thanks for double checking and letting us know. Looking forward to the next live demos and talks and please continue to mention our tooling extensions for VSCode. So much appreciated!!!
