### ISSUE TITLE
Start language server based on a project nature

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#269]
Today for all java projects, when opening a java file the language server is started. This cause a unnecessary overhead on all java projects. Its better to start the LS if a certain project nature (STS4 Nature) is present in the project.

**Comment by kdvolder** [comment]
I see your point, but this not straightforward. Because

a) lps4e is responsible for starting language servers 
b) project-nature is very specific to Eclipse. The language servers are not Eclipse-specific.

Besides we have some bad experiences with project natures in the past. The problem essentially is that these natures have to be put onto the projects somehow and this is a bit of a conundrum.

Either the user has to put the natures onto their projects somehow, or the tools have to do it automatically.

If the user has to put the natures on the projects's... this is cumbersome and leads complications that the tools don't work unless the user does this. This causes a lot of confusion and bug reports because without nature, the tools don't work and the user doesn't always know why. Also many users have a distaste for committing IDE-specific project metadata to source control, this further aggravates the issue.

If the tools have to autmatically add natures, then the problem is... how does a tool know what projects to put the nature on? This is not obvious and often also requires a lot of information about the project to make a good guess. This information in also not cheap to compute, and unless you keep repeating the computation again as the project data changes... it will not work properly. So basically... it defeats its own purpose.

It is for these reasons that we have moved away from having project natures be the 'switch' that turns on/off IDE functionality in STS4.

**Comment by martinlippert** [comment]
@gayanper I understand your point and agree to the points Kris made at the same time... :-) But I can clearly see that we can and should so something on the "overhead" piece of your question here. What kind of overhead do you observe?

We are actively working on improving startup performance and reduce memory footprint, so that should reduce the overhead (in case this is what you mean). Or do you observe any additional slowdown or lag in the IDE when working with Java files or opening them, related to the language server?

**Comment by martinlippert** [comment]
This has been implemented a while ago, starting the language server as soon as there is a project in the workspace that uses Spring Boot. So it is not exactly relying on a specific project nature in the sense of the Eclipse construct, but checks for projects that are using Spring Boot, independent of their exact natures.

Was part of the work on https://github.com/spring-projects/sts4/issues/880 and got solved in `4.17.0`already.
