### ISSUE TITLE
Live Boot Hint Decorators not working on windows 10

### ISSUE THREAD

**Issue by jcbritobr** [spring-projects/sts4#286]
To Reproduce: Create a spring project without actuator and devtools dependencies. After project is created, add the dependencies.

Im using spring tools 4  under windows 10 x64.
java version - openjdk 12.0.1
spring tools 4.2.1 release
eclipse 2019-03 (4.11.0)

Even with live boot decorators activated in preferences, the feature not works:

![image](https://user-images.githubusercontent.com/6579862/57325042-8b623d80-70df-11e9-893c-93e8e69a23ed.png)

**Comment by BoykoAlex** [comment]
Maybe it has to do with Java 12. Did you try Java 8 or 11?

It worked for me with Java 8 and 11. If you add Actuator and DevTools when the app is running you'd need to restart the app and then live hints appear... Otherwise it should work.

**Comment by jcbritobr** [comment]
> 
> 
> Maybe it has to do with Java 12. Did you try Java 8 or 11?
> 
> It worked for me with Java 8 and 11. If you add Actuator and DevTools when the app is running you'd need to restart the app and then live hints appear... Otherwise it should work.

Hi. I have not tested with java 8 or 11 yet, but when I set the project with devtools and actuator after, even restarting the app it didn't work. I don't know if this is a issue, but is better got it register.

**Comment by jcbritobr** [comment]
I did more tests, and really there is an issue. Once I have configured the springboot gradle project, even adding new dependencies to build.gradle the spring tools wont will recognize them. This happens to all dependencies.

**Comment by martinlippert** [comment]
First step here would be to make sure that all the dependencies that you declared are indeed recognized by the IDE and added to the classpath of the app. You can double check that in the package or project explorer by expanding the classpath container entry of the project, either the `Maven Dependencies` or the `Project and External Dependencies`.

In case you use Gradle for managing dependencies, make sure that you import the project as a Gradle project, so that the build-in Gradle tooling takes care of the dependencies. Maybe you need to trigger the tooling to update dependencies once you changed your gradle file (via the `Refresh Gradle Project`)?

So after taking care of all this, can you see the actuator dependencies showing up as part of the classpath of the project?

**Comment by jcbritobr** [comment]
@martinlippert refreshing gradle project solves the problem.

**Comment by martinlippert** [comment]
OK, great to hear that it is working now. And thanks for letting us know.
