### ISSUE TITLE
Eclipse Boot Wizard cannot be resolved

### ISSUE THREAD

**Issue by mtheiss** [spring-projects/sts4#308]
Eclipse 2019-06 with STS4. Boot Wizard cannot be resolved. No new project wizard available.

Caused by package javax.xml.bind.annotation being available via two paths.
Once via system.bundle and once via bundle javax.ws.rs

[sts4-boot-wizard-activation-error.txt](https://github.com/spring-projects/sts4/files/3310011/sts4-boot-wizard-activation-error.txt)

**Comment by martinlippert** [comment]
Yes, I came across this problem recently, too. There are two solutions to this:
- run your existing installation on top of a JDK11
- download and run an STS4 distribution (using either JDK8 or JDK11)

This is caused by a subtle OSGi wiring mismatch, caused by the java.ws.rs bundles package imports... :-(

In case you are waiting for an STS4 distribution on top of Eclipse 2019-06, it will probably be released tomorrow (June 21)... :-)

**Comment by martinlippert** [comment]
This can be closed, I think. We are still experiencing a few wiring issues around javax.xml.bind, but that is a different story.
