### ISSUE TITLE
Spring boot 2.0 compatibility

### ISSUE THREAD

**Issue by martinborgman** [spring-projects/sts4#31]
Due to the changes in how Spring boot actuator endpoints work sts4 cannot find the information it needs to provide runtime feedback such as the available endpoints in your application or simply the classes that are loaded at runtime...

**Comment by kdvolder** [comment]
We did test it with Boot 2.0 apps, but its possible they broke it again. Seems like the boot folks keep changing their minds on what JMX bean names the endpoints should be exposed as.

**Comment by kdvolder** [comment]
Seems to be working fine for me. Using latest snapshot of STS 4 nightly, I created a new spring boot app using 'New Spring Starter' project wizard.

I selected 'Maven' type, added 'actuator' and 'web' dependencies, and selected version Boot 2.0.0 SNAPSHOT.

I quickly added a simple 'hello world' endpoint. Run the app from STS 4 and everything seems to work:

- properties pages is showing beans and requestmappings
- STS 4 highlights in the editor for these things also working.

BTW: I do beleave that it may not work with Boot 2.0.0.M7. If that is the reason its not working for you, then please know that is not something we are going to fix, since once 2.0.0 is released people really shouldn't be staying with a milestone of spring boot anymore. If you are using a boot 2.0.0.SNAPSHOT and its not working for you, please provide some more details on exactly what you are doing so we can reproduce it. Then we can reopen the issue.

**Comment by martinborgman** [comment]
Yes, it works with boot 2.0.0.SNAPSHOT. I did use M7 before.
