### ISSUE TITLE
Spring Boot tools extension cant install properly.

### ISSUE THREAD

**Issue by mr-techiee** [spring-projects/sts4#316]
Issue Type: <b>Bug</b>

i cant install the spring boot tools properly, its getting too long time.

Extension version: 1.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by martinlippert** [comment]
I am not sure I understand exactly what you mean. Does the install of the extension into VS Code takes too long to complete? If so, does it work better for other extensions? Since the download via the Visual Studio Marketplace is something that we don't control, it might be hard for us to find out what is going wrong here.

Or do you mean something else is being slow or takes too long?

**Comment by martinlippert** [comment]
Closing this issue now due to lack to additional input. Please feel free to comment with more details and we can re-open this item anytime.
