### ISSUE TITLE
Ignore unrelated property files

### ISSUE THREAD

**Issue by neekibo** [spring-projects/sts4#320]
The STS language-server is validating my message.properties (translation files) and it gives me useless/countless "unknown property" warnings. I also get errors like mentioned in #314 

Was working correct with Spring Tool Suite 4 Version: 4.2.2
Wrong behavior occours since upgrade to Spring Tool Suite 4 Version: 4.3.0.RELEASE, Build Id: 201906200901

Is this intentional?
How does the language server knows which properties-file is a spring-configuration?
Can I configure this behavior and ignore my message.properties?

Thanks

**Comment by kdvolder** [comment]
I'll have to debug this to determine why this happens. I think it used to be a problem in the past and was caused by how lsp4e determines which files to validate, which is related to content-types assigned by Eclipse. Don't recall details, but I beleave it got fixed. Seems like it broke again :-(

**Comment by kdvolder** [comment]
And to be clear:

> Is this intentional?

No, of course not. So thanks for reporting the poblem :-)

**Comment by kdvolder** [comment]
> Can I configure this behavior and ignore my message.properties?

You can try making some changes to Eclipse workspace 'content-type' configuration. Which you can access at "Preferences >> General >> Content Types". I have my doubds that you will be able to 'fix' this though by meddling with them. I suspect the content type is determined correctly, but some 'bug' in either our language server or the Eclipse lps4e infrastructure is handling this incorrectly and validating the file even though it is not classifies as a 'Spring Properties File'.

**Comment by kdvolder** [comment]
Was able to easily reproduce the issue. I used STS 4.3.1.

Steps:

- created a boot project (don't think the starters matter but I used 'web' and 'actuator')
- opened application.properties and edited a bit.
- created a new file called 'whatever.properties'.
- added some text like this `bork=bark`.
=> A warning appears on that 'bork' is an unknown property

**Comment by kdvolder** [comment]
I think there's a bit of a mess going on between lsp4e and eclipse platform content type framework. This to the point that I don't think we can fix this bug without breaking something else in the process.

The problem seems to be that when our 'Spring Properties File' content type derives from the 'Java Properties File' as a base-type, then lsp4e will start invoking the reconciler on *all* properties files. 

I don't think lsp4e should do that, that seems like a bug in lsp4e.

We can avoid this problem by just declaring our content-type with base type of "Plain Text". Our editor still works fine in that case... except, there are some menu items to "Open With >> Generic Editor (Spring Properties File)". These no longer work as expected. They still open the generic editor, but special features (content assist, hovers and reconciling) do not work in the opened editor).

That also seems like a bug to me (not sure yet who to blame for this problem).

Anyhow... as the unwanted reconciling seems like a bigger and more annoying problem I will fix this for now and then raise other tickets to investigate these afterwards.

Since this bug is pretty annoying... I am choosing to fix this

**Comment by kdvolder** [comment]
I think the underlying issue is really a bug in lsp4e, so I have reported it here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549321

Fortunately were able to work around/avoid hitting the bug by making sure we allways use base-`type="org.eclipse.core.runtime.text"` even when it might seem more logical to use a more specific base-type.
