### ISSUE TITLE
testNg plugin is not installable in latest sts 4 

### ISSUE THREAD

**Issue by rgampa** [spring-projects/sts4#322]
testNg plugin can't be installed from marketplace after upgrading to latest sts4 (eclipse), please suggest alternative.
 
Spring Tool Suite 4 

Version: 4.3.1.RELEASE
Build Id: 201907120711

In the previous sts4 I could install testNg, I have upgraded it to see Tomcat 8.5v in server run times. 

if there is no fix, how to go back previous sts 4 release? I don't find it in spring.io/tools

**Comment by kdvolder** [comment]
I will investigate the problem in a bit. It might help if you posted any error message you got while trying to install testNg.

In the mean time let me start by trying to answer this question first.

> how to go back previous sts 4 release?

Actually, it seems hard to get to any sort of page that archives previous releases, or a least its very hard to find (as I can also not find it). I think that is a problem that should be adressed and I'll follow up on this.

In the mean time you can actually download older versions by 'hacking' the download urls and basically just replacing the version number with the one you want.

For example, from here: https://spring.io/tools

I can right click on one of the buttons to download STS and see do 'copy link' and get a link like this one:

https://download.springsource.com/release/STS4/4.3.1.RELEASE/dist/e4.12/spring-tool-suite-4-4.3.1.RELEASE-e4.12.0-linux.gtk.x86_64.tar.gz

If I wanted to have 4.3.0 version instead I can just edit the url and change '4.3.1' to '4.3.0'. 

Also, in case the problem is not actually in STS itself but comes from the Eclipse platform, then it might be useful to try and change the eclipse platform version as well. 

I know this kind of 'hacking the url' is not ideal, there should be list somewhere instead, but at least you can get / download old version this way now if you wanted to.

**Comment by rgampa** [comment]
@kdvolder There is nothing special about error, there is a popup with message saying current version doesn't support testNg. 

It's great hint to install previous version, will try it out.

**Comment by rgampa** [comment]
I wanted to go back to 4.1.x version, but it doesn't work with below modified URL, getting access denied error. 

https://download.springsource.com/release/STS4/4.1.2.RELEASE/dist/e4.12/spring-tool-suite-4-4.1.2.RELEASE-e4.12.0-macosx.cocoa.x86_64.dmg

**Comment by kdvolder** [comment]
I assume this is the plugin you are trying to install?

http://marketplace.eclipse.org/content/testng-eclipse

> saying current version doesn't support testNg.

Yes, I saw that too. I just tried it. Still it would have been helpful to say that. We get all kinds of reports that something can't install and it can be for all sorts of reasons, including network issues, corrupted Eclipse installation etc. etc. The message narrows it down a bit. Anyhow, it was easy enough for me to try and get the error myself, so no big deal.

From what I can tell this plugin hasn't been updated in a while and doesn't seem compatible with recent Eclipse platform versions. It's Marketplace page, for example states that the latest version of Eclipse it is compatible with is Eclipse 4.9 and we are now on Eclipse 4.12. Unfortunately Eclipse 4.9 is now so old that we no longer build a distribution for ir.

So this isn't a problem with STS but the TestNg plugin. You should try to raise the issue with its owner.

I am leaving this ticket open

**Comment by BoykoAlex** [comment]
@rgampa There was no eclipse 4.12 at that time probably. This URL should work: https://download.springsource.com/release/STS4/4.1.2.RELEASE/dist/e4.11/spring-tool-suite-4-4.1.2.RELEASE-e4.11.0-macosx.cocoa.x86_64.dmg

**Comment by kdvolder** [comment]
> I wanted to go back to 4.1.x version, but it doesn't work with below modified URL, getting access denied error.

That version was not built for Eclipse 4.12 because Eclipse 4.12 didn't exist back then. 

So try this:

https://download.springsource.com/release/STS4/4.1.2.RELEASE/dist/e4.11/spring-tool-suite-4-4.1.2.RELEASE-e4.12.0-macosx.cocoa.x86_64.dmg

**Comment by kdvolder** [comment]
If STS 4.1.2 on Eclipse 4.11 works for you, then perhaps you may also be able to use the latest STS 4 release on Eclipse 4.11. We still built STS 4.3.1 for Eclipse 4.11 though, again, these links are hard to find and that is a problem we should address.

https://download.springsource.com/release/STS4/4.3.1.RELEASE/dist/e4.11/spring-tool-suite-4-4.1.2.RELEASE-e4.11.0-macosx.cocoa.x86_64.dmg

**Comment by kdvolder** [comment]
Although the install issue doesn't seem like a STS problem. The problem that the links for old STS 4 releases are hard to find is something we should address. I'll create a separate ticket for that.

**Comment by rgampa** [comment]
@kdvolder I have installed E4.9 using https://www.eclipse.org/downloads/packages/release/2018-09/r, then could able to install testNg, and STS tools 4.1.0. I could export testNg software to file, and then import to STS 4 as well. This is suggested approach as mentioned in https://marketplace.eclipse.org/content/testng-eclipse reviews.

**Comment by kdvolder** [comment]
I don't think I understand the process you describe, but if it works for you then I'm happy you were able to solve your immediate problem. 

To my mind though, this sounds like a terrible workaround for something that the owner of the plugin alone can properly fix.

It looks like this is the home of the plugin's source code:

https://github.com/cbeust/testng-eclipse#update-sites

So if you want to get it properly fixed, you could try to raise an issue there. From the looks of things though, the repo has not seen much/any activity in over 2 years. So it may be the case that the project has been abandoned by it's owner.

**Comment by bodtx** [comment]
✅It's working with the update site https://dl.bintray.com/testng-team/testng-eclipse-release as specified on the [github page](https://github.com/cbeust/testng-eclipse#update-sites).

indeed not working with the one of the marketplace.

**Comment by martinlippert** [comment]
The related issue at TestNG is: https://github.com/cbeust/testng-eclipse/issues/463 - the marketplace entry needs an update of its metadata.

**Comment by SravanBetanapalli** [comment]
Worked with Help->install software->http://dl.bintray.com/testng-team/testng-eclipse-release
