### ISSUE TITLE
Can you document inJavadoc of  a number of annotations that hey does not want static method?s

### ISSUE THREAD

**Issue by Marco-Sulla** [spring-projects/sts4#323]
I work with Spring (Boot) and Eclipse. I enabled the warnings about methods that can be declared as static. The problem is Eclipse signals also methods decorated by `@Autowired` and other Spring decorators that does not want a static method.

[I reported the problem to Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547451), but they say they can't trust me, it must be documented in the Javadoc of the annotations.

Can you please add this information to the annotations that doesn't want a static method?

Thank you in advance.

**Comment by kdvolder** [comment]
Sorry for the long delay in responding to you. I went through the conversation on the Eclipse bug and I feel and sympatize with your frustration.

We can't unfortunately change these docs ourselves, but I'll reach out to some folks on the spring framework team and see if they can help resolve this.

**Comment by Marco-Sulla** [comment]
Oh, no frustration, I'm just ignoring these warnings for now. Thank you a lot, I hope in future Java will implement something standard, like an ad-hoc javadoc.

**Comment by kdvolder** [comment]
> Where can I propose such a introduction to javadoc?

Well, if this is just something specific for Eclipse, on Eclipse bugzilla. But if you seen recent discussion about it there, I think it is somewhat unlikely this will be adopted because it really should be done as part of Java / JRE / JDK standard itself. 

If that's in fact what you are suggesting...I am not very familiar with the process of proposing extensions to the Java platform. It is not impossible, but I beleave it is a rather long, complex and formal process. You don't seem like the type who is easily discouraged though, so if you want to pursue it, you can read up on it here:

https://en.wikipedia.org/wiki/Java_Community_Process

**Comment by martinlippert** [comment]
Since most of the discussion of this happens on this bug at Eclipse:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=547451

I tend to close this issue here. Would that be fine with everybody involved?

**Comment by martinlippert** [comment]
Ok, so let me close this one here and continue the discussion on the Eclipse bug. I think having the whitelist that Stephan mentioned over there configurable would be the best choice and allow us and/or users to modify that list whenever it makes sense. We can also try to submit a PR for that whitelist with the most famous Spring annotations, maybe that is enough of an "official" thing from the Spring team. Let's see.
