### ISSUE TITLE
[critical] XML completions are not working

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#337]
XML completions are not working in eclipse.

Version Info: 
Spring Tool Suite 4 Main Feature	4.3.2.201908030014-CI-B1945
Spring Boot Language Server Feature	4.3.2.201908022241

**Comment by martinlippert** [comment]
Can you share an example project? There was a problem with the support for XML files, but that is already fixed, so should be included in the version that you referenced. Sample project would be awesome to reproduce this.

**Comment by gayanper** [comment]
[xml-sample.zip](https://github.com/spring-projects/sts4/files/3477087/xml-sample.zip)

**Comment by gayanper** [comment]
I think the dependency for dbcp2 is missing in the pom.xml but even after adding it the completions are not working class and properties

**Comment by gayanper** [comment]
I can confirm that this is working in version 4.3.1.x, i think the latest snapshot has this problem.

**Comment by kdvolder** [comment]
I can try to reproduce, but can you please be very precise on what I should try? What file do I open, where do I place the cursor to try to get content-assist.

I'm affraid I'm not really enough aware of what is actually supposed to work that I would know what to do. Sure I can click around the project and try some content assists in xml, but since I'm not sure what is actually supposed to work, then it be hard for me to know that if I don't see any results in a specific location whether that is expected in that particular location or not.

I suspect this problem still has something todo with recent changes around content-type handling in Eclipse and I can probably debug (and hopefully fix), but having a good and specific 'base-line' example to debug is really helpful.

**Comment by gayanper** [comment]
@kdvolder You can try to open the applicationContext.xml in the resource folder. And try to add a property to the datasource bean by using auto completion to complete the property names which belongs to the BasicDataSource class. Basically the completions should contain all properties from the BasicDataSource which are writable.

**Comment by kdvolder** [comment]
Thanks for those details, but not having much success reproducing. Well... yes, it doesn't work but... to make sure I've got the right 'base line example' I'm trying to first get it to work in STS 4.3.1. But doesn't seem to work either. So maybe I'm just not trying the right thing?

My applicationContext.xml has this now:

```
	<bean class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<property name="driverClassName" value="net.sourceforge.jtds.jdbc.Driver"/>
		<property name=""></property>
	</bean>
```

I am placing the cursor inside of the `""` and press CTRL-space. It gives me no proposals. (There's a red error message in the status bar below showing "Content Assist not available at the current location". This is with STS 4.3.1.

**Comment by kdvolder** [comment]
I've had to guess a bit what was meant by this comment:

> I think the dependency for dbcp2 is missing in the pom.xml but even after adding it...

But figured it probably means the sample is not actually 'complete' and needs this to work:

```
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-dbcp2</artifactId>
		</dependency>
```

Even after adding it I can't get completions in either 4.3.1 or latest snapshot. So I am still not sure what I'd actually have to do (in 4.3.1) to make it work.

Near as I can tell it behaves exactly the same in both 4.3.1 and latest snapshot. Even the content-type reported in Eclipse 'properties' view for the xml file seems right (in both cases).

**Comment by kdvolder** [comment]
Moving on to something else for the time being. 

@gayanper please provide more detailed and step by step instructions such that: 

a) steps produce expected result in STS 4.3.1.
b) same steps produce a different result in STS latest snapshot.

Please make these steps as complete and precise as possible. I.e. start from new workspace, import this as follows etc. Maybe not all the details matter but since my guesses on these details seem to be producing a different result than what you see, some of these steps probably do matter.

**Comment by gayanper** [comment]
@kdvolder do you have the spring xml language server enabled and the setting enabled to scan xml files for spring configurations ?

**Comment by gayanper** [comment]
@martinlippert i think this is something related with the content type identification. Because in 4.3.2 the language server is not started when i open the xml file.

**Comment by martinlippert** [comment]
I tried this and it looks like the language server is correctly started when I open the `applicationContext.xml` file from your sample project. After that, content-assist for bean types works, too. But keep in mind that the content-assist doesn't do anything if you have an empty prefix (due to too many possible options). So if you do:

```
	<bean id="xmlStringBean2" class="<*>">
		<constructor-arg value="stringBean2" />
	</bean>
```

and hit content-assist, you will get nothing. When you do:

```
	<bean id="xmlStringBean2" class="j<*>">
		<constructor-arg value="stringBean2" />
	</bean>
```

you will get nice content-assist for the packages starting with `j`.

However, the content-assist for property names doesn't seem to work, there must be a bug in the implementation.

**Comment by gayanper** [comment]
@martinlippert in the first example of yours the class names are not provided right ? Any reason only packages ?

**Comment by martinlippert** [comment]
The class names are provided when you hit content-assist with a valid package prefix, they do not show up automatically if you continue typing while keeping the content-assist open.

**Comment by martinlippert** [comment]
Ok, the property name content-assist doesn't work in your example project due to the fact that the bean type is not on the classpath of the project - and therefore the language server is not able to figure out the property names of that type.

The maven dependency that Kris mentioned above is the wrong one (doesn't contain that type), here is the right one:

```
<dependency>
    <groupId>commons-dbcp</groupId>
    <artifactId>commons-dbcp</artifactId>
    <version>1.2.2</version>
</dependency>
```

Once this is on the classpath, the type is available for the language server to analyze and property names are being provided by the content-assist.

**Comment by martinlippert** [comment]
Summarizing this up, it looks like the XML support is actually working as designed here:
- language server starts up for that XML file
- type content-assist shows up
- property-name content-assist shows up

Please double check. If all this works for you, too, we can close this issue.

**Comment by gayanper** [comment]
Yes it was some configuration sync issue, with the lastest SNAPSHOT of 4.3.2 it is working for me.
