### ISSUE TITLE
Font display problem when dragging scrollbar in console

### ISSUE THREAD

**Issue by vision-ken** [spring-projects/sts4#346]
Found in STS 4.3.1.RELEASE & 4.3.2.RELEASE（macOS 64-bit), but work fine in STS 3.x.
![image](https://user-images.githubusercontent.com/24715266/63401356-954b4a80-c409-11e9-9311-08098b7c9641.png)

**Comment by martinlippert** [comment]
I think this is the same as reported in #312, so closing this here again. The fix from the Eclipse platform will be released as part of the Eclipse 2019-09 release, coming out late in September. If you wanna give early CI builds of STS4 on Eclipse 2019-09 (aka 4.13) a try, you could grab a CI build from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html - but since Eclipse 4.13 isn't released yet, those builds contain early milestone and integration builds of the Eclipse platform, too (not a stable release).
