### ISSUE TITLE
NetBeans support

### ISSUE THREAD

**Issue by Chris2011** [spring-projects/sts4#37]
Hi,

I see that your tools are available for vscode, atom, eclipse and intelliJ, for me NetBeans is missing. Can you please add support for NetBeans as well? That would be great.

Regards

Chris

**Comment by martinlippert** [comment]
We support Eclipse, VSCode, and Atom, but we don't support IntelliJ yet (mostly because of the lack of support for the language server protocol). For the same reason, we don't support Netbeans (yet).

Once there is some official support for the language server protocol coming to the Netbeans IDE, we might revisit that, but I haven't seen any activity on this from the Netbeans project yet, therefore closing this item for now.

**Comment by Chris2011** [comment]
Thx for the info :)

**Comment by martinlippert** [comment]
I saw that there is an enhancement request on the Netbeans issuetracker to support the LSP protocol. Maybe going there and adding a comment and/or vote helps to draw more attention to that... :-)

**Comment by Chris2011** [comment]
I know that issue yes. I think I already vote for it, but yeah I know what you mean :)
