### ISSUE TITLE
MacOS Catalina STS4 not Running

### ISSUE THREAD

**Issue by playdev-co-kr** [spring-projects/sts4#375]
‘SpringToolSuite4’ cannot be opened because Apple cannot check for malicious software.

**Comment by martinlippert** [comment]
We don't have a notarized version of the macOS application yet, but we will try to get this done soon. Since I haven't macOS Catalina installed yet, I cannot try solutions myself, but maybe you can give this a try?

`xattr -r -d com.apple.quarantine /<pathToSTS4App>/SpringToolSuite4.app`

Does that help?

**Comment by cedarjo** [comment]
@martinlippert thank you for your suggestion

![image](https://user-images.githubusercontent.com/22877523/66727250-81075500-ee70-11e9-8db3-53b6bfdc0a7d.png)

`xattr -r -d com.apple.quarantine /Applications/SpringToolSuite4.app`

![image](https://user-images.githubusercontent.com/22877523/66727280-b4e27a80-ee70-11e9-8a17-24e06c6d2673.png)

**Comment by martinlippert** [comment]
@cedarjo not sure how those screenshots are related to this issue. Seems to be instead belong to #377 .

**Comment by cedarjo** [comment]
@martinlippert sorry, this is the first time I try to use STS4. I open the website "https://spring.io/tools" and download "spring-tool-suite-4-4.4.0.RELEASE-e4.13.0-macosx.cocoa.x86_64.dmg".

**Comment by martinlippert** [comment]
@cedarjo No problem at all, just trying to find the right item for your issue. If you have trouble with Catalina, this one is the right for you, if you have trouble getting Lombok to work with STS4, the #377 seems to be the right one.

**Comment by martinlippert** [comment]
I might be wrong with regards to #377 being the right issue for your Lombok-related questions, since that seems to be a pure keyboard shortcut related question around the quick search instead of a real Lombok-related question.

Can you tell me again what exactly the problem is? The screenshots show that you installed Lombok (which is usually unrelated to the Catalina notarization issue). Can you shed some light on this?

**Comment by mstarkie** [comment]
> We don't have a notarized version of the macOS application yet, but we will try to get this done soon. Since I haven't macOS Catalina installed yet, I cannot try solutions myself, but maybe you can give this a try?
> 
> `xattr -r -d com.apple.quarantine /<pathToSTS4App>/SpringToolSuite4.app`
> 
> Does that help?

Yes

**Comment by martinlippert** [comment]
Awesome, that is very very good to know... :-)
At least there is a workaround until we get the app notarized.

Thanks for the feedback, much appreciated !!!

**Comment by gcamara** [comment]
> We don't have a notarized version of the macOS application yet, but we will try to get this done soon. Since I haven't macOS Catalina installed yet, I cannot try solutions myself, but maybe you can give this a try?
> 
> `xattr -r -d com.apple.quarantine /<pathToSTS4App>/SpringToolSuite4.app`
> 
> Does that help?

Thanks @martinlippert ! Helped a lot

**Comment by martinlippert** [comment]
We just released 4.4.2, which is notarized for macOS and should work now out-of-the-box.
