### ISSUE TITLE
Spring Tools 4 Plugin for Eclipse, CTRL-SHIFT-L  quicksearch not working on Eclipse 2019-09 with lombok on Mac 10.14

### ISSUE THREAD

**Issue by AlessandroC85** [spring-projects/sts4#377]
Steps to reproduce the issue:

- install Eclipse 2019-09
- Install lombok (latest version)
- relaunch eclipse
- install Spring Tools 4 from Marketplace
- reboot

The Quicksearch (CTRL+Shift+L) doesn't work, it appears the "Show Key assist" instead.

**Comment by martinlippert** [comment]
With regards to Lombok, it might be useful to check for Lombok being compatible with the latest Eclipse 2019-09 version. Since Lombok does a somewhat deep integration with Eclipse, it can easily be the case that new Eclipse versions break with older versions of Lombok.

An additional side note: In case Lombok doesn't recognize STS4 as an Eclipse install, you need to setup the Lombok config manually in the SpringToolSuite4.ini file.

With regards to the Quick search keyboard shortcut, please note that the quick text search got contributed to the underlying Eclipse platform and has changed the keybinding since then. You can usually find it via CTRL+ALT+SHIFT+L.

But I haven't tried this with Lombok installed on top.

**Comment by manueljordan** [comment]
Just in case:

* [Lombok with Spring Tool Suite 4](https://stackoverflow.com/questions/52780535/lombok-with-spring-tool-suite-4/52780688#52780688)

I work with STS 4 directly. I mean, I get the installer from:

* [Spring Tools 4](https://spring.io/tools)

Thus I don't get STS through marketplace.

Perhaps would work directly.

**Comment by kdvolder** [comment]
So, from the looks of things the issue in this ticket is that the quicksearch doesn't show up when pressing CTRL-SHIFT-L. I have updated the title accordingly. As Martin explained, the shortcut for his was changed when Quicksearch was contributed to Eclipse. The new key combo is CTRL-ALT-SHIFT-L.

I have change the title to be more descriptive of that problem.

Since this isn't really a bug (the key combo was changed on purpose because it otherwise conflcts with the 'Show Key Assist' key binding), I'll resolve / close this ticket.

If you have some other problem with Lombok and STS 4 then please raise a new ticket.

**Comment by manueljordan** [comment]
Is possible see the new combination directly through `Search` -> `Quick Search`
