### ISSUE TITLE
Suggest: Optional link console tab with Boot Dashboard selection

### ISSUE THREAD

**Issue by habuma** [spring-projects/sts4#386]
In STS (and just Eclipse in general), I have the option to Link Package Explorer with whatever code tab is open. 

Similarly, it would be very helpful, especially when I'm running several applications, if the Console tab's content would be linked to whatever app is selected in Boot Dashboard. 

That is, if I have three apps running (App A, App B, App C) and I click on App B's entry in the Boot Dashboard, I'd like the Console tab to display that app's logs/sysout, so that I don't have to dig through the "Display Selected Console" dropdown to find my app's output.

**Comment by kdvolder** [comment]
Sounds like a good idea. In the mean time are you aware that you don't have to dig through a context menu to reveal the console for selected app? You can just click on this icon in the boot dash's toolbar:

![open-console-button](https://user-images.githubusercontent.com/1002156/67798647-20b40e00-fa41-11e9-863c-f45648673602.png)

**Comment by martinlippert** [comment]
@habuma I had the same idea a while ago, but it never made it into the product yet. Thanks for the reminder and the suggestion, definitely something we should implement for the next release.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

I added a "Link with Console" button in the boot dashboard that will link the dashboard selection with the console, much like the Package explorer can link an editor with a selection in the  explorer.  I also added it to the boot dashboard dropdown menu. 

When the button is toggled, the console content will automatically change as selection changes in the boot dashboard.

See attached screenshots

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

After linking enabled. Whenever I click on any element in the boot dash that has no console, for example, because it isn't running, then I get an annoying error popup.

This is really making this feature unusable in practice.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Another problem. The 'checked' state of the menu item in context menu seems to be incorrect sometimes. It shows as checked in the menu even after I disabled it in the toolbar already.

Also not sure if this particular action really does anything other than changing its own checkbox. 

To be clear, there are 3 different places that I find this action:

- toolbar
- pulldown menu in the view
- Right-click context menu in the tree

It is the latter one that seems to be 'disconnected' and non-functional. I'd be fine with fixing this nitpick by simply removing it from the right-click menu. Since it is not really an action that you apply to a specific element.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

The pop-up error window that appears is from before this feature was implemented. You will get this too if you click on the old "Open Console" action on an app that  has no console or is not running. Do we want to completely get rid of this pop-up for both "Open Console" as well as "Link with Console", and write the error message on the console instead of showing a pop-up?

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

I think it makes sense to get a popup when I click the 'show console' button. But now when the console switch is via 'link with console'.

I.e. when I click a button to open a console and this is not possible then an error popup makes sense and is better than just nothing happening at all.

But for the link with console the switch is implicit and it just too disruptive to popup an error message all the time. Especially since it doesn't feel like an error in this case. 

I'd say that you just want to suppress the popup specifically when 'show console' was triggered via link with console but not otherwise.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Nieraj Singh:) 

The following changes have been made:

1. Removed "Link with Console" from right-click context menu. It is now just present in the toolbar and the drop-down menu
2. Suppressed pop-up error dialogue for "Link with Console" action, such that when switching between apps, the dialogue will  no longer appear if the console is not available. The pop-up will still appear for "Open Console" action.
