### ISSUE TITLE
other ide support

### ISSUE THREAD

**Issue by happyapple668** [spring-projects/sts4#391]
other ide support???such as  intelliJ idea

**Comment by BoykoAlex** [comment]
There is support for VSCode and Theia. IntelliJ support is purely experimental but someone from the community decided to make IntelliJ support production ready here https://github.com/gayanper/sts4. There was Atom support as well but we don't support it anymore... However, the code is still around and if you're interested i can give you instructions on installing Atom extensions from git repo.

**Comment by martinlippert** [comment]
@happyapple668 Please also note that IntelliJ comes with awesome support for Spring as part of their Ultimate Edition. But since we focus on implementing most of the tooling for Spring as a language server, it is certainly possible to integrate that into other IDEs for which we don't do the integration ourselves. As Alex mentioned, @gayanper worked a bit on integrating it with IntelliJ as a community effort. So if you are specifically interested in that, feel free to ping him and maybe offer your help... :-)

**Comment by gayanper** [comment]
@happyapple668 you can try my unofficial builds from https://dl.bintray.com/gayanper/idea-plugins/. I have not merged yet to spring tools main repo since i'm waiting for a release from lsp4intellij (which is a repo i do contribute) with all my fixes.

**Comment by happyapple668** [comment]
thanks
