### ISSUE TITLE
Spring Tool Suite tool performance is disappointing now a days

### ISSUE THREAD

**Issue by bismoy2013** [spring-projects/sts4#417]
I am not sure if this is the right way to address issues about STS product but I am personally very disappointed as a developer. First off, it keeps on getting hung unexpectedly in the middle of work , especially when I am trying to "open implementation of a given method" . Secondly, I am unable to view source code , although in Intellij I can literally scan inside a jar easily . There are many other minor concerns but these two are very major reasons why I am frustrated as a user. There were times when I thought, may be it's my system, referring to point no 1, changed my laptop and still the same story !!

**Comment by martinlippert** [comment]
Hey @bismoy2013, thanks for reporting this and sharing your experiences. I am sorry to hear about your bad experiences and the performance issues. We would be more than interested in figuring out what exactly is going wrong (also performance-wise), since this is clearly not the intended behavior and also not the behavior that I am experiencing on my end using the Spring Tools. Would be awesome if we could spend a few cycles on identifying the underlying issues with a bit of help from your end. Would that be possible?

As a first indicator, it would be awesome if you could share the exact version of the Spring Tools that you are using. Do you use the ready-to-use distribution or did you install the Spring Tools into a plain Eclipse? Additional information about your setting might also be helpful (JDK version, assigned max heap space, etc.). Also if you could provide a sample project that illustrates the issues (the one about not being able to browse source code as well as the performance issue when opening the implementation of a given method) and some detailed steps how to reproduce the behavior that you observe would be fantastic.

**Comment by bismoy2013** [comment]
@martinlippert thank you for the quick response. It was very much needed. I am currently using STS version 4 . The system that I am using is Macbook Pro and it's using MacOS Catalina version 10.15.3 . Sharing the .ini content in case that helps as well. I did download from this site : https://spring.io/tools , I believe this is the official webpage . Downloaded for MacOS 64 bit . JDK version I am using is openjdk version "1.8.0_242" . Due to privacy issues, I won't be able to share my project , but I hope I was able to explain that part clearly , Imagine just a simple method written in a Service class within a Spring boot project, and now I want to check what's the implementation like of that particular method, therefore, naturally I would click on the implementation of that method and that time, sometimes the mouse pointer keeps on rotating and I am forced to "Force Quit" and it works when I restarts , but the point is I want it running smoothly as a developer , at times it's embarrassing as most of my company folks promote intellij and I am disappointed when my choice of IDE behaves that way . 

There was also another instance, imagine you have added external jars and there are some codes which is using the codes in those jar , and it won't open the implementation , it would ask me to "Download source code bla bla bla" , or you can test it in the simplest way, have a dependency added in your pom.xml of your maven project, if any code is referring to the implementation present in those maven dependency which in turn is obviously a jar , just the only difference , it's not external this time, even in this case sometimes it won't open the class files which is already present within the jar file as a result of imported dependencies via pom.xml file . I hope I was able to explain to some extent though , I am not sure may be I am doing wrong but these much complications I never witnessed in intellij to be honest, pretty simple there , Even adding lombok is so much of complicated process that I need to follow , I think we can make STS further more user friendly , let's make it very easy to use .

-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.1100.v20190907-0426
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx2048m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts
-Xdock:icon=../Resources/sts4.icns
-javaagent:/Applications/SpringToolSuite4.app/Contents/Eclipse/lombok.jar

**Comment by kdvolder** [comment]
Spotted this:

```
-javaagent:/Applications/SpringToolSuite4.app/Contents/Eclipse/lombok.jar
```

To rule out that lombok might be part of the problem, can you remove it and see if it helps.

**Comment by bismoy2013** [comment]
I can try but then I am using lombok in my project . Is there any other recommended ways that I can try adding lombok dependency in my project ?

**Comment by kdvolder** [comment]
No, there is no other way but unfortunately Lombok is often a cause of problems for the IDE.
That is not to say that Lombok is causing a problem right now, but it would be good to rule it out.

**Comment by kdvolder** [comment]
Another thin that may help get info about the problem. You can enable 'UI responsiveness tracking' via Eclipse preferences. Just go to "Window >> Preferences >> General >> UI REsponsiveness monitoring". Enable this. It may log some interesting stack traces when there is a UI freeze.

**Comment by bismoy2013** [comment]
Isn't that the point of stabilising an IDE despite usage of some external dependencies like lombok ? I mean I can remove and may be STS IDE will start working smoothly , but then don't you think the purpose has failed here , I am still playing by the rule, in fact I have added lombok following a widely accepted tutorial , my point is no matter what, IDE has to stand strong ! "If Intellij can , STS should be able to endure as well" , is what's going on in my mind . Probably STS needs more stress testing or dependicies like lombok should have a better way to be added within the IDE , may be via installing it as plugins from marketplace just like intelliJ does

**Comment by kdvolder** [comment]
> Isn't that the point of stabilising an IDE despite usage of some external dependencies like lombok

Sure, but  Lombok is not your typical 'external' dependency. Lombok uses a java agent to *modify* Eclipse JDT under the hood. If Lombok is causing issues then the issue should be filed with Lombok and Lombok should fix it. 

Now, as I said, we don't know if Lombok is causing the issue, and in order to try to find out if it may or may not be a part of the problem... I was asking you try if you the problem still happens without it. If the answer is yes, then we know Lombok isn't the cause and that is something we really want to know.

**Comment by kdvolder** [comment]
So to clarify a bit. I do not want to tell you whether you should or should not use lombok. And I agree that we should strive for STS to work well with and without it. But in the process of trying to 'trouble-shoot' we want to determine whether Lombok is part of the problem or not.

**Comment by bismoy2013** [comment]
Sure @kdvolder I will try to enable log and see if I find something, then post in this thread .

**Comment by bismoy2013** [comment]
Please check log files on http://bit.ly/2WcEX1M . Just now faced similar problem where STS wasn't responding and I had to "Force Quit" . Hope this helps

**Comment by kdvolder** [comment]
@bismoy2013 Not sure what to do with that log file. Is this some kind of os-level stacktrace? That's not what we need for STS. It is more interesting to get stackdumps produced by the JVM. There are CLI tools that come with JVM/JRE that are called `jstack` and `jps` that you can use to get these kinds of stackdumps. 

It would be interesting to see a stackdump like that when the JVM is 'stuck'. Also if you have enabled UIResponsiveness monitoring as suggested, then similar stacktraces should have been written automatically into the Eclipse error log. You can find the Eclipse error log by opening it from inside Eclipse with the view 'Error Log' view. (Windows >> Show View >> Other >> Error Log).

These stackdumps may provide a 'smoking gun' pointing at some specific STS or Eclipse component that is blocking the UI thread (which causes the hang / unresponsive behavior). So those stacktraces could be very useful in determining the cause.

**Comment by bismoy2013** [comment]
Never mind, thanks for the help. Switched to Intellij today . Tough decision but better go with something stable .

**Comment by martinlippert** [comment]
@bismoy2013 It would be really helpful if you could try to remove Lombok from your STS ini file to double check whether the issues within the Java editor are related to that. It sounds very similar to previous issues that the combination of Lombok and Eclipse caused (and got fixed), so verifying that would be quite useful. If the Lombok integration is the root cause for the Java editor issues, I would suggest to submit that as a bug report to Lombok (https://github.com/rzwitserloot/lombok/issues).

Since the Lombok integration into Eclipse is a bit tricky and modifies pieces of the Java tooling code inside of Eclipse, it is also very tightly coupled to specific versions of Eclipse. In that case, a solution might be to run STS4 in a slightly older Eclipse version (we could provide you with those download links) for which the Lombok integration works.

**Comment by bismoy2013** [comment]
Sure thing @martinlippert , please do send in the download link. Hope you guys would give a thought on improving future versions of STS keeping lombok in mind . Great tool, STS , I would love to see it stand out in future .

**Comment by kdvolder** [comment]
> Hope you guys would give a thought on improving future versions of STS keeping lombok in mind

I'm not sure there is much that we can do really. Because of how Lombok works it is somewhat fragile and susceptible to breaking on newer Eclipse releases. The best we can do is report problems to them if we find problems caused by Lombok.

However, and in all fairness, for the problem that you rjust eported we don't know that Lombok is the cause of the problem here. It could be, or it could not be. Without your help to get the stacktraces and/or try out whether a setup without Lombok  to see if that helps, we have no real idea what is causing the problems for you and no real option to try and get it fixed.

But of course, the choice on whether that is worth your time is up to you. And we appreciate you at least tried to come this far in reporting what you already have.

**Comment by martinlippert** [comment]
> Sure thing @martinlippert , please do send in the download link. Hope you guys would give a thought on improving future versions of STS keeping lombok in mind . Great tool, STS , I would love to see it stand out in future .

If you want to, feel free to give this version a try, it is based on Eclipse 4.13 (2019-06), so maybe a higher chance to get the Lombok integration to behave nicer:

https://download.springsource.com/release/STS4/4.5.1.RELEASE/dist/e4.13/spring-tool-suite-4-4.5.1.RELEASE-e4.13.0-macosx.cocoa.x86_64.dmg

**Comment by bismoy2013** [comment]
@martinlippert thanks !

**Comment by bismoy2013** [comment]
@martinlippert  pls check the logs in your email , do not want to share here in public, I can confirm it's not a lombok issue , tried checking a method's implementation by doing (Cmd+Click) on method name, immediately STS froze and no lombok is added so far !

**Comment by martinlippert** [comment]
@bismoy2013 Thanks a lot for checking and for the logs, I will look into them. With "no lombok is added so far" you mean that you haven't added Lombok to your Spring Tools 4 IDE installation, correct, so that the ini file is still unmodified, right? Just wanted to double check on this.

In addition to that, can you provide a few steps, starting from an empty workspace, how to freeze the IDE from there? Does it happen every time you do the "Cmd+Click" action to navigate to a method implementation? Even on an empty workspace and a brand-new simple project?

I can already see a few UI monitoring freeze traces in the log file that you sent me (many many thanks for that again), but would love to reproduce this locally on my machine, too.

Thanks again for your help with this, very much appreciated.

**Comment by bismoy2013** [comment]
> With "no lombok is added so far" you mean that you haven't added Lombok to your Spring Tools 4 IDE installation, correct

Yes @martinlippert , that's correct .

> Does it happen every time you do the "Cmd+Click" action to navigate to a method implementation?

It's more like a sudden behavior rather than every time. Let's just 40% of the time it's like that if not all the time. Brand new or old projects, not sure how to respond to this part , let's just say irrespective of project's age .

> I can already see a few UI monitoring freeze traces in the log file

Yeah probably the past logs were also being appended , last time when you guys were asking me for the logs, I didn't know that I was supposed to check in .log folder which is normally a hidden folder within the STS folder , therefore I wasn't able to communicate clearly.

**Comment by kdvolder** [comment]
> I can already see a few UI monitoring freeze traces in the log file that you sent me (many many thanks for that again), but would love to reproduce this locally on my machine, too.

I think it would be nice to have these particular stacktraces shared more publically, (if @bismoy2013 is okay with that). If not I very much would like to see them for myself, so if someone can share them with me please.

I think in light of the additional info that seems to be available now, we should re-open this ticket.

**Comment by bismoy2013** [comment]
@kdvolder I do not have your email, hence couldn't send across, sent only to @martinlippert for time being

**Comment by kdvolder** [comment]
@bismoy2013 But I assume from that statement that you are okay if Martin shared it with me? Or you can just send them personally to my email as well "kdevolder AT pivotal.io". Thanks in advance.

**Comment by bismoy2013** [comment]
Emailed just now @kdvolder .

**Comment by ReddeppaKollu** [comment]
i am facing the same issue with 4.5 version, it always freezing Editor , and show sending classpath notifications.

-startup
plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1100.v20190907-0426
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms2056m
-Xmx4024m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM

really annoying , i can not even type single line of code, it hangs for few sec, and then opens for editing again.

**Comment by martinlippert** [comment]
@ReddeppaKollu It would be awesome if you could capture a thread dump of the IDE process while it is freezing (using jps and jstack) and attach it here.

As a workaround, you could also try to disable the Spring Boot language server in the preferences, just to see if this helps or not.

**Comment by kdvolder** [comment]
@ReddeppaKollu Also please consider 'UI REsponsiveness Monitoring' in the preferences. You can find it here: "Window >> Preferences >> General >> UI REsponsiveness monitoring". This will automatically collect stacktraces during moments of ui freezes and put them in the Eclipse error log. If you could then share some of those collected traces that would be useful. Using jps and jstack can be a bit tricky if the ui only freezes for a second or two, you will usually be too slow to do what is required to capture a stacktrace. So the UI responsiveness monitoring really helps there to catch interesting traces at the right moment.

BTW: I did take a look at the logs @bismoy2013 sent to me. It doesn't seem conclusive yet to me, the strongest pattern thatt I saw in them was short freezes of about 700ms to a 1s on actions like 'organize imports' seemingly hung on calls to JDT for getting an AST. In all these traces I did not yet see anything that seemed STS specific.

**Comment by humphreygao** [comment]
I suggest not to use `Ctrl/CMD + Click` to Open Declaration and Implementation. Use `F3`(Open Declaration) and `Ctrl/CMD + T`(Open Hierarchy) as a workaround.
This problem should be reported to Eclipse Bugzilla, and I find a recent one [UI freezing when Open Implementations](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560857).

**Comment by ReddeppaKollu** [comment]
i have machine with 1 TB SSD, 32 GB RAM,  with STS 4.5 it keep my CPU always 90+, causing entire machine slow,  consuming lot of resources, totally weird , i am trying above recommended options and let see if these helps, if not will use other Eclipses with Spring plugins.

**Comment by ReddeppaKollu** [comment]
[.bak_0.log](https://github.com/spring-projects/sts4/files/4364403/default.bak_0.log)
uploaded first file generated

**Comment by martinlippert** [comment]
@ReddeppaKollu One thing that I noticed from looking at the logs is:

```
!ENTRY org.eclipse.lsp4e 4 0 2020-03-21 17:41:49.430
!MESSAGE java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.hover(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
!STACK 0
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.hover(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.springframework.tooling.boot.ls.jdt.LSPTextHover.getHoverInfo(LSPTextHover.java:109)
	at org.springframework.tooling.boot.ls.jdt.SpringBootJavaHoverProvider.getHoverInfo2(SpringBootJavaHoverProvider.java:42)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:165)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:132)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
Caused by: java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.hover(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
	at org.springframework.tooling.boot.ls.jdt.LSPTextHover.lambda$11(LSPTextHover.java:237)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.springframework.tooling.boot.ls.jdt.LSPTextHover.lambda$10(LSPTextHover.java:246)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

The root cause of this is an updated Eclipse platform without the corresponding update of the Spring Tools 4 components. To solve this, I would strongly recommend to update to the just released Spring Tools 4 release 4.6.0, which should solve that issue.

Here is a related issue for that, which also offers a few more options how to trigger the update if it doesn't show up automatically: https://github.com/spring-projects/sts4/issues/423

In addition to that I am also seeing a number of timeout issues around language servers, so it definitely looks like something is going wrong in that space. I wonder if the update to the latest version makes a difference there. You also mentioned that you disabled the Spring Boot language server already. Did you disable that for all the associated content-types?

**Comment by ReddeppaKollu** [comment]
Updated to latest version 4.6, i feared, i can not even code now, its hitting always 100% system resources, something keep running in background , need to wait few secs type any word.

i can hear my system fan sound from 5 ft nows, and its running always since i open the STS.

i think performance got degraded bit more now. 
moving to plain eclipse, and importing STS plugin will do any help ??

**Comment by ReddeppaKollu** [comment]
how can i disable SendClasspathNotification process, i believe thats the culprit here, its always running.

**Comment by BoykoAlex** [comment]
Maybe it is the Spring Boot Language Server not working well for you.
You can disable Spring Boot Language Server via Preferences -> Language Servers and uncheck entries in the table where you see Spring Boot Language Server. Note that this would effectively disable many spring boot tooling features. Thus, this is essentially to confirm the the overall culprit of the issue.

Now, if performance improves with Spring Boot Language Server disabled it'd be good if you could find time to troubleshoot this performance issue for us. Enable the Spring Boot Language Server and also enable Spring Boot Language Server logging in the Eclipse console view via Preferences -> Language Servers -> Spring Language Servers and check-mark Spring Boot on the page. Now the log for the Spring Boot Language Server will show up in the Console view when the language server process is running. We'd be interested in seeing this log. In addition, it'd be great if you could download VisualVM (https://visualvm.github.io/download.html) and capture a CPU sampling snapshot of the Spring Boot Language Server process and attach the snapshot file here. (The CPU snapshot when the process consumes a lot of CPU). Thanks in advance!

**Comment by martinlippert** [comment]
@ReddeppaKollu Before disabling the Spring Boot Language Server, can you enable the log output of the language server to be streamed to the console view first? You can do that in the `Preferences -> Language Servers -> Spring Language Servers` and then check `Spring Boot Language`. That allows the log output of the language server to be streamed to the Console view.

Once you did that, can you capture a few log outputs from both the language server AND Eclipse and attach them here? Would be interesting to see what exactly is going wrong here.

Regarding your machine config: this should be way more than enough to run the IDE. Once you started up the IDE and ended up in this slow and freezing situation, could you fire up `jconsole` and attach that to the `spring-boot-language-server---` process to see what is going on there? Maybe that process is running out of memory for some reason. Not very likely, but I would like to verify that this is not the case over there. For the same purpose, the log output of the language server (streamed to the Console view) could also be very interesting.

**Comment by martinlippert** [comment]
After analyzing the provided log output, I also filed this bugs as a result:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=561372
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=561373

**Comment by martinlippert** [comment]
@bismoy2013 We found a major issue which might be well related to the issue that you describe here, especially the observation about the SendClasspathNotification job always running fits nicely to the problem that we identified and fixed. So if you want to give an early access version a try, it would be great to hear whether the situation improved for you, too. You could grab the latest CI build from here: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html.

**Comment by martinlippert** [comment]
@ReddeppaKollu please see the comment from above and, if possible, feel free to give the nightly build a try.

**Comment by bismoy2013** [comment]
@martinlippert thanks & sorry for the delay in response, was away , away from engineering world. Strangely STS is not stuck like before now , so yeah cool . Stay safe and take care , thanks for the effort , STS is close to my heart, hence I was more disappointed when it was getting stuck during that period .

**Comment by martinlippert** [comment]
@bismoy2013 Thanks for coming back to this and glad to hear it is working again smoothly on your end. Good news!!! :-) Let us know if anything else comes up.
