### ISSUE TITLE
Spring yaml validation doesn't understand the "<<:" syntax

### ISSUE THREAD

**Issue by youngm** [spring-projects/sts4#420]
I'd like to use yaml anchor references in my code.  The editor appears to handle the `*` anchor perfectly.  But, doesn't appear to know how to handle the `<<:` operator.  Test case:

```
@ConfigurationProperties(prefix = "config")
public class ConfigProperties {
  private String dude;
  private String bob;

  public String getBob() {
    return bob;
  }

  public void setBob(String bob) {
    this.bob = bob;
  }

  public String getDude() {
    return dude;
  }

  public void setDude(String dude) {
    this.dude = dude;
  }
}
```
Sample Yaml:
```
configref: &config
  bob: bob
  asdf: dude
config:
  <<: *config
```
In STS 4.5.1 there are 2 problems with this:
* First I get a warning in the `<<:` line "Unknown Property 'config.<<'.  This should not produce a warning.
* Second I do not get a warning on line `asdf:`.  But I should because config: doesn't have an `asdf` property.  The warning should be "Unknown Property 'config.asdf'.

Everything seems to work perfectly when using normal `*` references.  We just need it to work with `<<:` also.  Here is an example of it working perfectly with `*`.
```
configref: &config
  bob: bob
  asdf: dude
config: *config
```

**Comment by kdvolder** [comment]
I recall already implementing support for this sort of thing for the cf editor. So it should be too hard to get something similar working for the application.yml editor as well.

Found this test case which shows that this works for the cf editor:
https://github.com/spring-projects/sts4/blob/master/headless-services/manifest-yaml-language-server/src/test/java/org/springframework/ide/vscode/manifest/yaml/ManifestYamlEditorTest.java#L197

This is a good starting point to look / explore and reconstruct how it was done there.

**Comment by kdvolder** [comment]
If I recall correctly the reason this works already for `*` references is because the snakeyaml library we use to parse yaml already deals with this before we even get to see the yaml AST structure by 'inlining' these references. 

But for whatever reason this isn't the case for '<<' references. 

I also found the code that deals with this for the cf editor. The bulk of it is in this helper class:

https://github.com/spring-projects/sts4/blob/master/headless-services/commons/commons-yaml/src/main/java/org/springframework/ide/vscode/commons/yaml/ast/NodeMergeSupport.java

**Comment by kdvolder** [comment]
Fix pushed: https://github.com/spring-projects/sts4/commit/17af13e448d98747df2414fbcb9262f141a8e8a3

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

Verified in latest nightly build. Delivering.
