### ISSUE TITLE
about sts4's

### ISSUE THREAD

**Issue by smile8-d** [spring-projects/sts4#426]
I am just learn springmvc, but sts4 haven't springConfigEditor, that is not friendly.
so,I hope springConfigEditor can come back.

**Comment by martinlippert** [comment]
@smile8-d The Spring Config Editor in Spring Tool Suite 3 was designed for Spring XML config files and was not really specific for Spring MVC. In case you start to learn about Spring and Spring MVC, I would strongly recommend to start with Spring Boot (nowadays) instead of XML-based configurations.

Which feature of the Spring Config editor are you missing exactly?

**Comment by smile8-d** [comment]
oh , thanks a lot

**Comment by smile8-d** [comment]
if you can , let the xml config editor come back?( auto create spring namespace )
that editor maybe  use in some times.

**Comment by martinlippert** [comment]
We have some limited support for Spring XML config files in Spring Tools 4 already (e.g. https://github.com/spring-projects/sts4/issues/417), so the question would really be which features you are missing the most. Is it adding Spring namespaces to an existing Spring XML config file? I could imagine having nice content-assist support for that in the XML file, too. What do you think? Anything else?

**Comment by smile8-d** [comment]
@martinlippert thanks you answer , I will keep focus on sts4
