### ISSUE TITLE
org.eclipse.mylyn.wikitext.markdown required to update to 4.6.0?

### ISSUE THREAD

**Issue by mauromol** [spring-projects/sts4#429]
Today I tried to update my STS 4.5.0 installation (on top of Eclipse) to 4.6.0.
I did a "Check for updates", kept all the STS4-related bundles checked, then hit "Finish".
The following dialog appears:

![immagine](https://user-images.githubusercontent.com/1742494/77448894-9d30fa00-6df1-11ea-8538-3df847a45b04.png)

Why is this plugin needed? And why isn't it signed?

**Comment by martinlippert** [comment]
This plugin is required by the org.eclipse.lsp4e plugin, which is coming from Eclipse and takes care to integrate language servers into the Eclipse IDE. The reason why this isn't signed is probably due to the fact that we included a slightly more up-to-date version of this plugin on our product update site to allow a smooth installation into older Eclipse versions. I will go ahead and look out for a signed version of that to be included in future versions of Spring Tools 4.

**Comment by martinlippert** [comment]
This is done now for the next release, includes Mylyn Docs markdown version 3.0.36 instead of 3.0.37 to get signed version on board. Closing this for now.
