### ISSUE TITLE
Debugger ignores spring boot application.properties

### ISSUE THREAD

**Issue by Matthew-Dong** [spring-projects/sts4#43]
Greetings,

Need you knowledge to help address the issue raised in VSCode Java Debugger Extension. Could you share some thoughts about the fix? 

https://github.com/Microsoft/vscode-java-debug/issues/157

Thanks!

**Comment by kdvolder** [comment]
The application.poperties are loaded from the classpath. So this is most likely a classpath problem. Here are some things to check:

1. is `application.properties` (and other files in `src/main/resources`) copied to output folder (as Eclipse does with non .java files in source folders when doing a project build)

2. do these copied resources in output folder get added to the runtime classpath when launching the debugger?

These are just thoughts of the top of my head. I will try later on to reproduce the issue and try and see what's actually going on.

**Comment by kdvolder** [comment]
I've diagnosed the problem and added my findings to the original bug report.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I think there is really nothing we did to fix this, right? Therefore accepting this for the comments on that vscode-java-debug issue.

**Comment by kdvolder** [comment]
> I think there is really nothing we did to fix this, right?

Correct. I don't think there is anything we can do on our end. The problem is more of a issue with the jboss redhat language server maven support.

My interpretation of this ticket was that @Matthew-Dong wanted some help diagnosing the problem, (which I was happy to do) and so I think the comments I left explaining what I think is going on resolves this ticket for us.
