### ISSUE TITLE
Can't start a Springboot application when the dependencies jars are too many.

### ISSUE THREAD

**Issue by shawnliu1979** [spring-projects/sts4#433]
When I create the spring boot project as a sample , It's fine to start.
But when I add several jar in the [build.gradle], then The error of application start class is not be found is show up.

After my research,
 I found the Reason.
OK-CASE:  In the normal project's run configuration, 
click the [show Command Line],   -classpath is inline mode.
FAIL-CASE: but In the NG project's run configuration,
click the [show Command Line],   -classpath is short to a temp file.

X:\xxxxx\javaw.exe -Dfile.encoding=UTF-8 **"@X:\XXXX\java2_sample\.temp-New_configuration-classpath-arg-1585559234921.txt"** com.example.demo.JavaSampleApplication

in the temp file: -classpath "X:\XXXX\java2_sample\bin\main;;XXX.jar;..........."
I have do the compare that the both classpath in the inline mode or temp file that is same.

Here is my question:
Why in the short mode classpath configuration , can't find the application start class.
THX a lot.
(my sts version is sts-4.5.1.)

**Comment by kdvolder** [comment]
I think this is known bug in Eclipse on Windows. I have seen reports about it before and beleave it is fixed. Trying to find again the specific tickets with the details.

**Comment by kdvolder** [comment]
Here are the other tickets I mentioned above:

- https://github.com/spring-projects/sts4/issues/407
- https://github.com/spring-projects/sts4/issues/406
- https://github.com/spring-projects/spring-ide/issues/406
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=558495

A lot of posts to sift through. Here's a summary of the most important info:

- Eclipse bug affects windows-based Java launches on Java 9 or above, for projects with large number of dependencies
- was fixed in Eclipse 4.15.

> (my sts version is sts-4.5.1.)

Can you check what version of Eclipse your STS setup is based on? You can find about using the 'About STS/Eclipse' item in the 'Help' menu. Open that, then click on the 'Eclipse' icon in the row of icons near the bottom of the dialog. Look at the 'Feature' called 'Eclipse Plafform' in the table that appears. What version does it show there.

If you are not on Eclipse 4.15, consider upgrading. f you are already on Eclipse 4.15 then maybe this is a different problem and we should dig deeper. 

I am going to assume for now that this is the same problem as in the other tickets. So I am closing this ticket. Of course you can still post here with more questions and info, and we can always re-open it again if needed.

**Comment by shawnliu1979** [comment]
@kdvolder 
Thank you very much .
It's very helpful.
