### ISSUE TITLE
No Property Completion using @ConfigurationProperties

### ISSUE THREAD

**Issue by hanct** [spring-projects/sts4#458]
vscode version: 1.44.2
Spring Boot Tools extensions:1.17.0

Hi, I am currently using @ConfigurationProperties from spring boot. Despite that my gradle has generated build folder containing spring-configuration-metadata.json (located at build\classes\java\main\META-INF)  in it, I am still not able to get any property completion in the properties file.

below is the content of my spring-configuration-metadata.json 
```
{
  "groups": [
    {
      "name": "otp",
      "type": "com.apress.demo.MyAppProperties",
      "sourceType": "com.apress.demo.MyAppProperties"
    }
  ],
  "properties": [
    {
      "name": "otp.enabled",
      "type": "java.lang.String",
      "sourceType": "com.apress.demo.MyAppProperties"
    }
  ],
  "hints": []
}
```

Am I missing anything?

**Comment by kdvolder** [comment]
> located at build\classes\java\main\META-INF

I think that is the problem here. This 'build' folder is where a gradle commandline build produces its output. However, this is separate from Eclipse's build path. Eclipse produces output instead into the `bin` folder.

We can see that when open a typical Spring boot gradle project's .classpath file:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```

Not sure if there is much we can do about it or even if we should. My take on it is that this is probably something for BuildShip to fix. BuildShip would need to integrate somehow with Eclipse JDT APT (APT = Annotation Processing Tool) and JDT APT to execute the spring boot annotation processor to be executed as part of the Eclipse build. If the configuraton metadata is produced in an output folder that is part of the Eclipse buildpath, then STS will pick up on the file and parse it. Right now it doesn't because the file, while it may exist, is not actually on the Eclipse buildpath so our tooling doesn't consider it as relevant.

The issue around of intergeating annotatoion processor with BuildShip is a long standing one. You can find it here: https://github.com/eclipse/buildship/issues/329

I'm going to close this issue as I don't think it is an STS issue.
