### ISSUE TITLE
update to latest version error 

### ISSUE THREAD

**Issue by user20161119** [spring-projects/sts4#462]
try to update to latest version get following error 

![image](https://user-images.githubusercontent.com/123967/81494303-69932c00-92da-11ea-9015-8fede77020f5.png)

![image](https://user-images.githubusercontent.com/123967/81494311-76b01b00-92da-11ea-9847-17c719043fbb.png)

**Comment by martinlippert** [comment]
In most of the cases, this error message goes back to stale cache data in your Eclipse/STS installation that you can solve my either pressing "Reload" for the affected update sites in the `Preferences -> Install/Update -> Available Update Sites` preference page or by exporting all those available update sites (using the same preference dialog) to a file, delete them in Eclipse/STS, restart Eclipse/STS, and re-import them again.

In addition to that I am not sure which update site is affected here, since a regular STS 4.6.0 to 4.6.1 update wouldn't cause those Mylyn components to be updated, so there must be an additional update site around that triggers this.

Let's see first if the above mentioned solution works for you. If not, we can dive into more details. In that case it would be good if you could share the exact update message (which features will be updated) from the update dialog here with us. Might reveal some interesting additional information.

**Comment by user20161119** [comment]
thanks
1. reload update site not work,get the same error
2. export update sites,import ,upgrade success

thanks

**Comment by martinlippert** [comment]
@user20161119 good to hear that the workaround helped, thanks for letting us know.
