### ISSUE TITLE
sts displays log cannot be resolved

### ISSUE THREAD

**Issue by wusongdashu** [spring-projects/sts4#463]
The sts importing tx-lcn server java code  displays that log cannot be resolved

**Comment by wusongdashu** [comment]
![BaiduShurufa_2020-5-18_14-35-16](https://user-images.githubusercontent.com/64955200/82181329-e5155e80-9914-11ea-9122-ead14d930eaa.png)

**Comment by wusongdashu** [comment]
Through online search, I found a solution. Although the problem was solved, I didn't feel very good.

解决方式就是在eclipse中安装lombok插件。

1.前往官网下载：https://projectlombok.org/download  lombok.jar 

2.打开lombok.jar所在目录，在资源管理器地址栏输入cmd

3.在打开的cmd窗口中输入java -jar lombok.jar（当然这一步的基础是jdk装好了 并且配置好了环境变量）

4.在弹出的安装界面里点击左下角的Specify location…按钮 选择eclipse安装目录里的eclipse.exe

5.点击右下角的Install/Update按钮进行安装

6.安装成功之后点击右下角的Quit Installer就好了。

7.其实这个安装就是做了下面几个步骤：

把这个jar包拷贝到与eclipse.exe同路径下。
修改eclipse.ini文件 追加-javaagent:D:\jee-2018-12\eclipse\lombok.jar(lombok.jar的绝对路径！)
8.重启eclipse 然后clean一下项目 错误就消失啦！

**Comment by wusongdashu** [comment]
![BaiduShurufa_2020-道达尔5-18_20-57-27](https://user-images.githubusercontent.com/64955200/82215585-3a1f9780-994a-11ea-8177-bbcef976c79e.png)

**Comment by wusongdashu** [comment]
![BaiduShurufa_2020-道达尔5-18_20-57-27](https://user-images.githubusercontent.com/64955200/82215631-4f94c180-994a-11ea-99dd-ede3796a3be9.png)
but in the idea  this is  not  problem, please update  quickly

please
--



![image](https://user-images.githubusercontent.com/64955200/82215673-5d4a4700-994a-11ea-8b8f-a6486d050158.png)

**Comment by kdvolder** [comment]
I don't understand Chinese, but I guess the problem was that you need to install Lombok as your project uses it.

I don't think we are going to include Lombok by default in STS. This is not something that everyone needs. Also Lombok on occasion causes problems because of conflicts with other plugins in Eclipse, including Eclipse JDT. Users who don't use Lombok are also affected by these problems. So this is why Lombok should probably remain something that users who actually want to use that install by themselves.

**Comment by wusongdashu** [comment]
Whether to improve the component dependency related to Lombok or not, ieda has no problem, but STS reports an error

**Comment by kdvolder** [comment]
> idea has no problem

I understand that. But I think our only option here to 'fix' this is to include Lombok by default in STS. This is not something we want to do because it sometimes causes problems even for users who don't need Lombok. Therefore, if you need Lombok you will have to install it yourself. We do understand it is not ideal but neither is having it pre-installed so its basically a choice between:

- making things easier for lombok users and potentially causing problems for others
- avoiding potential problems for non-lombok users and making this somewhat harder for lombok users.

Neither are great choices. The conservative choice is to not include lombok.

**Comment by wusongdashu** [comment]
I don't know if the idea already contains the Lombok component. Can we improve the existing components to avoid error reporting?

**Comment by kdvolder** [comment]
>  Can we improve the existing components to avoid error reporting?

I don't think that is possible. Without lombok the Java code using lombok annotations simply cannot be compiled by the Java compiler because it is 'incomplete'. 

Lombok is a kind of code generation tool that uses annotations. So Lombok generates a lot of boilerplate code that you would otherwise have to write yourself. This is quite nice really. But basically, without lombok that extra code is not being generated and if your project relies on it then it simply won't be able to compile and run.
