### ISSUE TITLE
Code completion problem

### ISSUE THREAD

**Issue by humphreygao** [spring-projects/sts4#487]
See [code completion problem in Eclipse IDE](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564305). This problem is hard to reproduce in Eclipse IDE 2020-06, but can be reproduced in STS4 4.7.0.

**Comment by martinlippert** [comment]
I tried to reproduce this bug and it looks pretty consistent to me and the analysis on the Eclipse bug looks quite precise. If you have the preference enabled to automatically insert common prefixes (as described in comment #3 here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=564305#c3), the behavior that is described in the bug can be reproduced reliably in Spring Tools 4 for Eclipse 4.7.0 as well as Eclipse 2020-06. If you disable that preference, the content-assist behaves correctly across the board.

Therefore I recommend to follow the mentioned bug at Eclipse and disable the preference to automatically insert the common prefix until the bug gets fixed in Eclipse JDT.
