### ISSUE TITLE
Ctrl+Alt+T shortcut doesn't work with more then 2 projects at a time

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#489]
I am on the latest 4.7.0.RELEASE. I have 6 projects in my workspace (5 are maven, 1 is gradle if that matters). Windows 10 x64 Pro.

I have noticed that the Ctrl+Alt+T keyboard shortcut (Show In Local Terminal) only works on TWO projects at a time. I.e. I have Prj1..6.  If I do Ctrl+Alt+T on 1&2, the shortcut no longer works until I close one of them. It is not specific to 1&2. I can do 4&5, 3&1, etc. Any two of them.

The long path, right click and going through the menus works with all 6.

**Comment by kdvolder** [comment]
The terminal is an Eclipse component, I'm not actually 100% sure which part of Eclipse it actually comes from. I think it is probably the 'Terminal' component which is part of 'CDT'.

In any case I'm pretty sure though this is a bug that should be filed against Eclipse itself rather than STS. This component is not STS specific. I suggest reporting against CDT and select 'Terminal' component:

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=CDT

Also, I'm not totally sure what the problem is and cannot reproduce it. 

I have three projects open in my workspace and the shortcut still seems to work fine.
Well.... fine is relative. I select more than one project but only one terminal opens up. I guess the action only really takes the first element of a muti-selection as its 'input'. Arguably that's somewhat illogical. Be that as it may, you seem to be describing something different where the shortcut simply doesn't work at all unless you close projects? This doesn't seem to happen for me.

Anyway, if you want to raise the bug against Eclipse, try filing it against CDT (Terminal component):

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=CDT

**Comment by kdvolder** [comment]
Sorry.... actually my method of trying to reproduce may not actually be reproducing it. I think when I press CTRL-ALT-T on my machine running Ubuntu, it is Ubuntu who intercepts the keyboard shortcut and it opens a OS-level terminal totally independent of Eclipse. So basically the keyboard shortcut is completely hidden / inaccessible for me. Which means I have not *really* tried it at all. I just thought that I did.

Anyhow, problems with the behavior of this Shortcut such as you desribe them should still be reported against  Eclipse rather than STS.

**Comment by SledgeHammer01** [comment]
> Sorry.... actually my method of trying to reproduce may not actually be reproducing it. I think when I press CTRL-ALT-T on my machine running Ubuntu, it is Ubuntu who intercepts the keyboard shortcut and it opens a OS-level terminal totally independent of Eclipse. So basically the keyboard shortcut is completely hidden / inaccessible for me. Which means I have not _really_ tried it at all. I just thought that I did.
> 
> Anyhow, problems with the behavior of this Shortcut such as you desribe them should still be reported against Eclipse rather than STS.

Yeah, I'm using the embedded one for maven commands. Eclipse bugs have a disclaimer where they expose all your info email/name lol. Guess I'll have to set up an anonimized email lol.

Basically the repro for me is Select Prj 1, Ctrl+Alt+T, works. Select Prj 2, Ctrl+Alt+T works, select Prj 3, Ctrl+Alt+T doesn't open. If I close either of the terminal windows, then Ctrl+Alt+T starts working again. I didn't mean I have to close the entire project or workspace.
