### ISSUE TITLE
Missing Natures to Support Projects

### ISSUE THREAD

**Issue by ateebkhawaja** [spring-projects/sts4#49]
On importing a fresh project, I get the a popup with the message:

> Your IDE is missing natures to properly support your projects.
> Some extensions on the eclipse marketplace can be installed to support those natures.

Clicking on show solution opens the eclipse marketplace and shows Spring Tool Suite 3.9.3 plugin for installation.

In Problems, the following warning shows up:
Description	Resource	Path	Location	
Type Unknown referenced nature: org.springframework.ide.eclipse.core.springnature.	
.project	/PROJECT_NAME	Unknown	Unknown nature

I imported the project cleanly. Only items in the project were src and .git folder and pom file.

**Comment by martinlippert** [comment]
It looks like the project that you imported already had a `.project` file around that contained the spring nature definition from the STS 3 tooling. That nature is connected to the STS 3.9.x plugins on the marketplace, so that people can easily get the plugins installed that were used for the project in the past.

In case you don't want that, you can/should delete the old spring nature from the project metadata (you can also do that via the properties UI of the project). And you can skip the install of the STS 3.9.x plugins from the marketplace in case you want to continue to use pure STS4.

Hope this helps and explains the behavior.
