### ISSUE TITLE
sts4.7.0 SLF4J warning messages

### ISSUE THREAD

**Issue by mrchulho** [spring-projects/sts4#492]
Spring Tool Suite 4 
Version: 4.7.0.RELEASE
Build Id: 202006181331

It shows the following warning messages.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Applications/SpringToolSuite4.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.16.0.20200610-1735/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/Applications/SpringToolSuite4.app/Contents/Eclipse/configuration/org.eclipse.osgi/5/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]

Please advise.
Thanks,

**Comment by kdvolder** [comment]
> It shows the following warning messages.

For context as to where this message is coming from... *where* and *when* do you see this message? Is this in the eclipse error log? Or in the output console for maven? Or in the output console of your own app when you run it?

As to the nature of the error, I would assume it is mostly harmless. Slf4j logging framework is warning that it found more than one logger implementation and just picked one of them.

**Comment by mrchulho** [comment]
The sts4.7 console view shows this message when Run As > Maven install on a maven project. It seems just warning.
Thanks,

**Comment by kdvolder** [comment]
> Run As > Maven install on a maven project

In that case it would be interesting to check if you also get this warning when you run `mvn instal` outside of Eclipse from a OS terminal. l would guess the answer is yes, and I beleave that means the problem is due to the project itself (some diplication of logger dependencies on the classpath of the project), so its not a problem with the IDE.

If you do not get the same warning then it points at a possible issue with Eclipse maven tooling instead. And in that case I'd recommend filing a ticket on Eclipse bugzilla: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=m2e

**Comment by martinlippert** [comment]
I can reproduce this warning message with a simple Rest Service example in STS 4.7.0 as well as Eclipse 2020-06 and it looks to me like this is caused by the way m2e configures the embedded maven runtime when executing the maven command. I don't think this warning causes any harm, but I would recommend to file this as a bug against m2e, as mentioned above, via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=m2e

**Comment by kanakarraajj** [comment]
I am using STS4.8 in Windows 10 64 bit. Faced same Issue and in STS - updated Apache Maven installation folder in Preferences -> Maven-> Installations -> D:\Maven3.XXX\ ,
Then maven clean project and maven install... errors/wanings were done.
Note: Uncheck STS Maven and Check Local Maven for use
