### ISSUE TITLE
Existing "Run as Spring Boot" launches not working correctly anymore after upgrade to 4.7.0

### ISSUE THREAD

**Issue by bmaehr** [spring-projects/sts4#496]
I had a lot of spring boot launches I used to start the different spring boot applications. After the upgrade to 4.7.0  suddenly these launches didn't run the spring boot applications anymore like expected (Missing console output, missing log files, wrong profiles,...)

I found out the the reason was in a changed behavior of the checkbox 'Exclude test code" . In the existing launch configurations there was no setting for this. It seams that until 4.6.1 then the test code was not included (even if the checkbox was shown unchecked) and beginning with 4.7.0 it is necessary to check the checkbox.

**Comment by bmaehr** [comment]
#486

**Comment by kdvolder** [comment]
Glad you figured this out. For some background... 

We also noticed this 'breakage'. I beleave it is due to a change in behavior between Eclipse 4.15 and 4.16 in maven tooling. As you noticed the 'Exclude test code' checkbox didn't need to be checked before and test code was still being excluded anyway. However now unless the box is checked test code is no longer excluded. To address this problem, (it is a problem since typically people do not want the test code on the classpath when running a boot project), we changed STS to automatically check this by default. The caveat unfortunately is that this default value is only set on newly created launch configs. So if you have an older workspace that has a lot of older launch configs (sounds like that is your cae), you will be hitting this problem. You can either delete your old launch configs and recreate them or simply manually check the box.

**Comment by martinlippert** [comment]
@kdvolder Is there a way to internally identify whether the launch config is an old one or a new one with the checkbox not being checked? If there is a way to distinguish then, we should somehow set the checkbox to checked for those old launch configs to avoid further confusion for our users. Do you see a way to make that work?

**Comment by bmaehr** [comment]
@kdvolder In my case the setting was missing in the launch file. I think that could be used to distinguish the cases.

**Comment by bmaehr** [comment]
In fact the main problem was not to fix it. The main problem was to find what was causing it. Because I don't run these apps every day so there was a time gap between the update and recognizing the problem. And if you find an unexpected behaviour you first think about a configuration change in your application in the commints done during the last days or a changed dependency and not the update of your development environment you did two days ago.

**Comment by kdvolder** [comment]
> Do you see a way to make that work?

There's always a way. But I'm not sure it is worth the complexity it brings.

I.m.o if we were going to do this, It might have been worth doing prior to releasing STS for Eclipse 4.16. At this point, with STS already released, it is kind of too late really. Sure, we can do this for next release of STS, but by this time... most people who are going to be affected by the problem will have already hit it and dealt with it somehow.  So I don't think it is wort adding special logic to try and scan workspace for old launch configs to fix. Fix like these are somewhat messy and have themselves the potential to misbehave as well (i.e. accidentally 'fixing' things that it shouldn't touch).

**Comment by martinlippert** [comment]
@kdvolder I agree that this should have been fixed alongside the update to Eclipse 2020-06. But I also think that there is definitely still value in improving the situation for all the launch configs that people haven't used since updating to the latest version - I am sure that would help many of our users.

Thinking about a solution I don't like the "scan everything at startup" approach very much. I would prefer a solution that automatically adds the "check the checkbox" setting as soon as a launch config is used - and only in case we can differentiate between a launch config that doesn't have the checkbox checked because it is old (created pre-2020-06-Eclipse) and a launch config that doesn't have the checkbox checked but got created post-2020-06-Eclipse (so the user might have unchecked it manually). Can we differentiate those two cases by looking at a launch config?

**Comment by kdvolder** [comment]
> Can we differentiate those two cases by looking at a launch config?

Not sure, but if not we can add another attribute to mark a fixed config as 'we already fixed this one'.

I still don't think it is worth the trouble now, as it is a bit of a case of closing the barn doors after the horse already left.

Anyhow, I don't feel very strongly about it so I'll have a look at implementing it.

**Comment by kdvolder** [comment]
Pushed a fix. It was actually rather easy to 'recognize' old launch configs. As @bmaehr mentioned:

> In my case the setting was missing in the launch file. I think that could be used to distinguish the cases.

Indeed! That was a very good hint! So I just added a check to see if the attribute is missing, and if so, we set it to true. It it already exists, then we leave it alone.

See: https://github.com/spring-projects/spring-ide/commit/183eba55fe3923aa0708802e6d5a6c7e982bf258
