### ISSUE TITLE
While processing maven update the Deployment Assembly  of the project has been resets

### ISSUE THREAD

**Issue by nandakumardtc** [spring-projects/sts4#504]
1) While processing maven update the Deployment Assembly of the project has been resets. Again we need to add it by  clicking on add button.
2) manly when processing maven update the java build path entries are removed automatically from deployment assembly
3) on previous version (sts v4.6.2-release) it was not happened.

Am currently getting this from the sts v4.7-release and Build Id: 202006181331 on windows 10 pro 2004 os bulid 19041.388

**Comment by kdvolder** [comment]
I suspect this is probably not an STS specific problem but something related to m2e or possibly a WTP component that integrates with m2e. It would be good if you can try if a 'vanilla' "Eclipse IDE for Enterprise Java Developers" (can download it here: https://www.eclipse.org/downloads/packages/) has the same problem.

I would offer to do some trouble-shooting and try to reproduce the problem myself, but there is just not enough information in your description for me to guess what I need to do to reproduce this problem. I can give it a try but you will need to provide more info such as:

- a sample project that I can import
- precise instructions on how to import it into Eclipse (to reproduce something in a state as similar as possible to your setup)
- exact set of steps to take to add the deployment assembly (i.e. what button is that I need to click??)
- what exactly to do to make the problem happen and description of expected versus desired behavior

**Comment by nandakumardtc** [comment]
Yes you are correct the same issue is on the "Eclipse IDE for Enterprise Java Developers", it maybe my project is dependent on another maven project while opening the dependent project the deployment assembly of main project get resets. i think the problem is due to the maven build. Because i created a sample project to show you the problem. but the sample project deployment assembly is not getting resets. I don't know exactly the problem is with my project or not

**Comment by kdvolder** [comment]
> the same issue is on the "Eclipse IDE for Enterprise Java Developers"

In that case then it is a problem with Eclipse rather than STS and should be reported as an Eclipse bug on Eclipse bugzilla. It sounds like it's probably a problem related to m2e integration with WTP.  So I'd file it with that component:

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=M2E-WTP

To help the Eclipse developers diagnose and fix the problem you will need to provide some instructions on how to reproduce the problem though. You can of course always file a bug with whatever information you can provide, but unless they can diagnose and reproduce your issue it will be next to impossible to fix it.

I'll close this ticket now, as it doesn't seem to be a problem with STS itself. If you file a bug with Eclipse please provide a link here so we can also monitor the issue.
