### ISSUE TITLE
CSS Autocomplete not working in STS 4.7

### ISSUE THREAD

**Issue by jagansankara** [spring-projects/sts4#510]
I am using Spring Boot with Thymeleaf as template engine and placed css files at "resource/static/css" location. But when i try to edit html file, STS doesn't suggest css classes from my custom css file and even from bootstrap css file.

![image](https://user-images.githubusercontent.com/10755858/87830037-dd831f00-c89d-11ea-913c-b890d88c9a13.png)

Have tried all settings in preferences -> editors. Still no luck.

**Comment by kdvolder** [comment]
Eclipse or vscode?

**Comment by jagansankara** [comment]
Eclipse. I am using Eclipse based STS Suite.

**Comment by kdvolder** [comment]
STS itself doesn't have html editing support, so whatever support there is for editing html and css tags in the html comes from Eclipse (STS is essentially Eclipse with some additional spring-specific plugins added on).

I'd like to understand better the situation so that we can determine if there is something we can do to make this work better. Several possible things might be the case:

- Eclipse support for what you want just does not exist.
- Eclipse support for what you want does exist but isn't pre-installed as part of STS
- Eclipse support exists and is installed but the way STS configures spring boot projects is somehow incorrect and makes the CSS completions not work.

You seem to be expecting this to work so I hope you can help determine which of these 3 situations we are actually in (as what we can do about it differs :-).

So my question is really why did you expect it to work? Did you see this kind of CSS completion work before inside of Eclipse/STS, maybe we with a dfferent version of STS or Eclipse or, maybe with a different type of project? If so then perhaps we can determine what's the difference between the working setup and not working one.

**Comment by jagansankara** [comment]
I see Eclipse support with J2EE project but not with Spring Boot application. It is considering Spring Boot project as Java JAR application. I guess this is reason HTML editor not populating CSS suggestions.

**Comment by kdvolder** [comment]
That seems like a reasonable guess at what is going on. Does it help at all if you convert the boot project into a 'war' type project?

Anyhow, the fact that you can get it working on a JEE project... is actually somewhat good news. It gives us hope that maybe it's possible to enable this support somehow via some kind of project configuration. Could you attach a sample project for us to try. Ideally we have two similar projects to compare. One JEE project where it works, and one more typical boot jar project where it doesn't. Then we may be able to play around with those and see if some settings from the working project might somehow be applied to the not working one to make it also work.

**Comment by martinlippert** [comment]
We recently switched the overall support for HTML and CSS files to the Eclipse Wild Web Developer components that are based on the HTML/CSS support from VS Code. Therefore I would recommend to try the latest Spring Tools 4 for Eclipse 4.9.0 to see if this works better. In case the problem persists, please let us know and we can re-open this issue again. In that case it would be great if you could provide a sample project to reproduce this issue and a few steps how to reproduce.
