### ISSUE TITLE
Issue with STS 4 marketplace installation in eclipse

### ISSUE THREAD

**Issue by 4udipayan** [spring-projects/sts4#512]
Hi,
I have downloaded eclipse 2020-03 where I tried to install the STS 4 from the marketplace, but I ended up with some certificate exception. It seems there are some certificate issue.

![image](https://user-images.githubusercontent.com/4082022/87918019-70d17580-ca93-11ea-915b-92401476882b.png)

**Comment by kdvolder** [comment]
I just tried it and it works fine for me. Maybe a temporary network / configuration issue? Can you try again to see if it works better today?

**Comment by 4udipayan** [comment]
Just now I have tried and its same as earlier. There is no luck.

![image](https://user-images.githubusercontent.com/4082022/88020505-7b4e4680-cb49-11ea-8e48-f7d97cbb5965.png)

**Comment by kdvolder** [comment]
It still works fine for me, just tried it again. If you are experiencing this issue inside corporate network / firewall it may be something about that environment blocking certain urls or blocking content in other ways. The certificate error is a bit atypical for that kind of issue but then again, I don't really understand how corporate networks may be trying to block content.

I'm not really sure how to help diagnose / fix the issue, maybe you can reach out to the sysadmin managing your corporate network to help trouble-shoot the issue?

In the mean time you can try doing an 'offline' installation of STS in either one of two ways:

- download a 'full' distribution of STS and simply unpack it (it contains Eclipse with STS pre-installed into it). You can download it from here: https://spring.io/tools
- start with Eclipse and install it from a zipped update site. (The zip is not easy to find at the moment, we have to fix this, so I post you the link here: https://dist.springsource.coM/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/sts4-4.7.0.RELEASE-e4.16.0-updatesite.zip). 

I recommend you go the full distribution route. Update site install at the moment are bugged (includes installation from marketplace) (https://bugs.eclipse.org/bugs/show_bug.cgi?id=564475) and after installing STS update site your Eclipse may not start up anymore, but you can work around it by starting it once with the '-clean' option.

Note: your problem is not related to the Eclipse bug I linked it seems more like some kind of issue downloading the content. But I do not understand why your Eclipse instance cannot download it.

**Comment by 4udipayan** [comment]
I have though downloaded the zip one for e4.16.0 but earlier when I always used to install it from marketplace, it used to work fine from there. Recently I have started to face this certificate issue and wanted to check this with the team. In between today I tried to install this once again from marketplace but this time first I disabled the VPN and it went through smoothly. 

Thanks for your help @kdvolder !

**Comment by kdvolder** [comment]
@4udipayan We appreciate you telling us about the problem you are experiencing.

You are actually not the first person complaining about what may be a configuration issue with certificates on the update site download infrastructure. See also: https://github.com/spring-projects/sts4/issues/502#issuecomment-656204009

Seems like some very different errors, yet also possibly a similar / common cause. Both seems something todo with SSL configurations.

I don't think there is much that I can personally do about it. But maybe @trevormarshall can help. I also tried to get his attention on the other issue.

**Comment by trevormarshall** [comment]
There is a known issue where the download site does not resolve properly inside the VMware network. This is due to a stale split DNS zone leftover from the days after VMware's acquisition of SpringSource. I am coordinating with VMware IT and Engineering Services to get it removed.
In the meantime, if you are affected by this issue, workaround by connecting from outside the VMware network (including client VPN)

**Comment by kdvolder** [comment]
It looks like @trevormarshall is already aware of the issue and trying to get it fixed. Also it seems to be an issue specific/internal to VMWare's corporate network rather than a problem with STS update site. So from STS point of view, I think we can close this ticket.

**Comment by trevormarshall** [comment]
fwiw VMware tells us this can't be removed until after Aug 4 2020.
