### ISSUE TITLE
STS 4.4.0 is unusably slow

### ISSUE THREAD

**Issue by uskiranj** [spring-projects/sts4#513]
using STS 4.4.0 and it is unusable.  On CTRL + hover on a variable or a method is freezing and rotating.  I amusing windows 10.

-startup
plugins/org.eclipse.equinox.launcher_1.5.500.v20190715-1310.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1100.v20190907-0426
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms1024m
-Xmx4096m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM

**Comment by BoykoAlex** [comment]
I've just tried STS 4.7.0 on Win 10 with Java 14.0.2 - tried a new Spring Boot project generated by the Initializr - seems to work fine.
Any chance you can try the latest STS 4.7.0 instead of 4.4.0... I recall there used to be problems you describe in the past...
If the problem persist then we'd like to know:
1. Can you reproduce this with a newly Spring Boot project (Spring Starters wizard) in the new workspace
2. What's the JVM version running STS/Eclipse
3. Turn off Spring Boot Language Server in Preferences -> Language Servers page (uncheck entries in the table). Check if the situation improves
4. A VisualVM CPU Sampling snapshot would be useful (https://visualvm.github.io/download.html). If 3 helps then turn Spring Boot Language Server back on and capture VisualVM CPU sampling snapshot of the Spring Boot Language Server process. Otherwise capture snapshot of Eclipse/STS process.

**Comment by martinlippert** [comment]
@uskiranj I also think that those problems got fixed in later versions of STS4 and you should definitely upgrade to them. Most of those changes and fixes were made for the 4.6.1 and 4.6.2 releases. So please upgrade and report if the problem persists, then we can re-open the issue.
