### ISSUE TITLE
[concourse] support also the pipeline directory

### ISSUE THREAD

**Issue by ramonskie** [spring-projects/sts4#524]
currently only is supported
```
**/*pipeline*.yml : activates support for editing pipelines
**/tasks/*.yml | **/*task.yml : activates support for editing tasks.
```

but allot of standard uses are
ci/tasks/*.yml
ci/pipeline/*.yml

so can we add
`**/pipeline/*.yml`
to https://github.com/spring-projects/sts4/blob/master/vscode-extensions/vscode-concourse/package.json#L72

**Comment by kdvolder** [comment]
Sure, no objections to doing that. This probably won't make it into next release unfortunately because the RC was already built yesterday. 

You can add your own customised file associations via workspace or user preferences in the mean time:

https://code.visualstudio.com/Docs/languages/overview#_adding-a-file-extension-to-a-language

**Comment by ramonskie** [comment]
no worries i will see it in a future release.

in the mean time im still using the customized workspace
