### ISSUE TITLE
Cannot configure already existing starters anymore

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/sts4#539]
Existing project with already configured startes.
I want to remove one or more of these starters -- but the context menu only offers to "Add Starters".
I seem to recollect that in previous versions one could edit existing starters as well.
It would be preferable to be able to do that again.

Spring Tool Suite 4 Main Feature	4.7.2.202009020958-RELEASE

**Comment by martinlippert** [comment]
@2019-05-10 You are absolutely right, the previous edition offered to also remove existing starters from a project, whereas the new edition doesn't offer that option anymore.

Due to the increased complexity of starters and their dependencies we decided to only support the addition of new starters moving forward. We don't have any plans to support the removal in future versions.

The easiest way is to directly edit the build config (your `pom.xml` or `build.gradle` file) instead.
