### ISSUE TITLE
Is this STS or Eclipse?

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#559]
In 4.6.0, when I start up STS, I see in the status bar that there's a bunch of stuff going on. Initializing tooling, updating maven dependencies, building, etc. In 4.8.x, it seems like it just initializes the tooling on start up and then doesn't do the rest of the stuff until you click on something in Project Explorer. So you get 2 medium delays vs the 1 delay at start up. But the 2nd delay doesn't start until you are ready to work. The old way you just double clicked it and came back in a few. Not sure if that's STS or Eclipse. If Eclipse, any idea what component to open the ticket for?

**Comment by kdvolder** [comment]
> Initializing tooling, updating maven dependencies, building,

Those all seem like Eclipse to me. I.e. handling of maven dependencies and project building is not specific to STS.

To be sure whether the problem is really not STS specific, the only 'sure' way would be to try a Vanilla Eclipse installation and see if it happens there too.

> If Eclipse, any idea what component to open the ticket for?

For maven dependencies, I'd say m2e. For project builds I'd say JDT. If the behavior is similar for gradle projects then its more likely a common thing with how classpaths are resolved for project builds and so a JDT issue. If it only affects maven projects, its more likely specific issue to file with m2e.

In any case don't worry too much about what's the best component to file a bug against, the folks at Eclipse are usually pretty good about reassinging tickets as it becomes clearer which component is actually responsible. In practice it isn't allways easy/possible to know what component caused a problem from the get go. So just file a ticket, make your best guess about the component and follow it up from there.

Before filing a Eclipse ticket it is a good idea to try to reproduce the problem with Vanilla Eclipse because:

- Eclipse developers will be less inclined to dismiss the problem as 'not Eclipse' (i.e. they could blame STS and it would be hard to be sure whether the problem is really STS or Eclipse). I think you understand this already :-)

- It is easier for Eclipse devs to reproduce problems if they don't need to install third party components, which they are generally reluctant to do. Problems that are easier to reproduce are more likely to receive attention and get fixed.

**Comment by SledgeHammer01** [comment]
> > Initializing tooling, updating maven dependencies, building,
> 
> Those all seem like Eclipse to me. I.e. handling of maven dependencies and project building is not specific to STS.
> 
> To be sure whether the problem is really not STS specific, the only 'sure' way would be to try a Vanilla Eclipse installation and see if it happens there too.
> 
> > If Eclipse, any idea what component to open the ticket for?
> 
> For maven dependencies, I'd say m2e. For project builds I'd say JDT. If the behavior is similar for gradle projects then its more likely a common thing with how classpaths are resolved for project builds and so a JDT issue. If it only affects maven projects, its more likely specific issue to file with m2e.
> 
> In any case don't worry too much about what's the best component to file a bug against, the folks at Eclipse are usually pretty good about reassinging tickets as it becomes clearer which component is actually responsible. In practice it isn't allways easy/possible to know what component caused a problem from the get go. So just file a ticket, make your best guess about the component and follow it up from there.
> 
> Before filing a Eclipse ticket it is a good idea to try to reproduce the problem with Vanilla Eclipse because:
> 
> * Eclipse developers will be less inclined to dismiss the problem as 'not Eclipse' (i.e. they could blame STS and it would be hard to be sure whether the problem is really STS or Eclipse). I think you understand this already :-)
> * It is easier for Eclipse devs to reproduce problems if they don't need to install third party components, which they are generally reluctant to do. Problems that are easier to reproduce are more likely to receive attention and get fixed.

Yeah, vanilla Eclipse has the issue too.

**Comment by kdvolder** [comment]
@SledgeHammer01 If you file an Eclipse bug, it would be nice to post a link here. We would be interested to keep an eye on it too. And it also helps other folks who might stumble on this ticket, to follow the breadcrumb trail.
