### ISSUE TITLE
STS 4.8.0 and above java perspective missing

### ISSUE THREAD

**Issue by GNINGK** [spring-projects/sts4#570]
Hello,

Trying to install the STS on window with the self extracting jar provided on your website I noticed that the java perspective is missing from the Eclipse embeded version. The issue seems to be with the Eclipse 4.17 you are embeding since STS 4.8.0.
Is it normal behaviour and if it is what should I do to add missing perspective ?

**Comment by martinlippert** [comment]
STS 4.8.x on Windows should contain the Java perspective, so if that is not showing up, something seems to be seriously wrong with the install.

Since this works in general, we should check what exactly is going wrong inside of your installation. When you start the IDE, are there any error messages showing up in the Error Log view?

Also when looking at the About dialog, and then selecting the Installation Details and the Configuration details, is your IDE running on a JDK >= 11? We shipped an embedded JDK15 to be used for running the IDE, but maybe something is going wrong there. Can you double check which JDK is being used from looking at the list of those properties that show up as the configuration details?

**Comment by martinlippert** [comment]
Closing this due to no further updates or feedback arrived. If this problem still occurs, please comment and we can re-open this and investigate this in more detail. In that case, please re-read the questions in the above comment to provide more details... :-)
