### ISSUE TITLE
Make WildWebDeveloper updatable

### ISSUE THREAD

**Issue by 4javier** [spring-projects/sts4#571]
WildWebDeveloper is in a fast development phase. 
STS 4.8.1 ships 0.10.2 while last stable release is 0.11.3, but it's not possible to update it adding new software source.

**Comment by martinlippert** [comment]
I tried a fresh STS 4.8.1 and added this update site to the preferences:
https://download.eclipse.org/wildwebdeveloper/releases/latest/

Followed by a "Check for Updates". This results in an update dialog showing up with an available update of the Wild Web Developer feature in version 0.10.4, which is the latest one showing up on that mentioned update site.

This update site from WWD:
https://download.eclipse.org/wildwebdeveloper/releases/0.11.3/

shows the same version of the main WWD feature, so I think the above mentioned update site points indeed to the latest WWD release. When I continue with the "Check for Updates" dialog, the update installs fine, I can restart the IDE and the new version of WWD is installed just fine.

So to me it looks like I can update an STS 4.8.1 install to the latest WWD release, but maybe something is different on your end that causes this update to fail. Following the steps that I described, do you see an error message when trying to install the update? Or is there no update showing up at all when doing a "Check for Updates"? If that is the case, please double check the version of the installed main WWD feature via the About dialog and the installation details to see if this is indeed still 0.10.2 or maybe already updated to 0.10.4. And if an error message shows up, please attach it here so that we can take a deeper look.

**Comment by 4javier** [comment]
@martinlippert 
I was trying to install latest snapshot from https://download.eclipse.org/wildwebdeveloper/snapshots/ as suggested by WWD dev.
I was using the "Help → Install new software" menu, and this is what I get
![immagine](https://user-images.githubusercontent.com/459381/100521977-a277ed00-31a7-11eb-9178-062359ad28b3.png)
I tried with latest release you linked https://download.eclipse.org/wildwebdeveloper/releases/latest/ and get exactly the same problem.
Using "Help → Check for Updates" after checking to have the sources enabled
![immagine](https://user-images.githubusercontent.com/459381/100522026-0b5f6500-31a8-11eb-8993-ab7697a9962f.png)
simply doesn't update anything. No error. No update.

**Comment by martinlippert** [comment]
The latest snapshot is indeed not installable on STS 4.8.1 due to an incompatibility between the m2e usage of the XML language server and the WWD usage of the same. If you remove the snapshot update site, updating to the latest release version should be possible (if you have both update sites around, the IDE will always try to update to the latest version). Can you try that?

**Comment by 4javier** [comment]
@martinlippert 
I had just find out that, and I was editing my previous message. LemMinx version for POM editor seems to be incompatible with the newer one needed by WWD 11.x.
Anyway, I tried to update just to the latest RELEASE, and now actually update dialog shows up, but just to say this to me:
![immagine](https://user-images.githubusercontent.com/459381/100522724-4adb8080-31ab-11eb-934a-752dc0ca86b3.png)
I installed STS4 from AUR on Archlinux. Tell me if you need any installation info.

**Comment by martinlippert** [comment]
With regards to the incompatible POM editor, you can uninstall that feature via "About -> Installation Details", then select that feature from the list and uninstall it. After a restart, you should be able to install the snapshot from WWD again - at least it worked while doing some quick testing here.

With regards to the latest error message, I unfortunately haven't seen that before. Are there any more details (from the `More...` link? Or a stack trace in the Error Log view maybe?

You could also try to install STS4 from the tar.gz, maybe there is a permission issue with the location you installed STS4 into.

**Comment by 4javier** [comment]
@martinlippert 
Maybe the problem arised when WWD has been integrated into STS.
Now it gets installed inside /opt/STS/plugins path, root owned.
Previously, I installed it explicitly with my STS instace running as user, then it got installed inside my home.
For anyone interested:
- Run eclipse as root to execute the update
Thanks for your help.
