### ISSUE TITLE
why there is no sts for intellij idea community?

### ISSUE THREAD

**Issue by Dhruv-Garg79** [spring-projects/sts4#575]
I just want to know if there are any plans of having sts plugin for intellij idea.

**Comment by martinlippert** [comment]
We don't have any plans to integrate the Spring Tools 4 into the IntelliJ IDEA due to the comprehensive existing Spring support that comes with the IntelliJ IDEA Ultimate Edition.

There is a community-driven project that integrates the Spring Tools 4 language server into the IntelliJ IDEA (including the Community Edition) that you can find here: https://plugins.jetbrains.com/plugin/14279-spring-tools

**Comment by Dhruv-Garg79** [comment]
Thanks
