### ISSUE TITLE
STS 4.8.0 template proposals invalid

### ISSUE THREAD

**Issue by moonknight37** [spring-projects/sts4#579]
When I use the latest stable version of STS, I tried to use 'Alt + /' to get template proposals, then the IDE displayed 'Computing proposals(0%)...' and no template proposals display.

**Comment by martinlippert** [comment]
I think I figured out what is causing this issue and I am working on a solution. Unfortunately, this is not super easy to improve and solve, so it will take a while. But I am on it.

Technical details:
The completion request arrives at the language server, which is trying to take a copy of the internal text document buffer to work with. This "taking a copy" goes through the global event loop, which is busy at that time. Therefore the completion request has to wait for that lock to become available.

The reason why the event loop (AsyncRunner) is busy could be manifold. In one case it is still working on a document change notification, updating the live hover information, and waiting for some JDT type information (which could take a long time, depending on JDT doing something long-running in the IDE like a build or updating the index). Another case that I saw is an update notification reaction taking a long time because the AST parsing was slow (e.g. for a very large Java file).

One part of the solution is to re-work the way the language server deals with the internal event loop. It still has to process the events in the order they arrive, but they should not really wait for each other in every case. The underlying mechanics how the language server deals with text documents could be improved here as well to avoid locking.

Another area that might need some work here is the reaction to a change notification. Most of the following internal reactions should happen async (on a snapshot of the text document, as most of them do anyway). Especially the call chains that involve additional communication to outside systems (like the JDT type information requests) need to run in an async way, independent of the event loop runner.

The case of a large Java file and the AST parser taking a long time to create the AST is a different case that is harder to solve. A completion request will most likely need an AST in order to identify possible completion proposals. If that takes too long, what should happen?

Another area that is involved here could be the cancellation of requests from the client.

**Comment by martinlippert** [comment]
I committed a number of changes that should help to address this issue. Would be awesome if you could give this a try and report back how things are going. You can download the latest CI build from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by BrenoVitoi** [comment]
Window >>> Preferences >>> Java >>> Editor >>> Content Assistent >>> Advanced >>> Java Proposals 

https://www.youtube.com/watch?v=l8pIEnUiYb8

**Comment by martinlippert** [comment]
I think this is fixed now and should not happen again. Therefore marking this as fixed for the upcoming 4.10.0.RELEASE. If you come across this issue again, please commend and we can re-open (or file new issue). In that case, please capture a thread dump while content-assist hangs from both the IDE process as well as the Spring Boot language server process.

**Comment by ganesh1382** [comment]
sts 4 also won't give html template proposal, but its work in sts 3.9.10

**Comment by martinlippert** [comment]
@ganesh1382 Sorry for being late replying to your comment here. I think the missing HTML template proposals are related to the Spring Tools now shipping with the Wild Web Developer tools instead of the regular HTML tooling of the Eclipse Web Tools project. So I would suggest to file this issue against the Wild Web Developer project.
