### ISSUE TITLE
Let custom @Endpoint appears in the "Request Mapping" tab of the "Properties" view

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#582]
For: 

* STS 4.9.0
* Spring Boot 2.4.1

Having:

```
@Component
@Endpoint(id="springhost")
class SpringHostEndpoint {

	@ReadOperation()
	HostInfo report() {
          ....
        }
}
```

It works fine, the custom `@Endpoint` appears under the `.../actuator` base path how `/springhost` as follows (see the second link):

![01](https://user-images.githubusercontent.com/2552795/103547054-e1b5ef80-4e71-11eb-9f85-45c2ef8353d5.png)

Now about STS, observe the following:

![02](https://user-images.githubusercontent.com/2552795/103547088-ef6b7500-4e71-11eb-9ea0-6fac4e48ff1d.png)

From above, two things to notice:

* Appears all the SB's endpoints
* Does not appear the developer's custom endpoint

It happens with and without Spring Dev Tools, or even doing a `clean compile`. Nevertheless the Bean appears as follows: 

![Screen Shot 2021-01-04 at 9 11 36 AM](https://user-images.githubusercontent.com/2552795/103547028-d9f64b00-4e71-11eb-9250-e52a21a13a4c.png)

Therefore, so, is possible improve the `Request Mappings` tab to include/show the custom `@Endpoint`? Or perhaps add a new tab named: `Endpoint Mappings`?.

Thanks in advance

**Comment by martinlippert** [comment]
@manueljordan I tried this and it seems to work fine, but my setup seems to be a little bit simpler. The request mappings tab in the dashboard properties shows the information from the `actuators/mappings` endpoint. What happens when you look at the JSON data from that endpoint in your case? Does it contain your `springhost` endpoint?

Maybe you can attach a sample project that reproduces the problem, so that we could take a deeper look. Seems like your actuator path is different than the default setting, so maybe that makes a difference.

**Comment by manueljordan** [comment]
Not sure what happened, now they appear:

![Screen Shot 2021-01-11 at 10 02 16 AM](https://user-images.githubusercontent.com/2552795/104198520-50f08e00-53f4-11eb-87d6-630eedfdb4f3.png)

![Screen Shot 2021-01-11 at 10 02 41 AM](https://user-images.githubusercontent.com/2552795/104198554-59e15f80-53f4-11eb-9353-2fd0c55d6200.png)

As usual, thanks for the quick support.

**Comment by martinlippert** [comment]
Sure, and glad to hear that it works now.
