### ISSUE TITLE
`.sts4` dir location

### ISSUE THREAD

**Issue by muradm** [spring-projects/sts4#601]
**Expected Behavior**
Configurable with jvm args and/or environment variables. May be follow XDG spec.

**Current Behavior**
Hardcoded path:
https://github.com/spring-projects/sts4/blob/0f3f3dfce7fb1630c1a95aaf9f178eaeaf15087c/headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/utils/SymbolCacheOnDisc.java#L65

**Comment by martinlippert** [comment]
Fixed with https://github.com/spring-projects/sts4/commit/17d8ecf02e56405f17d0be59a99294f6972d62d4. This is now configurable with a property called `languageserver.boot.symbolCacheDir` and should be given a fully qualified path to the directory that should be used for storing the symbol cache.

This could, e.g., be passed as a JVM arg like `-Dlanguageserver.boot.symbolCacheDir=/Users/username/.sts4/.symbolCache` to the language server via https://github.com/spring-projects/sts4/wiki/Custom-VM-Args to the language server process.
