### ISSUE TITLE
"Hide from Boot Dash" has no effect

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/sts4#613]
**Describe the bug**
In run configuration
[x] Hide from Boot Dash
is checked, but the project nevertheless shows up in Boot Dash

Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2021-03 (4.19.0)
Build id: 20210312-0638

Spring IDE Boot Microservices Dash	4.10.0.202103111225	org.springframework.ide.eclipse.boot.dash.feature.feature.group	Spring IDE Developers

**Comment by martinlippert** [comment]
Hey @BoykoAlex, can you take a look at this? That would be great.

**Comment by BoykoAlex** [comment]
I've tried the "hide from boot dash" checkbox in the boot launch config. Seems to be all working fine. Is it some special launch config? Coming from the previous Eclipse/STS version perhaps?
Seems to work fine with any launch config I've created in my STS 4.10
I've tried creating 3 launch configs for petclinic, open the launch config dialog, select petclinic launch config and check/uncheck the checkbox "Hide from Boot Dash" and apply config watch the Boot Dash configs appear/disappear under Local -> spring-petclinic in Boot Dash... How is your case different? Any steps you can list to reproduce the issue please?

**Comment by 2019-05-10** [comment]
> Is it some special launch config? 

Nothing special, in fact, it appeared automagically on its own.

> Coming from the previous Eclipse/STS version perhaps?

Probably, project itself was created in the beginnig of March. Next STS update, IIRC, was a couple of weeks later

> How is your case different? Any steps you can list to reproduce the issue please?

As said above, I didn't do anything myself, but it was all done by STS. Thus, no steps.
Since hiding doesn't work either with even older STS projects anymore, I presume that the old launch configurations haven't been converted correctly by the latest update.

**Comment by 2019-05-10** [comment]
Funny thing: I just deleted the launch configuration completely -- doesn't bother the dash, project is still listed.
So, looks to me as if the dashboard at least does something else on the side.
How exactly does the dashboard determine what projedcts to list?

**Comment by 2019-05-10** [comment]
Curiouser and curiouser.

Dash board view -> Local -> RMC on the proejct -> Open Config
opens the "Debug Configurations" dialog (why "Debug"?) with a mostly empty interface, but as name
"my project (1)"
as if there were another already with the same name.

**Comment by BoykoAlex** [comment]
Boot Dash would start showing launch configs as children of an app if there are more than one launch config. If an app has one launch config it's not shown in the dashboard at all because there is no reason to show it really. You'd need to have more than one launch config for an app to see **Hide from Boot Dash** feature working

**Comment by 2019-05-10** [comment]
I'm sorry, what?

**Comment by BoykoAlex** [comment]
Do you have **Hide solitary launch configs** unchecked in Boot Dash filters? It is checked by default hence you won't see launch config if there is just one... if there is more than they'd show under the app. If you have unchecked then you'd see all launch configs but since you didn't mention it i assumed one launch config won't show under the app by default. Does this make sense to you?

**Comment by BoykoAlex** [comment]
Run configuration and project are two distinct elements. **Hide from Boot Dash** in the launch config wizard/dialog only applies to launch config and **not** to the project. My feeling at the moment that you expect the project/app to go away from Boot Dash when **Hide from Boot Dash** is checked - I don't think this is expected.
One could hide launch configs but not the app/project... You can tag your elements in Boot Dash and then enter tag of elements you'd like to see only... but I don't think we have anything explicit to not show project/app in Boot Dash (similar to launch config)

**Comment by BoykoAlex** [comment]
There is a way to remove app/project from Boot Dash.
Go to Preferences -> Spring -> Boot page. Under **General** section find **Exclude Projects** text box. Type regular expression for projects you'd like to be hidden.

Does any of it help?

**Comment by 2019-05-10** [comment]
> Go to Preferences -> Spring -> Boot page. Under **General** section find **Exclude Projects** text box. Type regular expression for projects you'd like to be hidden.

Works.

But from a UX PoV this is plain horrible!
Why do I have to look in the **_global_** preferences for such a **_local_** feature -- if anywhere this belongs to the Dash view itself, as part of the  filters.

As for the checkbox in the Launch configuration, that seems to be completely pointless. I am still not sure I understand the explanation, but from what I gather, it is confusing, to say the least.

AFAIU, the entry in the Dash view appears magically w/o any way to control its existence. 
It exists independently of a Launch configuration, and yet, it offers an active context menu entry "Open Config" that leads to a Launch configuration w/o any hint that this configuration is just for fun.
The checkbox "Hide from Boot Dash" in particular follows an arcane, to put it mildly, rule when to be effective.

What exactly is the rationale behind all that?

**Comment by martinlippert** [comment]
Let me explain:

The overall rationale behind this is that the Boot Dashboard should provide a quick and easy-to-access one-click experience to start and stop your Spring Boot application (among other features it provides). Therefore it shows all the Spring Boot apps of your workspace by default, without the need to configure anything or do mark your projects. It identifies projects as Spring Boot projects and then shows them in a list. To that level of the boot dashboard is all about your Spring Boot projects.

If you start a Spring Boot project, there is an associated launch config being used - the regular way in Eclipse to launch apps. Therefore you can jump from the project entry in the Boot Dashboard to the corresponding launch config that is used to launch the app.

If you have exactly one launch config for a project, we don't show the launch config in the boot dashboard by default. You can enable that from the context menu of the boot dashboard, but by default, this is disabled.

If there are more than one launch config for an app, those different launch configs show up as nodes below the application, so that you can see all the related launch configs for your project. You can start/stop all of them or individually. For that case, users have asked us to allow to NOT show very specific launch configs in the boot dashboard, therefore we added the option to not show a specific launch config in the boot dashboard.

I fully agree to the point that the preference to hide specific projects (not launch configs) is totally hidden and too far away from the boot dashboard itself. We tried to address that by adding a menu item to the dashboard view menu called `Boot Projects Filters Preference...`, which navigates you to exactly that preference. But that doesn't seem to do the job here... ;-) We could introduce a context-menu item for a project on the dashboard to hide it from the dashboard - and the same for the project in the project explorer to bring it back. Just an idea. Any other concrete ideas here?

Hope I could explain the rationale behind the boot dashboard a bit. There is a user guide section about it as well where some or many of these aspects where described: https://github.com/spring-projects/sts4/wiki/Introduction-And-Working-With-Local-Projects.

I am sure thee is a lot of room for improvement here (on the boot dashboard itself as well as on the user guide), so we will take your input here ans try to improve. If you have any additional concrete suggestions, please feel free to add them. They are more than welcome.

**Comment by 2019-05-10** [comment]
> The overall rationale behind this is that the Boot Dashboard should provide a quick and easy-to-access one-click experience to start and stop your Spring Boot application (among other features it provides). Therefore it shows all the Spring Boot apps of your workspace by default, without the need to configure anything or do mark your projects. It identifies projects as Spring Boot projects and then shows them in a list. To that level of the boot dashboard is all about your Spring Boot projects.

As far as I can tell, the Dash is all about _runnable_ projects (start, stop, debug, launch config, connection,  ...)
So, no Spring Boot project that is not supposed to be run should appear here.

That would remedy the initial cause of my ticket:
I got three projects, one as a SHARED project containing everything common, and two to be actually run (using SHARED as library).
SHARED should not appear in Dash.
 
> If you start a Spring Boot project, there is an associated launch config being used - the regular way in Eclipse to launch apps. Therefore you can jump from the project entry in the Boot Dashboard to the corresponding launch config that is used to launch the app.

That is highly confusing and hardly in keeping with the overall Eclipse experience -- to run something, a Launch configuration is required.
Hence, no Launch conf, no entry in the Dash.
This again would remedy my initial issue: since SHARED has no runnable class, a Launch config cannot be created, thus it would'nt appear in Dash. 
Or else, that Launch config simply could be deleted by the user who intuitively recognizes the relationship between Launch conf and entry in Dash.

> I fully agree to the point that the preference to hide specific projects (not launch configs) is totally hidden and too far away from the boot dashboard itself. We tried to address that by adding a menu item to the dashboard view menu called `Boot Projects Filters Preference...`, which navigates you to exactly that preference. But that doesn't seem to do the job here... ;-) We could introduce a context-menu item for a project on the dashboard to hide it from the dashboard - and the same for the project in the project explorer to bring it back. Just an idea. Any other concrete ideas here?

The Dash's toolbar has an entry called "Filters" -- why exactly is that feature (which is at least as much if not more about filtering than the three current entries) not part of it?
After all, the three existing entries concern themselves as well with managing the contents of the Dash.
Even if, for some reason that feature needs to be part of the overall preferences, why not have that `Boot Projects Filters Preference...` there instead of being hidden in the dots menu?

**Comment by martinlippert** [comment]
> > The overall rationale behind this is that the Boot Dashboard should provide a quick and easy-to-access one-click experience to start and stop your Spring Boot application (among other features it provides). Therefore it shows all the Spring Boot apps of your workspace by default, without the need to configure anything or do mark your projects. It identifies projects as Spring Boot projects and then shows them in a list. To that level of the boot dashboard is all about your Spring Boot projects.
> 
> As far as I can tell, the Dash is all about _runnable_ projects (start, stop, debug, launch config, connection, ...)
> So, no Spring Boot project that is not supposed to be run should appear here.
> 
> That would remedy the initial cause of my ticket:
> I got three projects, one as a SHARED project containing everything common, and two to be actually run (using SHARED as library).
> SHARED should not appear in Dash.

That sounds related to https://github.com/spring-projects/sts4/issues/605.

**Comment by martinlippert** [comment]
> The Dash's toolbar has an entry called "Filters" -- why exactly is that feature (which is at least as much if not more about filtering than the three current entries) not part of it?
> After all, the three existing entries concern themselves as well with managing the contents of the Dash.
> Even if, for some reason that feature needs to be part of the overall preferences, why not have that `Boot Projects Filters Preference...` there instead of being hidden in the dots menu?

Agree, we should change that and redesign the filtering experience here. Doesn't provide a coherent experience at the moment.

**Comment by martinlippert** [comment]
> > If you start a Spring Boot project, there is an associated launch config being used - the regular way in Eclipse to launch apps. Therefore you can jump from the project entry in the Boot Dashboard to the corresponding launch config that is used to launch the app.
> 
> That is highly confusing and hardly in keeping with the overall Eclipse experience -- to run something, a Launch configuration is required.
> Hence, no Launch conf, no entry in the Dash.
> This again would remedy my initial issue: since SHARED has no runnable class, a Launch config cannot be created, thus it would'nt appear in Dash.
> Or else, that Launch config simply could be deleted by the user who intuitively recognizes the relationship between Launch conf and entry in Dash.

I don't agree here. I really like the fact (and think this is an important feature of the boot dashboard) that you can "just run" your Spring Boot app without creating a launch config yourself before. And this is not something totally alien to Eclipse (there is also the context-menu, where you can select a project, right-click, and then select "Run As...", which automatically creates a launch configuration behind the scenes).

Therefore, showing projects AND launch configs in the boot dashboard makes sense to me. However, I see the confusion that it creates for projects that are not runnable or that users will never run, even if it might be possible, technically.

I would suggest:
- We do not show projects without a main class anymore in the boot dashboard (by default)
- We re-design the filtering experience to make it more coherent (and maybe more advanced)

Once that is done, we can re-evaluate to see what other changes are necessary to improve the experience and to further reduce confusion.

**Comment by 2019-05-10** [comment]
> > That is highly confusing and hardly in keeping with the overall Eclipse experience -- to run something, a Launch configuration is required.
> > Hence, no Launch conf, no entry in the Dash.

> I don't agree here. I really like the fact (and think this is an important feature of the boot dashboard) that you can "just run" your Spring Boot app without creating a launch config yourself before. And this is not something totally alien to Eclipse (there is also the context-menu, where you can select a project, right-click, and then select "Run As...", which automatically creates a launch configuration behind the scenes).

Well, that was misleading. 
Ithink, in fact, my and your idea quite match -- only show projects with a Launch config. If no main class exists, do not create a Launch config.
`main class` in this context of course one with `@SpringBootApplication`.

**Comment by kdvolder** [comment]
I also like that you can run apps from boot dash without first creating a launch config. When you do, the Boot Dash creates the launch config for you and that is very convenient. Otherwise you have to go through some additional steps to create launch configuration. These extra steps would be especially cumbersome if you needed to run more than one app at the same time, which a scenario the boot dash was expecitly designed to provide a convenient mechanic for. I.e. you select several projects in boot dash, click 'start' and several launch configs are created/started with a single button click. 

I can see the logic of only showing things with launch configs in the boot dash though. That does make sense from some point of view as well.

**Comment by BoykoAlex** [comment]
Showing only projects with either present launch config or main class only in Boot Dash by default -> 0b840cd8ea03e7de0bf07d5a3c0eaa4466fd75cb

**Comment by martinlippert** [comment]
Just as a quick follow-up: both mentioned enhancements are implemented and will be shipped as part of the next release (late in June 2021).
