### ISSUE TITLE
Issue with new file wizards in Spring Tool Suite 4.10.0

### ISSUE THREAD

**Issue by hoak-land** [spring-projects/sts4#622]
**Describe the bug**
In STS 4.10.0:
When I try to add a new HTML, CSS or JSP file to my Spring Boot project, I can't see wizards for these file types. They do not appear in the wizard list. (These wizards were available in STS 4.9.0)

**To Reproduce**
Launch STS.
Open a project.
Press Ctrl+N to open "Select a wizard" dialog. 
No wizard listed for HTML, CSS or JSP.

"Select a wizard" Dialog (STS 4.10.0)
![sts4 10 0](https://user-images.githubusercontent.com/82163186/114097262-7a706700-98c8-11eb-82f6-127bf333f23c.png)

"Select a wizard" Dialog (STS 4.9.0)
![sts4 9 0](https://user-images.githubusercontent.com/82163186/114097265-7b08fd80-98c8-11eb-8105-ae618168a3e4.png)

**Comment by martinlippert** [comment]
Spring Tools 4 for Eclipse started to move to the Wild Web Developer components for working with web components like HTML or CSS files and those Wild Web Developer components do not provide those extra wizards for creating new files on these types. Instead, you can just go ahead and create a new file with a name and the appropriate file type extension.

If you prefer to use the older components from the Web Tools project, you can install them via: `Install New Software`, select the main Eclipse update site, and look for the `Eclipse Web Developer Tools` feature. That will bring the wizards that you mentioned back, but also comes with their specific editors for them.

So you end ups having quite a bit of duplication of features in your IDE. For example two ways to edit and validate HTML pages will be around (the `HTML Editor` from the old WTP tooling and the advanced `Generic Text Editor` with support for HTML files from the Wild Web Developer components). We had this in previous releases of the Spring Tools 4 for Eclipse (that is why you had the wizards in Spring Tools 4 for Eclipse 4.9.0), and it caused quite some confusion - so that we went ahead and removed the older WTP components.

**Comment by martinlippert** [comment]
https://github.com/spring-projects/sts4/issues/572 (for the reference here)

**Comment by dfvalenciav** [comment]
Lets try to use index.html or styles.css in new file name and then complete your work

**Comment by yagosayansext** [comment]
Hi, I am having quite the same problem but i don´t understand what is the real solution to it. I am currently using STS 4.17.2 and I am nos able to create default HTML files using the wizard. When I try to use the wizard this is what I obtain:
![image](https://user-images.githubusercontent.com/125879834/222433949-dc06f550-6a76-4404-8384-941ea7a53d44.png)
and I already have the eclipse web developer tools and html editor installed.
![image](https://user-images.githubusercontent.com/125879834/222434199-8893ce4f-ca93-4dc1-9eb8-76ea76c908bc.png)
Could you give me a solution?

**Comment by martinlippert** [comment]
@yagosayansext I tried to reproduce this starting from a fresh STS 4.17.2.RELEASE distribution install and it seems to work as expected. Here is what I can do and see:

- when running the vanilla 4.17.2.RELEASE installation (without any extra plugins installed), I don't have any wizards to create HTML files or anything like that, but when I create those files as regular files they open in the Generic Editor for those file types and I get all kinds of support features (like content-assist, etc.), so this is what is expected to be included in the default installation of STS.
- when I open the Eclipse Marketplace from within STS, I can install the `Eclipse Web Developer Tools` (that you also mentioned in the screenshot of your comment) and after installing that, I get those additional editor types in my installation, so that I can choose between specialized editors or those based on the Generic Editor. The wizards to create those files also show up.

So it looks like this works as expected (at least when starting from a fresh install), so it looks like something is different in your setting. I wonder why there is a "change" showing up for that item in your install. What does the dropdown offer you? Can you uninstall and re-install that package, for example? Or would it be an option to start with a fresh STS install and go from there?
