### ISSUE TITLE
creates folders like F827A47534... in java.io.tmp

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/sts4#625]
**Describe the bug**
Current STS creates a folder like 
`F827A47534...`
in 
`java.io.tmpdir`
Folder contains only a subfolder
`servlet-sessions/`
without any content.

The folder isn't removed either when the project is stopped again.
AFAIR having in my project a folder
`public/`
is supposed to prevent filling up of
`java.io.tmpdir`
but since the latest update apparently that doesn't work anymore.

**Comment by kdvolder** [comment]
When is this file created? Is it when you launch STS? When you launch a boot app? If it is when launching a boot app, it probably something that the app does rather than something that STS itself does. WE can investigate and debug it to determine what is happening but it would be helpful you can attach a sample app or describe in a bit more detail how we can setup an app ourselves that causes this behavior.

**Comment by martinlippert** [comment]
I will close this one now as there is no sample that could help us to reproduce this issue. If you are still hitting this issue and can attach a sample project (and a few steps how to reproduce), please comment and we can re-open anytime.
