### ISSUE TITLE
STS 4.10.0 responding very slow

### ISSUE THREAD

**Issue by coolkanchan** [spring-projects/sts4#632]
Hi Team STS 4.10.0 responding very slow, when i click on any java class its seems to hang after 20 to 30 second it will become normal state. below is my .ini file

-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.100.v20210209-1541
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m

**Comment by martinlippert** [comment]
Does this happen only when you open the first Java source  file or does that happen when you open subsequent Java source editors as well?

In addition to that it might be interesting to get some additional insights into the situation:
- can you capture one (or multiple) thread dump(s) of the IDE process while it is slow or hangs for those 20-30 seconds?
- can you capture one (or multiple) thread dump(s) of the BootLanguageServerApp process during that timeframe?
- can you enable the log output of the Spring Boot Language Server (`Preferences -> Language Servers -> Spring Language Servers`, then check the `Spring Boot` entry. This will push the internal log output of the language server process into the console view of the IDE, so that you can copy/paste this into a file and attach it here. That would be great. The log file will most likely contain path and file names, so if there is anything secret in there, make sure to wipe that from the log file.
- does this happen for every project? and do you have a sample project that reproduces this behavior that we could try?

**Comment by coolkanchan** [comment]
frequently its happened when first time java file opend but also some time i have an also experience of subsequent java source editor..  please find the thread dump for your reference.

[ThreadDump1.txt](https://github.com/spring-projects/sts4/files/6412110/ThreadDump1.txt)

**Comment by coolkanchan** [comment]
![image](https://user-images.githubusercontent.com/15816670/116825326-690b3980-abac-11eb-8970-21e875c086bc.png)

**Comment by martinlippert** [comment]
@coolkanchan Thanks for the additional details. The message in the log output is the key here, I think. It looks like the language server fails to start due to a missing class. That could be caused by an issue during the install process. Did you download the executed the self-extracting JAR file for the STS4 distribution for Windows?

**Comment by coolkanchan** [comment]
Hi @martinlippert  thanks for prompt response,
yes, i have downloaded self extracting jar file for STS4 distribution for windows(spring-tool-suite-4-4.10.0.RELEASE-e4.19.0-win32.win32.x86_64.self-extracting)

**Comment by martinlippert** [comment]
The only guess that I have at the moment is that something went wrong while extracting the distribution or that something corrupted the install. Can you try and extract the distribution again (maybe to a different location), enable the log output again, create a sample Spring Boot project, open a Java source - to see if the same issue happens again?

**Comment by coolkanchan** [comment]
okay, thanks. I will do that as you suggested. will get back to you if I face an issue.
