### ISSUE TITLE
STS 4.11.0.RELEASE Git can not add index

### ISSUE THREAD

**Issue by kafecat** [spring-projects/sts4#657]
**Describe the bug**
STS 4.11.0.RELEASE Git can not add index

**To Reproduce**
sometime can not add index on git staging.need restart
use greade build java project. sometime can not build.need restart

**Comment by martinlippert** [comment]
Can you provide more details on this issue? It is not clear to me know to reproduce this from your description. I am not aware of a general issue with the Git Integration, so it sounds like we need to investigate this in more detail with a few more details from your side, a sample project that could help us to reproduce this, steps to reproduce, the system you are running on, etc.

In case this turns out to be an issue with the Git Integration for Eclipse, I would also recommend to file a bug at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit (and maybe look there for existing, similar bugs).

**Comment by de-das-dude** [comment]
I am also facing the same issue.
Cannot move the edited files to staging so that i can create a commit and push the changes.

Need to restart the application to be able to stage files.

To replicate, 
WHEN files are edited
AND showing in git unstaged changes
THEN try to move them to staged changes by dragging or right clicking and selecting the correct option.
THEN the files do not go to staged changes

**Comment by kafecat** [comment]
> Can you provide more details on this issue? It is not clear to me know to reproduce this from your description. I am not aware of a general issue with the Git Integration, so it sounds like we need to investigate this in more detail with a few more details from your side, a sample project that could help us to reproduce this, steps to reproduce, the system you are running on, etc.
> 
> In case this turns out to be an issue with the Git Integration for Eclipse, I would also recommend to file a bug at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit (and maybe look there for existing, similar bugs).

**Comment by ricoom** [comment]
Same here.. Has any one found a solution?
