### ISSUE TITLE
Local dependency repository / path instead of only get dependencies or be restricted from internet, not letting create a project successfully

### ISSUE THREAD

**Issue by rodneyazev** [spring-projects/sts4#675]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by rodneyazev** [comment]
I will need to migrate to NodeJS because of this, because after we create a project, I can use the the packages I download, to create projects anytime anywhere, as my personal devpack, something that I miss with Spring and Eclipse.

You dont need to do this because of me.

Just a feel frustraded.

Thanks and advance.

**Comment by martinlippert** [comment]
I am still not sure I understand the details here. In case you use Maven as the build system, it caches downloaded dependencies on your local machine in the local Maven repo and it will not download the dependencies again when building the project or creating a new project that refers to the same dependencies - which is pretty similar to what npm is doing.

In case you are referring to the import wizards that let you create a new project using Spring Initializr (which you would do via https://start.spring.io otherwise), this calls indeed https://start.spring.io under the hood and therefore requires internet access. If you want to avoid that, you could do different things: You can go to https://start.spring.io, download a project as a ZIP file, extract that ZIP file and import that as a project manually into your IDE. And you could do that whenever you want to create a new project. You could also host a version of start.spring.io yourself (e.g. in your companies network) and use that from the IDE.

In case your Maven config is set accordingly, you could even set this up to use a company-local Maven repo with all the necessary dependencies and use that, if you want to work in a closed setup within your company.

Just a few thoughts here. Let me know more about the details and we can see if there is already a way to do what you are trying to accomplish or if we need something else here.

**Comment by rodneyazev** [comment]
Hello Martin,

The main problem is when I try to add another dependency in my project, for
example, I wand add the spring oauth client.

Spring try download a existent library instead use the existent one. And
this impact if I would like to increase the functionality of my project.

I really dont know why this happen.

Em qui., 19 de ago. de 2021 06:41, Martin Lippert ***@***.***>
escreveu:

**Comment by martinlippert** [comment]
Do you use Maven for your builds and projects? If so, there is an offline mode in Maven and you can enable this from the preferences.

**Comment by rodneyazev** [comment]
Yes, I use it. If this is possible, i would love to know how to do it, please. I would be very grateful for that.

**Comment by martinlippert** [comment]
So if I understand you correctly, you are trying to:

- create a new project using https://start.spring.io and you select a few dependencies for that
- you download the ZIP file and run the build
- then Maven runs the build and downloads all the dependencies for this project (in case you don't have a local Maven repo that already contains all those libraries)

Is this already problematic for you? Or would you like to have an option in initializr that not just downloads the project for you, but also a pre-populated local maven repo with all the dependencies?

**Comment by rodneyazev** [comment]
Complementing:

- and when I try use some of these libraries, and an existing project, just one, somehow the maven do not build properly, as it decides first download this library for this project, instead of use the existing one.

And about "an option in initializr that not just downloads the project for you, but also a pre-populated local maven repo with all the dependencies", would be great, however, when I try to capture some of the libraries to an ongoing project - as I have port restrictions in my workstation, because I am not from dev team, but an Analyst from Infrastructure team - maven stuck the project, because the imposssibility to download from internet.

**Comment by martinlippert** [comment]
This sounds a lot like you should get in touch with some IT admin to see what the proper way is to use Maven in-house. My guess would be that there is a company-wide local Maven repo that people should use instead of downloading things from the internet (for some good reasons). If this is true, you can configure your machine to use that company-wide Maven repo instead of downloading stuff.

**Comment by rodneyazev** [comment]
My company use an Eclipse IDE modified.

I would need create my own Maven repo so.

I don't have to program, but I intend to help another colleague, and who knows, start doing my own projects to help my teammates.

**Comment by rodneyazev** [comment]
Hey Marvin, thank you very much for your attention and patience. You helped me a lot. I will see what I can do. thank you so much again. 🍻👍

**Comment by martinlippert** [comment]
If you need any additional help, please comment. For now, I will close this issue.
