### ISSUE TITLE
Code comment suggests for sts4

### ISSUE THREAD

**Issue by drc5521** [spring-projects/sts4#685]
**Expected Behavior**

When I use the shortcut key "Alt + /" to comment the code, the effect should be as shown in Figure 2.

**Current Behavior**

Shown in Figure 1. This style is very unsightly. I have to use code formatting to become Figure 2, but that is very troublesome, because I don't want to format the code every time the comment is finished.

**Context**

I hope that when using the shortcut key "Alt + / ", it will be directly in the style of Figure 2.

Figure 1.
![code comment-1](https://user-images.githubusercontent.com/55195642/133557059-d5e3d1ce-4a16-4cfe-a143-ee2309ae34d2.png)
Figure 2
![code comment-2](https://user-images.githubusercontent.com/55195642/133557088-314d0870-995d-4008-b242-81d4a2bdd45f.png)

**Comment by martinlippert** [comment]
This is nothing that we control from the Spring Tools side. It is implemented as part of the Java tooling inside of Eclipse, so any enhancement request should be reported there.

However, you would need to make some very strong arguments for this change when reporting this. I think many people like it the way it works at the moment and it was implemented that way because of that reason. The part of this that I find questionable is that code formatting is doing something else than the shortcut.

This could be the argument that you could make: the shortcut and the code formatting should result in the same.
