### ISSUE TITLE
mybatis xml cannot complete the automatic prompt

### ISSUE THREAD

**Issue by moshilgc** [spring-projects/sts4#701]
**Describe the bug**
   In version 4.12.0 of sts4, mybatis XML cannot complete the automatic prompt, even if the mybatis DTD file is imported
![noprompt](https://user-images.githubusercontent.com/18208031/140464623-645ab9b3-2175-4213-b74b-6ad54ef9ced5.jpg)
![sts4](https://user-images.githubusercontent.com/18208031/140464629-91b006da-3c98-46e1-9ae6-ee84a78deb65.jpg)

**Comment by sayseakleng** [comment]
Same issue for STS V. 4.12.1.RELEASE as screenshot below,

![image](https://user-images.githubusercontent.com/19582007/145000786-f922e077-9e1d-4077-ac39-45bcbc2a8b0c.png)

**Comment by martinlippert** [comment]
Sorry for not coming back to this earlier, apologize. Can you double check if this happen with a regular Eclipse JEE installation as well? (Eclipse 2021-09 as well as latest Eclipse 2021-12 RC builds)

Another question here would be what happens if you open the file with the Generic Editor? Does that change the behavior here?

**Comment by martinlippert** [comment]
Please ignore my comment above, I tried this myself with a small sample project and I can reproduce this quite easily. Seems to work fine with a regular Eclipse JEE installation (both 2021-09 and 2021-12), but not with STS 4.12.1 nor the upcoming 4.13.0, so need to dive deeper here what the problem is. Maybe something that is not installed into the STS4 distributions from the standard XML tooling.

**Comment by martinlippert** [comment]
OK, I found the missing piece and here is how to solve that for your installation (in case you don't want to switch to the Generic Editor for editing your XML files):

Please go to `Install New Software`, select the `Latest Eclipse Release` update site from the dropdown and install the feature called `Eclipse XML Editors and Tools`. After that, you should see the content-assist working again in the (old) XML editor.

**Comment by moshilgc** [comment]
It really works. Thank you. I'm sorry I didn't reply in time.
