### ISSUE TITLE
[vscode-spring-boot] Provide better Spring component code completion experience on class and method level

### ISSUE THREAD

**Issue by nickzhums** [spring-projects/sts4#758]
Method-level 
- Users might need to deal with CRUD mapping such as @GetMapping, @PostMapping very often. Therefore, another enhancement is – when user starts typing @ symbol, we can pre-define a list of most often used CRUD mappings (@Get/@Put/@Delete/@Post) and show them in the code completion list. Currently, the default suggestions do not contain all frequent Spring mappings. 
Class-level 
- Besides method level completion enhancement, we could also consider adding better support for @Bean / @Component / @Service when user is typing on the class definition. For example, when user creates an empty class in a Spring app, and starts to type “@”, we should make sure to provide the most frequently used Spring class annotations. 

(cc: @martinlippert @Eskibear)

**Comment by martinlippert** [comment]
The first part of this issue is done, the code completion snippets for request mapping methods nicely show up when you start typing `@` in the editor, in case you are inside a controller class.

I will extract the second part of this issue (the things on the class level) into a separate issue, also to discuss in more detail what exactly we would like to do there.
