### ISSUE TITLE
Error on Content Assist

### ISSUE THREAD

**Issue by gchiarapa** [spring-projects/sts4#766]
I'm facing the issue when I try to use the content assist
![error_content_assist](https://user-images.githubusercontent.com/50337428/163819560-ef6c4a6e-cb75-4b20-baee-27455d8a49fa.jpg)
, I try to solve by uncheck and then apply, and then check Java Proposal and Java Type Proposals, but does not work.

`Spring Tool Suite 4

Version: 4.14.0.RELEASE
Build Id: 202203131612

Copyright (c) 2007 - 2022 VMware, Inc.
All rights reserved. Visit https://spring.io/tools

This product includes software developed by the
Eclipse Foundation https://www.eclipse.org/

This product includes software developed by the
Apache Software Foundation https://www.apache.org/

Lombok v1.18.10 "Envious Ferret" is installed. 

Does anyone could help me?

Thanks a lot.

**Comment by martinlippert** [comment]
@gchiarapa The error message talks about an exception. Can you have a look at the Error Log view? There should be details logged for this exception. Please share those details here.

Also it would be very helpful if you could provide a few steps how to reproduce this error, maybe attach a sample project, and describe how to arrive at this error.

I also See from your "about" details that you have the Lombok extension installed. Would it be possible to install a fresh Spring Tools 4 for Eclipse without Lombok installed to see if the issue is related to the Lombok extension? Would be good to verify whether it is related to the Lombok extension or not.

**Comment by gchiarapa** [comment]
Hi @martinlippert , thanks for help. I solve this issue, by migrating the project to another workspace. Even changing to another workspace I get to solve some erros on the project.

**Comment by martinlippert** [comment]
@gchiarapa Thanks for the update. In case you still have access to the workspace where this doesn't work, the details from the Error Log View would be interesting. Just in case...

**Comment by gchiarapa** [comment]
@martinlippert , Where is the location of this error log?

**Comment by martinlippert** [comment]
@gchiarapa You can open the `Error Log` view in the IDE itself (via `Window -> Show View`, then select `Error Log`)
