### ISSUE TITLE
2022-03, 2022-06 eclipse / Spring Legacy Project Missing (v4.23)

### ISSUE THREAD

**Issue by ajy3477** [spring-projects/sts4#790]
hello.

I installed the Spring Tools 4 and Spring Tools 3 Add-Ons for Spring Tools 4 on Eclipse 2022-03 and 2022-06 respectively because it requires a Spring legacy project.

However, there seems to be a problem during the installation, and the spring legacy project cannot be found even after installation.

Did something go wrong during the installation process?

2022-03 installation process

![eclipse_2022-03_1](https://user-images.githubusercontent.com/62630860/174503198-53662663-78a6-4f52-a198-66c223b8c905.png)
![eclipse_2022-03_2](https://user-images.githubusercontent.com/62630860/174503200-67fe8847-c1d0-4364-bb12-f7b8d229d0ee.png)

2022-06 installation process

![eclipse_2022-06_2](https://user-images.githubusercontent.com/62630860/174503220-30d2c36e-b17e-43ed-933e-654c36362b39.png)
![eclipse_2022-06_1](https://user-images.githubusercontent.com/62630860/174503223-a94be950-a93c-4a21-a5ab-4f23fa3fb9b0.png)

thank you

**Comment by martinlippert** [comment]
Hey @ajy3477, there are two main issues here:

- the STS3 Add-On Pack does not support Eclipse 2022-06. The support for maintenance updates for Spring IDE and Spring Tool Suite / STS3 has officially ended (https://spring.io/blog/2022/06/14/goodbye-spring-ide-welcome-spring-tools-4), so there will be no version with support for Eclipse 2022-06 and beyond.

- Using an older update site to install STS3 components into an Eclipse 2022-06 install will fail due to various incompatibilities (mostly due to dependencies not being around anymore).

- the screenshots that you shared show a number of "Test" bundles being installed, which is what users usually should not install. The STS3 Add-On Pack doesn't include those test bundles, so I wonder how they ended up in your install. Maybe you installed features manually from an update site? But this is just a side note, since the main issue of no STS3 add-on pack being available anymore for Eclipse 2022-06 doesn't enable you to use it anyway.

If you have a so-called legacy project, you should be able to import this into a regular and up-to-date Spring Tools 4 distribution on top of Eclipse 2022-06. This wiki page of the user guide gives you a few hints how to migrate those projects: https://github.com/spring-projects/sts4/wiki/STS3-Migration. Another way would be to import the project as a fresh project into a fresh workspace using "Import -> Existing Maven Projects".

In case you are missing specific tooling features in the Spring Tools 4 for Eclipse distribution that would make your life easier working with your legacy project, please tell us and create an enhancement request here: https://github.com/spring-projects/sts4/issues/new/choose
