### ISSUE TITLE
About spring tool suite 4 

### ISSUE THREAD

**Issue by xiexie2904** [spring-projects/sts4#801]
I want to ask we have any add on that support for sts 4 updated . I am following a tutorial, before the update they use add-on 3 
to create new spring beans configuration files,....

but with recently add-on 3 stopped maintained. So are there any ways to support for create those. Thanks so much

**Comment by martinlippert** [comment]
@xiexie2904 Since the old STS3 Add-On pack will not be maintained anymore, I would like to see how we can make your life easier in the Spring Tools 4 moving forward. What exactly are you missing? Support for creating Spring XML config files? And if so, what exactly would be useful here, beyond just creating an empty file?

In case my guesswork above is correct, I would also be interested to learn about why you are using Spring XML config files here. If the tutorial that you are referring to explains this as the best way to use Spring, it seems to be quite outdated. Since the STS3 Add-On pack is end-of-life, the above mentioned tutorial should better the updated instead of bringing old tooling back. You should probably think about using a different, more up-to-date tutorial that starts with using Spring Boot and the annotation-based style of constructing your application with Spring (at least that would be my recommendation).

**Comment by martinlippert** [comment]
No additional details provided for this one here, so closing this for now. If you hav additional thoughts and comments, please let us know and we can re-open.
