### ISSUE TITLE
no apache servers?

### ISSUE THREAD

**Issue by mavisguo** [spring-projects/sts4#81]
Why there are no Apache Tomcat or Jetty Servers?

**Comment by lzysuqianqiu** [comment]
install Jboss Tools

**Comment by martinlippert** [comment]
Yes, the Spring Tools 4 for Eclipse distribution comes without all the various server adapters pre-installed, since we tried to reduce the size and the number of pre-installed plugins to a somewhat minimum in order to keep it as small and lightweight as possible.

You can easily get those server adapters back by going to `Install New Software`, like described here: https://stackoverflow.com/questions/52004876/apache-tomcat-server-not-in-list-to-add-new/52039440#52039440

Installing JBoss Tools might be another option.

**Comment by kdvolder** [comment]
Just wanted to add some little bit of extra info on why this fits with the goal of STS 4 to mainly support the typical development of spring-boot apps. With spring boot app 'jar' packaging you don't really need to install tomcat or jetty anymore because it comes with an embedded tomcat (default) or jetty (as a optional project dependency you can easily get with small change to pom or gradle build).

This is now really the recommended way to run your boot apps. It avoids all of the complexities of having to manage tomcat or jetty server installations to be able to deploy and run war files. It makes things so much simpler because you can just package and run the boot app all by itself without needing some external server to deploy it too.

We do recognize not everybody can just decide from one day to the next to convert all their projects to jar-packaged boot apps, so you can still install the old-fashioned server-based tooling for deploying war projects, but it is now no longer what we are assuming/encouraging most people to be doing nowadays.

If at all possible I encourage you to explore packaging your apps as standalone boot-apps. You might be pleasantly surprised how much easier it makes things when you don't have to worry about what server to deploy it to :-)

**Comment by mavisguo** [comment]
Ok. thx!

**Comment by AlejandroMontes** [comment]
The solution is in: 
https://github.com/spring-projects/sts4/issues/93

Regards!
Alejandro Montes
