### ISSUE TITLE
Java document symbol request is slow in vscode

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#814]
**Describe the bug**
Open a java file and trigger document symbols. It takes more that 20s to list the document symbols regardless there are spring symbols or not.

**To Reproduce**
Open a java file in a project where spring-core is part of transitive dependencies. List document symbols.

Disabling the spring boot extension cause the symbols to appear instantly. And also its only the first call the document symbol on a given class takes time, the consecutive calls are instant.

*Extension Version*
v1.37.0

**Comment by martinlippert** [comment]
I think this could be related to https://github.com/spring-projects/sts4/issues/808, at least be caused by the same underlying issue. Can you try the latest CI build of the spring boot extension VSIX from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html to see if that fixes this issue?

**Comment by gayanper** [comment]
Still exist with latest build, disabling this extension will speedup, it also speed up workspace symbol search.

**Comment by martinlippert** [comment]
@gayanper Thanks a lot for trying the latest CI builds, much appreciated. Do you think this has changed with the latest releases? So if you switch to an older version of the Spring Boot Tools extension in VSCode, does this speed things up again as well?

**Comment by gayanper** [comment]
@martinlippert seem like this was a issue from path, it exist even in 1.33.0. This is prominent for projects which has more that 100/500 classpath entries.

**Comment by martinlippert** [comment]
@gayanper Ok, good indicator here. When the extension sees the project for the first time, it scans/parses the source files in order to create the symbol information, so that might take a little while when the classpath is larger. But we have a cache in place, so when the extension sees the project for the second time (e.g. after restarting the IDE), it uses the symbols from the cache - which should be a lot faster.

But nevertheless, if you observe a response time of 20s before anything shows up, that is a problem that we need to solve. Do you have a sample project at hand that you could share to reproduce the slowness?

**Comment by gayanper** [comment]
Some thing I also note is this happens for class files, I mean binary classes which comes from classpath dependencies. This doesn't happen for source files. May be something extra happening when a class file symbols are requested from spring-boot ls

**Comment by gayanper** [comment]
Also I noticed that jdt.ls ready time is reduced when spring boot ls is disabled. One thing I note is the project dependency resolution runs for long time when boot.ls is enabled.

**Comment by martinlippert** [comment]
> Also I noticed that jdt.ls ready time is reduced when spring boot ls is disabled. One thing I note is the project dependency resolution runs for long time when boot.ls is enabled.

Lets file a separate issue for this one (which we need to investigate and improve as well, of course)

**Comment by martinlippert** [comment]
> Some thing I also note is this happens for class files, I mean binary classes which comes from classpath dependencies. This doesn't happen for source files. May be something extra happening when a class file symbols are requested from spring-boot ls

Interesting. I tried this with my VSCode using a Petclinic sample and opened a type from the classpath (I tried `java.lang.String` as well as `org.springframework.stereotype.Controller`), but pressing Cmd-Shift-O to show the document symbols show up instantly, same for Cmd-T to search for workspace symbols.

I have the Java extension configured to `Standard` for the `Launch Mode` (instead of hybrid or light modes), in case that makes a difference here.

Do you have a sample project and a few steps how to reproduce this? It looks like I am doing something slightly different, so that the problem doesn't appear yet on my end.

**Comment by martinlippert** [comment]
@gayanper Now that we have the 4.16.0.RELEASE out the door, lets investigate this in more depth. Can you share a sample project that reproduces the issue somehow and a few steps how to reproduce this? My initial tests are not showing a slowdown, but I am most likely not doing the right thing to cause the issue to appear on my end.

> Also I noticed that jdt.ls ready time is reduced when spring boot ls is disabled. One thing I note is the project dependency resolution runs for long time when boot.ls is enabled.

How do you measure/watch these things?

**Comment by gayanper** [comment]
> @gayanper Now that we have the 4.16.0.RELEASE out the door, lets investigate this in more depth. Can you share a sample project that reproduces the issue somehow and a few steps how to reproduce this? My initial tests are not showing a slowdown, but I am most likely not doing the right thing to cause the issue to appear on my end.
> 
> > Also I noticed that jdt.ls ready time is reduced when spring boot ls is disabled. One thing I note is the project dependency resolution runs for long time when boot.ls is enabled.
> 
> How do you measure/watch these things?

Sure i will try to reproduce this with latest extensions again and try to find a opensource project where you can also test if i still find the issue. Give me 3.-4 days to come back with the results.

**Comment by martinlippert** [comment]
Sure, thanks @gayanper for helping with the investigation here, very much appreciated!!!

**Comment by gayanper** [comment]
I cannot see the issue with latest version of springboot extension together with java extension. Hence I will close this and reopen if I come across again with either the project or some flight recordings with method samples.

**Comment by martinlippert** [comment]
@gayanper Thanks for coming back to this and for the update, much appreciated.

**Comment by martinlippert** [comment]
Just a quick additional comment here: I worked on a few additional improvements in this space around the symbols machinery in order to improve the responsiveness for symbol requests, so might have a positive impact on this as well. In case you would like to try that, feel free to manually install the latest VSIX from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html
