### ISSUE TITLE
Update to 4.15.3 from 4.14  clears Available Software Sites

### ISSUE THREAD

**Issue by space88man** [spring-projects/sts4#817]
**Describe the bug**
Successful upgrade from STS 4.14 to 4.15.3 (including Eclipse from 2022-03 to 2022-06)
At the end of the upgrade process the "Available Software Sites" was empty.

**To Reproduce**
* install STS 4.14
* upgrade to STS 4.15 using "Check for Updates"

**Sample**

N/A

**Comment by martinlippert** [comment]
Thanks @space88man for reporting this. I tried to reproduce this, but wasn't able to (the update sites remain the same when I try the steps you described), so it looks like something special happened on your end. I think I saw something like this before a while ago, but were never really able to reproduce or find the root cause.

For your convenience, you can bring back the standard update sites by creating an XML file with the following content and importing this in the preferences for the available update sites. Hope this helps to get back to the regular state here.

```
<?xml version="1.0" encoding="UTF-8"?>
<bookmarks>
   <site url="https://download.eclipse.org/releases/latest" selected="true" name="Latest Eclipse Release"/>
   <site url="https://download.springsource.com/release/TOOLS/sts4/update/latest" selected="true" name="Spring Tool Suite 4"/>
   <site url="https://download.springsource.com/release/TOOLS/sts4-language-server-integrations" selected="true" name="Spring Tools 4 Language Servers for Eclipse"/>
</bookmarks>
```
