### ISSUE TITLE
STS is hanging up a lot. Keeps on showing not responding. 

### ISSUE THREAD

**Issue by developerNamrataKhatwani** [spring-projects/sts4#854]
Please tell me the minimum system requirements for STS4?

**Comment by martinlippert** [comment]
The default max memory heap when running the Spring Tools 4 distribution for Eclipse is set to 2GB of heap space (while the JVM itself will consume additional memory), the language server processes that are running as separate processes will consume extra memory, but that depends a lot on the size of your workspace and which editors you keep opened.

You can enable a memory usage indicator in the preferences, so that you can see the exact heap usage of the JVM in the status bar. Maybe you can enable that to see if memory is an issue here?

Also it might be useful to capture a few thread dumps (using jps and jstack) while the IDE is not responding or is extremely slow and attach those thread dumps here. Maybe they reveal some details about what exactly is going on under the hood when the IDE is slow or hanging.

It would also be useful to know which operating system you are running on, which version of the tooling you are using, and whether you have any specific steps or sample projects that could help to reproduce the issue.

**Comment by martinlippert** [comment]
No further feedback or details on this one, so closing the issue for now. If you still observe that STS is hanging a lot please re-open and provide a few more details (as described in the comment above) to allow us to investigate the issue further.
