### ISSUE TITLE
boot dashboad not available in Eclipse 2022-09

### ISSUE THREAD

**Issue by kalpeke** [spring-projects/sts4#878]
**Describe the bug**
Spring tools menu is not listed on eclipse **Window->Show View->other** after upgrading to eclipse 2022-09 or a fresh install of same
**To Reproduce**
Install a fresh install of eclipse 2022-09 or upgrade to same from version 2022-06 that already had Spring tools installed(for upgrade the spring dash icon disappears from menu bar and is also not available in show menu)

versions: 
============================================ ECLIPSE====================
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2022-09 (4.25.0)
Build id: 20220908-1902
OS: Linux, v.5.19.0-23-generic, x86_64 / gtk 3.24.34
Java vendor: Azul Systems, Inc.
Java runtime version: 11.0.11+9-LTS
Java version: 11.0.11
================================================= Spring Tools==================
  Spring Boot Language Server Feature	4.16.1.202210240737	
  Spring IDE Boot Microservices Dash	4.16.1.202210240748	
  Spring Tool Suite 4 Main Feature	4.16.1.202210240748	
   Spring XML Namespace Support	4.16.1.202210240748	

**Sample**

I believe its same issue as https://stackoverflow.com/questions/62451896/spring-boot-dashboard-not-available-in-eclipse-version-2020-06

**Comment by martinlippert** [comment]
Here is what I tried a moment ago to see if I can reproduce this:

- installed a fresh Eclipse 2022-09 JEE package
- install Spring Tools 4 using the Eclipse Marketplace client from the help menu

After that (and accepting some outdated signatures during the installation process) the dashboard appears just fine when I switch to the Java perspective, the icon is in the menu bar - and everything looks just fine. So the question here is what is different on your end, so that the dashboard doesn't appear on your machine.

The one thing that I notice is that your Eclipse installation runs on a JDK 11 from Azul, which is not the correct version to run Eclipse 2022-09 (and beyond). The minimum requirement is actually a JDK 17 - which comes embedded and auto-configured if you download and install either Eclipse 2022-09 or Spring Tools 4 for Eclipse 4.16.1 (from https://spring.io/tools).

I would recommend to switch this back to the standard configuration (via a fresh install or by modifying the `eclipse.ini` file manually) to point the IDE to a JDK 17.

As a side note (just in case this question comes up): The JDK that you use to run your IDE is unrelated to the JDK that you use to compile and run your projects inside of the IDE. You can have a JDK 11 configured in the preferences when running the Eclipse IDE for your projects to use without running the IDE itself on that same JDK.

**Comment by martinlippert** [comment]
@kalpeke Thanks for letting us know. Closing this now.
