### ISSUE TITLE
Add the Dashboard to Help menu

### ISSUE THREAD

**Issue by batterista87** [spring-projects/sts4#88]
The dashboard including the Tooling Updates and news, is missing in the Help menu.

**Comment by martinlippert** [comment]
That is "by design"... ;-) We have deprecated the dashboard that was included in STS 3 and don't include that going forward with Spring Tools 4 anymore.

Which parts of that dashboard are you missing most? We are always looking for feedback and might introduce something else instead, but therefore we need to know what you are missing or what you would benefit from. Want to share some thoughts with us?
