### ISSUE TITLE
[refactoring] reduce size of execute rewrite recipes messages

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#897]
The message for the command `sts/rewrite/execute` contains lots of data and has a size of about 500Kb (in my tests). This doesn't seem to be reasonable and we should reduce the size down to the data that is really needed to identify the selected recipes and their params (as a first guess).

**Comment by BoykoAlex** [comment]
The `sts/rewrite/list` needs improvements in this area as well. Likely we need to flatten the recipe tree such that when navigating inside the recipe we'd load more data for sub-recipes rather than load everything at once.
There is going to be quite a bit of work. Size of the recipe descriptor json has grown thus we'd need to address this rather soon.

**Comment by BoykoAlex** [comment]
Should be fixed with d6ff60a96e0701b3972350a5b4271bab48c6df98
Instead of loading. all recipes and sub-recipes lazy load sub-recipes on demand. Instead of sending recipe descriptors to instatiate recipes on the LS side send selected recipes json.
