### ISSUE TITLE
Add checksums at download page

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#906]
Not sure if it is the correct place but, here we go.

Currently at [https://spring.io/tools](https://spring.io/tools) is possible download in peace STS4 according to all OS, but where are the checksums? I think would be nice add them. 

Consider it as a friendly suggestion.

**Comment by martinlippert** [comment]
We have checksum files around (replace the file extension in the download link with `.md5` or `sha1`, but due to the downloads being available via https only, I am not sure whether you really need a checksum to verify. Nevertheless, you can find them there. We should probably update sha1 to sha256 though.

**Comment by manueljordan** [comment]
You are the expert here, but I just confirmed that Gradle and Maven for example have/use https to download their installers too and offer the checksum.

**Comment by martinlippert** [comment]
I updated the build to produce checksums in SHA-256 now instead of SHA-1, so from the upcoming `4.17.0` release you can get the checksums my replacing the file extension of the general distribution download links with `.md5` or `.sha256` and get the checksums. Hope this works for you. And thanks for raising this, much appreciated.

**Comment by martinlippert** [comment]
But we will not add links to the checksums to the download page - to avoid too much clutter in that area.

**Comment by manueljordan** [comment]
Understood, but I think is wise add an indication about your approach in the page - btw really is enough add only the `.md5` or `.sha256` to the current URL, so is not necessary replace the file extension.

**Comment by martinlippert** [comment]
Haha, you are absolutely right, not replace the file extension, just append it. My fault. Thanks for pointing that out!!!
