### ISSUE TITLE
XML editor preferences in Eclipse have no effect on editing pom.xml

### ISSUE THREAD

**Issue by ykartsev** [spring-projects/sts4#963]
Dear STS Team!

Looks like I'm unable to change specific XML editor preferences (colors, indentation, etc.) for editing pom files of my Spring Boot projects in Eclipse. Any other XML file correctly uses preferences set in Eclipse, while when editing pom files it seems that some hard-coded set of preferences is used, because colors look different, as well as indentations, etc.

Steps to reproduce:
1. Create or import a Spring Boot Maven project into Eclipse IDE with installed STS plugin.
2. Open pom.xml.
3. Create and open any other other.xml file with some contents in the same folder as pom.xml, observe color difference (depending on your setup).
4. Open IDE Preferences -> XML -> XML Files -> Editor and update indentation size, as well as colors in XML Files -> Editor -> Syntax Coloring.
5. Open pom.xml, observe no changes in coloring or indentation preferences.
6. Open other.xml, observe color/indentation preferences in effect.

The same appears to happen with application.properties files and other properties files in the same folders (Preferences -> Java -> Properties Files Editor)

My Eclipse version is 2022-12 (4.26.0), Build id: 20221201-1913
STS version is 4.17.1.202301011700

Am I doing something wrong here? Please advise.

Thank you in advance!

**Comment by martinlippert** [comment]
Hey @ykartsev, the reason for this difference is that there are different editors involved here. The editors `Properties File Editor` and the `XML Editor` are the old ones, all based on the platform and coming with their own set of preferences and highlighting logic/settings.

The new editors for the `pom.xml` file as well as the `Spring Properties Files` are based on the Generic Editor, which can be configured for various languages and grammars. This is why you see the difference, depending on which editor you use.

The style and coloring of the new generic editor is done by https://github.com/eclipse/tm4e and can be configured via CSS, see the preferences at `TextMate -> Theme`. It would indeed by good to unify this across the different editors, but due to the different technologies being used here, I don't think this would be easy.

**Comment by ykartsev** [comment]
Thank you @martinlippert ! That's **very** helpful and some new information indeed. The main thing for me is that I'll now be able to update those preferences which I could not find before and it was not very intuitive where they may be. But you helped a lot, the ticket can now be closed I think. Thank you once again!

**Comment by ykartsev** [comment]
@martinlippert , quick question... I figured how to configure colors and some specific Language Configurations. Would you know how to configure indentation size?

**Comment by martinlippert** [comment]
@ykartsev If this auto-formatting setting is something that you would like to specify for the `pom.xml` file only, you can ask for this on the m2e project where the maven-specific extensions for the XML editor lives: https://github.com/eclipse-m2e/m2e-core.

If this is something that applies to editing XML files via the XML language server and its integration via the general editor, you can ask the team behind the wild web developer project here: https://github.com/eclipse/wildwebdeveloper
